-- Migration 015: Add 20 games to page 2
-- Created: 2024
-- Description: Add 20 new games to page 2 with Portuguese translations

-- Adicionar 20 novos jogos na página 2
INSERT INTO games (
  id, title, description, instructions, url, category, tags, thumb, width, height, views, likes, page
) VALUES 
(
  '18296',
  'Montanha de Neve ZigZag',
  'Just Freeskiing é uma simulação de esqui/freeski altamente autêntica com infinitas possibilidades para ajustar, estilizar e combinar truques realistas! Os numerosos locais de desafio Slopestyle, Halfpipe, Big-Air, Jibbing (Rails, Boxes) e Backcountry cobrem uma grande variedade de freeskiing.',
  'Controle do Mouse',
  'https://html5.gamemonetize.com/s94xp6bhitgjcptd98dyph9u5m7i922m/',
  'Hypercasual',
  '.io Games, 2 Player Games, 3D Games, Adventure, Arcade, Casual, drifting, Fun, Hypercasual, Island, Snow',
  'https://img.gamemonetize.com/s94xp6bhitgjcptd98dyph9u5m7i922m/512x384.jpg',
  800,
  600,
  0,
  0,
  2
),
(
  '4865',
  'Quebra-Cabeça do Herói Resgate',
  'Você gosta de jogos de resgate? Claro, eles são ótimos. Ajude o herói a resgatar e salvar a princesa e conseguir o tesouro no novo jogo hero wars - Hero Rescue. Atire nos bastões para salvar a princesa, matar os goblins, conseguir um tesouro... Você se tornará um herói rico neste jogo de resgate da cidade.',
  'Controle do mouse',
  'https://html5.gamemonetize.com/3596x93682lmj4cn7mrtldmfhviig7jj/',
  'Puzzles',
  'Action, Boys, Fun, Girls, HTML5, Logic, Puzzle',
  'https://img.gamemonetize.com/3596x93682lmj4cn7mrtldmfhviig7jj/512x384.jpg',
  800,
  600,
  0,
  0,
  2
),
(
  '7451',
  'Bolas do Amor 2D',
  'É hora de usar seu cérebro e encontrar uma maneira de bater as bolas! A regra é fácil, apenas desenhe linhas ou formas para bater as bolas, você precisará de sua sabedoria e imaginação.',
  'Use o mouse para jogar',
  'https://html5.gamemonetize.com/1l6pgl750zi41o2cktmkmr71dntshaej/',
  'Puzzles',
  'Adventure, Arcade, Ball, Love, Puzzle',
  'https://img.gamemonetize.com/1l6pgl750zi41o2cktmkmr71dntshaej/512x384.jpg',
  900,
  600,
  0,
  0,
  2
),
(
  '20593',
  'Copo Feliz: Encha o Copo Desenhando Linhas',
  'Simplesmente enchendo o Copo Feliz com Desenhar Linhas, Faça um Corvo Feliz. Tente encontrar a melhor maneira de completar cada nível. Você pode criar sua própria solução, então seja criativo e não tenha medo de pensar fora da caixa!',
  'Desenhe Linhas com Clique Esquerdo do Mouse',
  'https://html5.gamemonetize.com/dayksem3hjbea9vsbklh6wqi213w9121/',
  'Puzzles',
  'Boys, Click, Draw, Games, Girls, HTML, HTML5',
  'https://img.gamemonetize.com/dayksem3hjbea9vsbklh6wqi213w9121/512x384.jpg',
  600,
  900,
  0,
  0,
  2
),
(
  '13555',
  'Pou Online',
  'Você tem o que é preciso para cuidar do seu próprio animal de estimação alienígena? Alimente e cuide do Pou.',
  'Controle do mouse',
  'https://html5.gamemonetize.com/jyeazqa0x7ym5xcq22g9mgv74s5tift1/',
  'Puzzles',
  'Boys, Girls, HTML5',
  'https://img.gamemonetize.com/jyeazqa0x7ym5xcq22g9mgv74s5tift1/512x384.jpg',
  800,
  600,
  0,
  0,
  2
),
(
  '7296',
  'Tiro Noturno de Ursos Zumbis',
  'Zumbis caminham entre nós! Você é um dos poucos sobreviventes de uma infecção pandêmica. O apocalipse zumbi começou depois que um cientista derrubou um frasco de vírus em um laboratório secreto. Como um atirador de elite experiente, você tem experiência em campo de tiro e foi treinado em estratégia militar para jogos de guerra de caos, ação e sobrevivência.',
  'Controle do mouse',
  'https://html5.gamemonetize.com/a8i3hhixhynwz435k72ub0ichgummyfw/',
  'Adventure',
  '2D, Adventure, Fight, Unity3D, Zombie',
  'https://img.gamemonetize.com/a8i3hhixhynwz435k72ub0ichgummyfw/512x384.jpg',
  900,
  600,
  0,
  0,
  2
),
(
  '10144',
  'Trilhos do Telhado - Pilha de Cores 3D',
  'Bem-vindo para jogar jogos de trilhos do telhado 3d de 2021 com corrida de atalho gigante empurrador gordo 3d para fazer jogos de trilhos do telhado deslizantes divertidos usando truques de pista complicada de corrida de atalho para deslizamento gigante desta nova aventura de empurrador gordo de trilho do telhado jogos para meninas e meninos.',
  'Controle do teclado',
  'https://html5.gamemonetize.com/3zsuu4fl12ujvfaa5yett2t1rclzg9jj/',
  'Arcade',
  '.io Games, 3D, Adventure, Arcade, Train',
  'https://img.gamemonetize.com/3zsuu4fl12ujvfaa5yett2t1rclzg9jj/512x384.jpg',
  600,
  900,
  0,
  0,
  2
),
(
  '6152',
  'Among Us Edição Online',
  'Bem-vindo ao jogo Among Us Online Edition - jogo baseado em Among Us, mas neste jogo você pode jogar apenas solo e como impostor na nave espacial. Você pode fazer sabotagem na nave espacial ou matá-los um por um sem ser pego. Tenha um bom jogo!',
  'Use o mouse para jogar',
  'https://html5.gamemonetize.com/luye5rleios737wp2o9wjq7h577gl937/',
  'Arcade',
  '1 Player, Action, Arcade, Multiplayer, Shooter, Shooting',
  'https://img.gamemonetize.com/luye5rleios737wp2o9wjq7h577gl937/512x384.jpg',
  800,
  600,
  0,
  0,
  2
),
(
  '2178',
  'Minecraft Remake',
  'Jogo clássico do minecraft! Explore mundos infinitos e construa tudo, desde as casas mais simples até os castelos mais grandiosos.',
  'WASD ou Setas Mover - Shift Esquerdo Correr - Mouse Olhar - Roda do Scroll Trocar Bloco - Espaço Pular - Botão Direito do Mouse Colocar Bloco - Botão Esquerdo do Mouse Destruir Bloco',
  'https://html5.gamemonetize.com/cznxajp3hzb8l7gtebaq96s0pbrfa33m/',
  'Boys',
  '3D, Adventure, Craft, Crafting, HTML5, Minecraft, Unity3D, WebGL',
  'https://img.gamemonetize.com/cznxajp3hzb8l7gtebaq96s0pbrfa33m/512x384.jpg',
  960,
  600,
  0,
  0,
  2
),
(
  '2461',
  'Básico do Baldi v1.4.3',
  'Básico do Baldi v1.4.3 - Inspirado por jogos educacionais assustadores/ruins dos anos 90, Básico do Baldi é um jogo de terror meta que é realmente estranho, sem valor educacional real a ser encontrado. O objetivo do jogo é coletar sete cadernos e depois escapar da escola, mas isso é mais fácil falar do que fazer!',
  'WASD - Mover Shift - Correr LBM - Ação Espaço - Olhar para trás',
  'https://html5.gamemonetize.com/iiifrxhcnzl5laslqf3eaedtevjzb2bu/',
  'Boys',
  '3D, Fun, HTML5, Math, WebGL',
  'https://img.gamemonetize.com/iiifrxhcnzl5laslqf3eaedtevjzb2bu/512x384.jpg',
  900,
  600,
  0,
  0,
  2
),
(
  '16062',
  'Tom Falante Corrida do Ouro Online',
  'Tom Falante Corrida do Ouro Online é o melhor jogo de corrida de gato. Desfrute de horas de diversão com seu gato querido, corra para coletar moedas de ouro depois de ser roubado neste jogo de corrida infinita! Explore novos mundos, apenas correndo com velocidade rápida.',
  'Toque ou clique',
  'https://html5.gamemonetize.com/hn5dh0x6wcnroy3p33ogeyu5z6xsltvw/',
  'Adventure',
  'Action, Adventure, Animal, Boy, Boys, Cat, Collecting, Collection, H5, HTML5, run',
  'https://img.gamemonetize.com/hn5dh0x6wcnroy3p33ogeyu5z6xsltvw/512x384.jpg',
  644,
  644,
  0,
  0,
  2
),
(
  '15409',
  'Corrida de Bicicleta',
  'Seja você menino ou menina, há muitos personagens FUNKY para satisfazer e muitas bicicletas legais para ganhar! Colete moedas, complete missões, passe de nível e assim por diante! Atualizado com os recursos e conteúdo mais legais do jogo, você vai adorar fazer flips, truques e acrobacias nas encostas.',
  'Mouse ou clique para jogar',
  'https://html5.gamemonetize.com/4bb52narsr9s57z5y7qlch5zhupiucld/',
  'Adventure',
  'Action, Adventure, Baby, Baby Hazel, Boy, Classic, Driving, Hypercasual, subway, Superhero, Traffic',
  'https://img.gamemonetize.com/4bb52narsr9s57z5y7qlch5zhupiucld/512x384.jpg',
  720,
  1280,
  0,
  0,
  2
),
(
  '21144',
  'Empurre a Multidão Louca: Confronto Stickman 3D',
  'Empurre a multidão louca - confronto stickman 3d é um jogo hiper casual divertido. Empurre todos para fora da plataforma com apenas um deslizar do dedo. Abra caminho através da batalha de corrida da multidão para chegar à linha de chegada como um mestre invicto da corrida da multidão stickman.',
  'Jogue com Controles do Mouse - Empurre Inimigos Clicando no Controle Esquerdo do Mouse',
  'https://html5.gamemonetize.com/91juk8nwy961yt1uu7jloxvwoe3awabu/',
  'Hypercasual',
  'Boys, HTML, HTML5, run, running',
  'https://img.gamemonetize.com/91juk8nwy961yt1uu7jloxvwoe3awabu/512x384.jpg',
  600,
  900,
  0,
  0,
  2
),
(
  '4995',
  'Super RunCraft',
  'Super RunCraft é um maravilhoso jogo de corrida 3D, corra através de uma longa terra minecraft para coletar fileiras de moedas douradas, número de itens especiais como Hoveboard ao longo de sua pista de corrida e evite os obstáculos em seu caminho. O jogo de corrida infinita de estilo clássico que sempre lhe dá uma grande diversão fantástica minecraft.',
  'Teclas de seta ou Toque para Jogar',
  'https://html5.gamemonetize.com/syoymgm7jw290t7mz0hpqjqmc8yqlmrd/',
  'Arcade',
  'Kiz 10, kiz10, running',
  'https://img.gamemonetize.com/syoymgm7jw290t7mz0hpqjqmc8yqlmrd/512x384.jpg',
  525,
  700,
  0,
  0,
  2
),
(
  '5028',
  'Fall Bros',
  'A experiência definitiva do Fall Guys para a web: Fall Bros! Jogue o nível mais popular Hex-A-Gone a qualquer hora e gratuitamente! Sobreviva o máximo possível não caindo. Chute seus oponentes para fora das plataformas. Melhore seu jogo com estratégias inteligentes!',
  'WASD para mover ESPAÇO para pular',
  'https://html5.gamemonetize.com/vnvpo9h7zc6phugavlw7xni2thz4no4i/',
  'Action',
  '.io Games, 3D, Action, Casual, Game, Platform',
  'https://img.gamemonetize.com/vnvpo9h7zc6phugavlw7xni2thz4no4i/512x384.jpg',
  800,
  600,
  0,
  0,
  2
),
(
  '6079',
  'Among Us Corrida Espacial',
  'Jogue Among Us Rush agora no kiz10.com !!! Um novo jogo vem com o melhor estilo e com os personagens de Among Us corra e não pare de correr através das plataformas perigosas dos diferentes níveis do jogo, tenha muito cuidado porque você pode cair do penhasco ou colidir com diferentes obstáculos.',
  'Use Mouse ou Tela de Toque',
  'https://html5.gamemonetize.com/3iaqi4b196ujgycgvjnxhegwcj0y4617/',
  'Hypercasual',
  'Jumping, Kiz 10, kiz10, running',
  'https://img.gamemonetize.com/3iaqi4b196ujgycgvjnxhegwcj0y4617/512x384.jpg',
  800,
  500,
  0,
  0,
  2
),
(
  '10521',
  'Vândalos do Skate',
  'Cowabunga! Pequenos vândalos estão a caminho! Escolha seu herói e organize uma desordem incrível ^_^ Colete moedas, melhore bônus, compre skates legais, evite obstáculos perigosos e obtenha pontuações o máximo que puder.',
  'Setas Deslizes para mover',
  'https://html5.gamemonetize.com/vy07es6s71vci1su3wzcqrp7e3ym0vtw/',
  'Arcade',
  '3D, 3D Games, Action, Arcade, Best, city, endless, Highscore, Kids, run, running, Skateboard, subway, Subway Surfers, WebGL',
  'https://img.gamemonetize.com/vy07es6s71vci1su3wzcqrp7e3ym0vtw/512x384.jpg',
  800,
  600,
  0,
  0,
  2
),
(
  '15736',
  'Desafio Round 6 3D',
  'Convite para o Round 6. Convite para um jogo justo de Sinal Vermelho, Sinal Verde. Quem ganhar este jogo receberá uma grande quantia em dinheiro de prêmio. Pare no sinal vermelho. Continue quando o sinal verde estiver ligado. Siga os movimentos da cabeça do seu personagem! Não se apresse.',
  'Controle do Mouse',
  'https://html5.gamemonetize.com/dtemvyguxvsbdnnoilu3s1ygg8umdbvt/',
  'Shooting',
  '.io Games, 1 Player, 2 Player Games, 3D Games, Action, Adventure, Best, Game, Games, Kill, Killing, Online, Shoot, Shoot Em Up, Shooter, Shooting',
  'https://img.gamemonetize.com/dtemvyguxvsbdnnoilu3s1ygg8umdbvt/512x384.jpg',
  600,
  900,
  0,
  0,
  2
),
(
  '4392',
  '12 MiniBatalhas',
  '12 MiniBatalhas é um jogo multiplayer divertido onde você e um amigo podem jogar um contra o outro em uma variedade de jogos. Este jogo de estilo físico tem diferentes tipos de jogos que você pode jogar aleatoriamente, incluindo uma partida de futebol e guerra de franco-atiradores.',
  'Jogador 1 use A Jogador 2 use L',
  'https://html5.gamemonetize.com/nuiyi3o2g6fktyjda55g42v3qe5a3hbq/',
  'Arcade',
  '2 Player, 2 Player Games, 2D, Arcade, Family, Flight, Retro',
  'https://img.gamemonetize.com/nuiyi3o2g6fktyjda55g42v3qe5a3hbq/512x384.jpg',
  1280,
  720,
  0,
  0,
  2
),
(
  '18622',
  'Tap Tap Recarregado',
  'Toque junto com todas as suas músicas favoritas neste jogo de ritmo acelerado! Tap Tap Reloaded é a experiência definitiva de jogo de ritmo orientado pela comunidade. Reloaded é construído no que a comunidade quer em um jogo de ritmo móvel.',
  'Controle do mouse',
  'https://html5.gamemonetize.com/ogindx0i77db45yzyg8950b6lhirpfsq/',
  'Hypercasual',
  '.io Games, 2 Player Games, 3D Games, Adventure, Arcade, Baby, Casual, Family, Hypercasual, Logic, Unity3D',
  'https://img.gamemonetize.com/ogindx0i77db45yzyg8950b6lhirpfsq/512x384.jpg',
  800,
  600,
  0,
  0,
  2
),
(
  '3921',
  'Tom e Jerry Corrida',
  'Tom and Jerry Run é um jogo de corrida infinita divertido como subway surfers! Corra com Jerry através da cidade do metrô e pule sobre obstáculos para coletar moedas de ouro como no talking tom gold run!',
  'Use mouse ou teclado',
  'https://html5.gamemonetize.com/a6d9kqfsjxbpdktw6p8j11z8bm776t8h/',
  'Action',
  '.io, 3D, 3D Games, endless, run, running, subway, Subway Surfers, surfers',
  'https://img.gamemonetize.com/a6d9kqfsjxbpdktw6p8j11z8bm776t8h/512x384.jpg',
  800,
  600,
  0,
  0,
  2
);

-- Verificar se os jogos foram adicionados corretamente na página 2
SELECT COUNT(*) as total_jogos_pagina_2 FROM games WHERE page = 2; 