-- Migration 017: Adicionar jogos da página 3
-- Adiciona 32 jogos traduzidos para português na página 3

INSERT INTO games (
  external_id, 
  title, 
  description, 
  instructions, 
  url, 
  category, 
  tags, 
  thumb, 
  width, 
  height, 
  page
) VALUES 
(
  '34219',
  'Corrida da Luz',
  'Balance, pule, gire e deslize seu corpo de mestre stickman flip de uma forma neon colorida para outra para fazê-las brilhar e acender. É um mundo escuro lá fora para um pequeno mestre stickman flip como você, e é hora de acender e fazer as cores brilharem.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/gskztfg8o3i7aeh66zmn8flgkttfftdw/',
  'Fighting',
  'Ação, Aventura, Casual, Pular, Correr, Stickman, Super',
  'https://img.gamemonetize.com/gskztfg8o3i7aeh66zmn8flgkttfftdw/512x384.jpg',
  480,
  800,
  3
),
(
  '34218',
  'Super Motocross',
  'Pilote sua moto dirt através de níveis desafiadores cheios de rampas, saltos e obstáculos. Balance, acelere e chegue à linha de chegada sem bater! Um jogo HTML5 de motocross divertido e acelerado para todas as idades.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/d8vjyjtwgj1c7opsa1e99ifmvnfvgvn8/',
  'Sports',
  'Arcade, Jogos Mapi, Motocross, Motocicleta',
  'https://img.gamemonetize.com/d8vjyjtwgj1c7opsa1e99ifmvnfvgvn8/512x384.jpg',
  1280,
  800,
  3
),
(
  '34217',
  'Esconde-Esconde Amigos!',
  'O bom e velho clássico esconde-esconde. Jogue como um procurador ou como um escondedor e construa seus abrigos de carros ou mesas de escritório, esconda-se na água, no monte de feno, no milharal, no escritório do chefe e, mais importante, empurre outros no campo de visão dos procuradores.',
  'Bem-vindo ao mundo do Esconde-Esconde 3D',
  'https://html5.gamemonetize.com/c55i7d1tly2sovcobi9j3i13cpz0iekw/',
  'Arcade',
  'Jogos .io, Ação, Arcade, Online, Estratégia',
  'https://img.gamemonetize.com/c55i7d1tly2sovcobi9j3i13cpz0iekw/512x384.jpg',
  600,
  960,
  3
),
(
  '34216',
  'Cone de Sorvete Enrolado DIY',
  'O verão está chegando! Você não quer experimentar um sorvete gelado? Que tal sobremesas deliciosas de verão? Bem-vindo ao Cone de Sorvete Enrolado DIY, um jogo casual de comida DIY para crianças. Refresque-se com esta simulação de culinária de sobremesa de sorvete projetada contra o verão quente!',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/lp9qbdo722u21gngmsf02j1w1s1mfjfm/',
  'Hypercasual',
  'Comida, Gelo, Crianças',
  'https://img.gamemonetize.com/lp9qbdo722u21gngmsf02j1w1s1mfjfm/512x384.jpg',
  720,
  1280,
  3
),
(
  '34215',
  'Fábrica de Veículos',
  'Fábrica de Veículos é um jogo criativo de construção baseado em física onde suas habilidades de engenharia são testadas! Construa seu próprio veículo anexando componentes como rodas, rodas especiais e ventiladores. Uma vez que seu design esteja pronto, aperte o botão Iniciar e assista sua criação personalizada navegar por um mapa de física dinâmico.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/32n43ar75l12h5uru5qjr2djpqddupk2/',
  'Puzzles',
  'Ação, Cérebro, Carro, Mentolatux, Física, Quebra-cabeça, Unity, WebGL',
  'https://img.gamemonetize.com/32n43ar75l12h5uru5qjr2djpqddupk2/512x384.jpg',
  800,
  600,
  3
),
(
  '34214',
  'Salto Circular',
  'Controle a seta para correr para o próximo círculo. Aproveite o momento, para que a seta corra para evitar o vórtice. Venha experimentar e veja quantos pontos você pode ganhar.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/3irb0wmjx8kc93fohm9j22rxpeim8j2d/',
  'Shooting',
  '1 Jogador, Aventura, Arcade',
  'https://img.gamemonetize.com/3irb0wmjx8kc93fohm9j22rxpeim8j2d/512x384.jpg',
  350,
  600,
  3
),
(
  '34212',
  'Sprunki Trilhos Mortos',
  'Sprunki Trilhos Mortos - proteja o trem! Sobrevivência cooperativa contra zumbis com construção de blocos. Para facilitar o jogo, você pode comprar uma torre que ajudará a destruir zumbis. Jogue em um dos 6 mapas. Os mapas são enormes! Jogue com um amigo ou no modo single player.',
  'No dispositivo móvel os controles são fornecidos usando botões na tela. No PC - Jogador Azul: Movimento setas do teclado, Atirar J, Construir K - Jogador Vermelho: Movimento WASD, Atirar F, Construir',
  'https://html5.gamemonetize.com/iixpxl3s6ss7gqrvced5eaysnigvw0os/',
  'Boys',
  '1 Jogador, 2 Jogadores, Jogos 2 Jogadores, 2D, Melhores Jogos, Defesa, Mobile, Atirador, Sprunki, Tower Defense, Jogos Dois Jogadores, Zumbi',
  'https://img.gamemonetize.com/iixpxl3s6ss7gqrvced5eaysnigvw0os/512x384.jpg',
  800,
  600,
  3
),
(
  '34210',
  'Caminho Pixel',
  'Ajude um corajoso herói pixel a sobreviver a níveis alucinantes cheios de armadilhas mortais, teletransportadores e quebra-cabeças que desafiam a gravidade! Toque para virar o mundo de cabeça para baixo, pule sobre serras giratórias e colete gemas cintilantes para desbloquear novos mundos emocionantes.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/fcwz88fz1d52nffy0nemiduus7o8hahs/',
  'Puzzles',
  'Arcade, Casual, Hypercasual, Pixel, Quebra-cabeça, Estratégia, Armadilha',
  'https://img.gamemonetize.com/fcwz88fz1d52nffy0nemiduus7o8hahs/512x384.jpg',
  800,
  600,
  3
),
(
  '34208',
  'Sprunki Mod Ketchup',
  'Sprunki Mod Ketchup - Um jogo com física de arremessos e elementos ragdoll. Jogue ketchup para acertar o Sprunki e transformá-lo em uma versão ketchup! Tente sua sorte em 30 níveis! A dificuldade aumentará e os mapas crescerão. Pense com a cabeça: calcule a trajetória perfeita do arremesso e use os ricochetes para vencer!',
  'Sua missão é jogar ketchup no Simon. Use o ketchup como projétil, estique-o como um estilingue e jogue com precisão',
  'https://html5.gamemonetize.com/7tvjo8x6w1flu3fvadry5mz8qbhotkxo/',
  'Puzzles',
  '1 Jogador, 2D, Angry Birds, Casual, Mobile, Física, Sprunki',
  'https://img.gamemonetize.com/7tvjo8x6w1flu3fvadry5mz8qbhotkxo/512x384.jpg',
  800,
  600,
  3
),
(
  '34207',
  'Magia do Quebra-Cabeça de Blocos',
  'Monte e elimine os blocos. Blocos de várias formas aparecerão aleatoriamente na parte inferior. Arraste os blocos para a caixa superior. Eles serão eliminados quando uma linha ou coluna for preenchida. Venha experimentar.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/z6gxwxdgunqmjmhva7j5kszeya71ls9u/',
  'Puzzles',
  '1 Jogador, Arcade, Quebra-cabeça, Bloco de Quebra-cabeça',
  'https://img.gamemonetize.com/z6gxwxdgunqmjmhva7j5kszeya71ls9u/512x384.jpg',
  350,
  600,
  3
),
(
  '34206',
  'Simulador de Direção de Caminhão Offroad',
  'Experimente a emoção do caminhão offroad! Navegue por terreno acidentado, entregue carga através de caminhos desafiadores e domine caminhões poderosos em ambientes realistas. Conquiste colinas, lama e rios nesta aventura definitiva de simulador de direção de caminhão.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/a6i1ot5d0scwphehyrsl0vned0ezjk8q/',
  'Action',
  'Direção, Mentolatux, Offroad, Simulador, Caminhão, Unity, WebGL',
  'https://img.gamemonetize.com/a6i1ot5d0scwphehyrsl0vned0ezjk8q/512x384.jpg',
  800,
  600,
  3
),
(
  '34205',
  'Zumbis vs. Girassóis',
  'Neste jogo de tower defense cheio de ação, seu jardim está sob cerco de zumbis implacáveis! Posicione estrategicamente plantas únicas - cada uma com habilidades especiais - para parar os invasores cambaleantes. Desbloqueie e Melhore - Fortaleça suas plantas para liberar ataques poderosos e criar uma defesa imbatível.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/6kw2gj2vjs2uztzkl5xyrxrpreo5t6lo/',
  'Hypercasual',
  'Plantas Irritadas, Apocalipse, Exército, Batalha, Casual, Defesa, Fruta, Frutas, Hypercasual, Planta, Plantas, Tower Defense, Zumbi',
  'https://img.gamemonetize.com/6kw2gj2vjs2uztzkl5xyrxrpreo5t6lo/512x384.jpg',
  800,
  600,
  3
),
(
  '34204',
  'Bestas Doces',
  'Combine doces. Alimente monstros. Libere o caos do açúcar! Entre no mundo selvagem e caprichoso de Bestas Doces, uma aventura de quebra-cabeça match-3 repleta de doces onde monstros adoráveis têm um apetite insaciável por doces! Combine doces coloridos, acione combos explosivos e alimente seus amigos bestas famintos.',
  'Match-3 e vença',
  'https://html5.gamemonetize.com/h9oc4gnpqgqndct23kpvys6qlgzlo7v4/',
  'Hypercasual',
  'Melhores Jogos, Match-3, Quebra-cabeça',
  'https://img.gamemonetize.com/h9oc4gnpqgqndct23kpvys6qlgzlo7v4/512x384.jpg',
  800,
  600,
  3
),
(
  '34202',
  'Fuga do Parquinho Thung Thung Sahur',
  'Fuga do Parquinho Thung Thung Sahur é um survival horror. Você deve encontrar uma maneira de completar a missão dentro de um tempo determinado antes que Thung Thung te pegue!',
  'WASD para mover',
  'https://html5.gamemonetize.com/8tcibyn2omj8rnb6w52fca37crhmexjh/',
  'Adventure',
  'Horror, Tung Tung Tung, Tung Tung Tung Sahur',
  'https://img.gamemonetize.com/8tcibyn2omj8rnb6w52fca37crhmexjh/512x384.jpg',
  800,
  600,
  3
),
(
  '34200',
  'Chuva de Slime',
  'Desvie dos objetos que caem e colete o máximo de moedas que puder! Jogo de arcade baseado em reflexos, acelerado, fácil de jogar, mas difícil de dominar. Por quanto tempo você consegue sobreviver?',
  'Teclado ou deslizar ou tocar',
  'https://html5.gamemonetize.com/d0h77hx3taikfukdn3jqgjvh2hz333y3/',
  'Hypercasual',
  '2D, Arcade, Evitar, Coleção, Infinito',
  'https://img.gamemonetize.com/d0h77hx3taikfukdn3jqgjvh2hz333y3/512x384.jpg',
  720,
  1280,
  3
),
(
  '34198',
  'Arrastar e Explodir',
  'DragnBoom é um jogo de arcade divertido da velha escola combinando velocidade e precisão! Mergulhe em um universo medieval imaginário cheio de heróis, ecoando os maiores jogos de arcade e plataforma de todos os tempos.',
  'Use o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/avdfpa7rynma1wxofv7mfg6iyh8trf07/',
  'Adventure',
  '1 Jogador, Ação, Aventura, Arcade, Cartoon Network, Correr, Dragão, Mario, Correr, Habilidades',
  'https://img.gamemonetize.com/avdfpa7rynma1wxofv7mfg6iyh8trf07/512x384.jpg',
  800,
  480,
  3
),
(
  '34197',
  'Quebra-Cabeça de Desafio de Links',
  'Una os quadrados correspondentes. O jogo tem vários tipos de blocos, cada um dos quais tem uma linha de conexão, e blocos com a mesma linha de conexão podem ser conectados. O jogo tem tema espacial, a tela é muito bonita, venha experimentar.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/w9ivj4zh3jsdgv228mo6arl3scwflrpc/',
  'Puzzles',
  '1 Jogador, Arcade, Quebra-cabeça',
  'https://img.gamemonetize.com/w9ivj4zh3jsdgv228mo6arl3scwflrpc/512x384.jpg',
  350,
  600,
  3
),
(
  '34196',
  'Barragem Heroica',
  'Libere balas. Desvie do caos. Defenda o reino. Em Barragem Heroica, você é a última linha de defesa - um guerreiro destemido armado com poder de fogo infinito, enfrentando onda após onda de inimigos implacáveis. Situado em um campo de batalha de rolagem lateral acelerado logo acima do nível do solo.',
  'Desvie de inimigos e atire',
  'https://html5.gamemonetize.com/xh68e468i0y8trlyucd55tbhdh526foh/',
  'Hypercasual',
  'Inimigos, Voar, Correr, Super-herói',
  'https://img.gamemonetize.com/xh68e468i0y8trlyucd55tbhdh526foh/512x384.jpg',
  800,
  600,
  3
),
(
  '34195',
  'Fuga das Cobras',
  'Fuga das Cobras é um jogo de sobrevivência arcade acelerado onde o perigo desliza de todas as direções! Desvie de uma onda infinita de cobras e tente sobreviver o máximo possível. Simples de jogar, mas difícil de dominar - perfeito para jogadores casuais e competitivos.',
  'Teclado ou toque ou mouse',
  'https://html5.gamemonetize.com/l078xbrwau481peyccnpdwkcdsg5g0ke/',
  'Hypercasual',
  'Casual, Mobile, Cobra, Sobrevivência',
  'https://img.gamemonetize.com/l078xbrwau481peyccnpdwkcdsg5g0ke/512x384.jpg',
  720,
  1280,
  3
),
(
  '34194',
  'Bolas Saltitantes',
  'Se você está procurando o campeão dos mata-tempo, não perca este jogo Html 5 Bolas Saltitantes. Parece um jogo muito simples de quebrar tijolos, mas mais viciante! É um jogo simples e minimalista para jogar porque não há necessidade de pegá-los. Apenas use seu dedo para tocar para mirar e atirar a bola.',
  'Deslize seu dedo para jogar as bolas e quebrar os tijolos. Cada tijolo tem números, acerte os tijolos tantas vezes quanto os números nele para fazer aquele tijolo desaparecer. Tente quebrar o máximo de tijolos possível antes que se movam para baixo',
  'https://html5.gamemonetize.com/t6jirs5vm2z0c3xa60ld40xh8u34v13a/',
  'Puzzles',
  'Bola, Cérebro, Número, Quebra-cabeça, Habilidades, Estratégia',
  'https://img.gamemonetize.com/t6jirs5vm2z0c3xa60ld40xh8u34v13a/512x384.jpg',
  800,
  600,
  3
),
(
  '34193',
  'Labubu e Amigos 2 Jogadores',
  'Labubu e seu amigo precisam escapar da ilha durante o verão! Seja muito cuidadoso enquanto vocês aventuram juntos e coletam todas as conchas douradas pelo caminho. Claro, colete essas conchas douradas primeiro - então chegue à caixa de presente gigante! Ambos os adoráveis amigos Labubu devem chegar à caixa de presente.',
  'Use WASD e setas do teclado para mover. Colete todas as Conchas Douradas e chegue à Caixa de Presente. Jogável tanto no mobile quanto no PC',
  'https://html5.gamemonetize.com/lv9gv1e4b0nnycb2h3v6chrzmsiwp1zr/',
  'Arcade',
  '1 Jogador, 2 Jogadores, Jogos 2 Jogadores, 2D, Ação, Aventura, Arcade, Plataforma',
  'https://img.gamemonetize.com/lv9gv1e4b0nnycb2h3v6chrzmsiwp1zr/512x384.jpg',
  800,
  600,
  3
),
(
  '34192',
  'Motorista de Caminhão de Carga Real 2025',
  'Motorista de Caminhão de Carga Real 2025 é um jogo de simulação de caminhão imersivo onde os jogadores transportam carga pesada através de estradas desafiadoras. Experimente física de direção realista, clima dinâmico e ambientes detalhados enquanto gerencia entregas, melhora seus caminhões e explora rotas expansivas de mundo aberto.',
  'WASD para dirigir',
  'https://html5.gamemonetize.com/l1d2e2zfagy73bk0trm842vg06hfmagh/',
  'Action',
  'Carga, Direção, Mentolatux, Caminhão, Unity, WebGL',
  'https://img.gamemonetize.com/l1d2e2zfagy73bk0trm842vg06hfmagh/512x384.jpg',
  800,
  600,
  3
),
(
  '34188',
  'Festa do Pijama das Meninas',
  'Ei meninas! Preparem-se para hospedar a festa do pijama mais incrível de todas com Festa do Pijama das Meninas, um jogo de simulação casual super divertido que também é educativo! O jogo começa com fazer seus convites. Você vai desenhar cartões fofos usando uma variedade de acessórios para convidar suas melhores amigas para a festa.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/kjjfnkvvc17kylsnhoa23q248ihugrro/',
  'Hypercasual',
  'Incrível, Educativo, Diversão',
  'https://img.gamemonetize.com/kjjfnkvvc17kylsnhoa23q248ihugrro/512x384.jpg',
  1280,
  720,
  3
),
(
  '34187',
  'Ceifador Corta Grama',
  'Ei fazendeiro, é hora de dirigir seu ceifador! Entre no volante e colete todo o trigo. A temporada de colheita chegou. O trigo está maduro e pronto para ser colhido. Ligue seu trator e are o campo. O tempo está acabando - você deve terminar de colher todo o campo antes que o tempo acabe!',
  'Use as setas do teclado para mover esquerda, direita, cima e baixo. Jogável tanto no mobile quanto no PC. Controles de toque móvel disponíveis',
  'https://html5.gamemonetize.com/cqtzwbhonl1obzxshoppcaq0mek8g2qj/',
  'Hypercasual',
  '1 Jogador, 2D, Fazenda, Jogos, HTML5, Trator',
  'https://img.gamemonetize.com/cqtzwbhonl1obzxshoppcaq0mek8g2qj/512x384.jpg',
  800,
  600,
  3
),
(
  '34186',
  'Matador de Gigantes',
  'Melhore seus heróis, batalhe inimigos temíveis e aperfeiçoe suas habilidades estratégicas nesta aventura de fantasia infinitamente rejogável. Domine seu esquivar, defesa e ataque para conquistar cada nível e se tornar o herói definitivo!',
  'Clique ou toque',
  'https://html5.gamemonetize.com/5923r5x0fasynzvmt4m12j2ctknjrtvv/',
  'Adventure',
  'Ataque, Fantasia, Baseado em Turnos',
  'https://img.gamemonetize.com/5923r5x0fasynzvmt4m12j2ctknjrtvv/512x384.jpg',
  854,
  480,
  3
),
(
  '34185',
  'Corredor Vermelho',
  'Embarque em uma aventura emocionante de rolagem lateral 2D! Corra, pule e role pelo caminho através de níveis desafiadores cheios de armadilhas, inimigos e segredos. Use timing preciso e reflexos rápidos para sobreviver e chegar à linha de chegada. Com controles suaves e ação acelerada, este jogo de plataforma testará suas habilidades.',
  'Controles: W - Pular, A D - Mover Esquerda Direita, S - Rolar ou Esquivar. Domine esses movimentos para superar obstáculos e chegar ao objetivo',
  'https://html5.gamemonetize.com/ja7cy5j8u20ajm7jkzammyjwo0jo8fe3/',
  'Adventure',
  '2D, Aventura, Plataforma',
  'https://img.gamemonetize.com/ja7cy5j8u20ajm7jkzammyjwo0jo8fe3/512x384.jpg',
  800,
  600,
  3
),
(
  '34184',
  'Corrida de Mini Supercarros Batendo',
  'Corrida de Mini Supercarros Batendo é diversão caótica pura! Corra supercarros pequenos mas poderosos em pistas selvagens cheias de saltos, obstáculos e explosões. Bata em rivais, derrape em curvas apertadas e cause acidentes épicos enquanto luta pela vitória. Rápido, furioso e cheio de caos - esta é loucura de corrida mini!',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/4htdhun5663v914ifk7o2kdfwtc3nfs8/',
  'Action',
  'Carros, Acidente, Demolição, Direção, Mentolatux, Corrida, Supercarros, Unity, Veículo, WebGL',
  'https://img.gamemonetize.com/4htdhun5663v914ifk7o2kdfwtc3nfs8/512x384.jpg',
  800,
  600,
  3
),
(
  '34183',
  'Matemática Louca',
  'Descubra rapidamente a resposta certa. O jogo aparecerá rapidamente um problema de cálculo simples, você precisa calcular a resposta correta, cada resposta correta seu personagem disparará uma bala para matar o inseto na sua frente, mate um inseto para ganhar um ponto, venha experimentar para ver quantos pontos você pode conseguir.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/85hu8a9g2ve9wi36y5k9byzdrd30tcux/',
  'Shooting',
  'Arcade, Matemática, Atirar',
  'https://img.gamemonetize.com/85hu8a9g2ve9wi36y5k9byzdrd30tcux/512x384.jpg',
  350,
  600,
  3
),
(
  '34179',
  'Cavaleiro de Galinha Atirando Tung Tung Sahur',
  'Entre no mundo selvagem, maluco e pixelado de Cavaleiro de Galinha Atirando Tung Tung Sahur - um atirador de ação acelerado onde o mais improvável dos heróis enfrenta o submundo do crime de uma Las Vegas estilo Minecraft. Você é o Cavaleiro de Galinha, um zumbi bebê lendário montado em uma galinha destemida, armado com coragem, determinação e um blaster confiável.',
  'Apenas mouse',
  'https://html5.gamemonetize.com/5jekjsbk5wqleu5n4k5sqxibpycywcth/',
  'Shooting',
  '1 Jogador, 8 Ball Pool, Ação, Ar, Avião, Apocalipse, Arena, Mineblock, Minecraft',
  'https://img.gamemonetize.com/5jekjsbk5wqleu5n4k5sqxibpycywcth/512x384.jpg',
  800,
  600,
  3
),
(
  '34178',
  'Luta de Robôs Definitiva',
  'Entre no confronto definitivo em Luta de Robôs Definitiva. Você estará controlando seu robô em batalha. Continue atirando em inimigos e tente sobreviver. Jogue como um guerreiro mecânico destemido e lute contra inimigos. Colete várias armas para aumentar sua contagem de balas. O jogo é projetado para meninos e é simples, mas desafiador!',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/xo851pwg3e5nh7act1wsy486mjyb8w6u/',
  'Arcade',
  'Luta, Robô, Sobrevivência',
  'https://img.gamemonetize.com/xo851pwg3e5nh7act1wsy486mjyb8w6u/512x384.jpg',
  1334,
  750,
  3
),
(
  '34177',
  'Simulador de Construção Lite',
  'Bem-vindo ao Simulador de Construção Lite, o jogo de simulação de construção casual projetado para todo menino que sonha em operar máquinas pesadas! Assuma o controle de escavadeiras poderosas, carros, guindastes e mais! Operação precisa do braço robótico. Complete uma série de tarefas de construção como cavar, manusear e preencher a fundação.',
  'Clique do mouse ou toque para jogar',
  'https://html5.gamemonetize.com/iifqhn3k4bln57rcd9w1saylv5y6bine/',
  'Hypercasual',
  'Carro, Simulador, Caminhão',
  'https://img.gamemonetize.com/iifqhn3k4bln57rcd9w1saylv5y6bine/512x384.jpg',
  1630,
  750,
  3
); 