-- Migration 023: Adicionar jogos de culinária na página 4
-- Criado: 2024
-- Descrição: Adiciona 32 jogos de culinária traduzidos para português na página 4

INSERT INTO games (
  id, title, description, instructions, url, category, tags, thumb, width, height, views, likes, page
) VALUES 
(
  'cozinhe-em-3d',
  'Cozinhe em 3D',
  'Mergulhe no mundo colorido e emocionante do match-3! Colete ingredientes suculentos em um prato para cozinhar receitas únicas e surpreender todos com obras-primas deliciosas. Descubra novos ingredientes, descubra receitas ainda mais deliciosas e torne-se um mestre das aventuras culinárias! Pronto para um desafio divertido e delicioso? Então comece agora mesmo!',
  'Combine 3 ingredientes necessários no prato com o mouse ou dedo para obter pontos. Não adicione mais de 3 produtos ao prato',
  'https://html5.gamemonetize.com/w4h80fkwq0ipv6u699rm3mwr6wcfjpqx/',
  'Culinária',
  '3D, Culinária, Comida, Simulador',
  'https://img.gamemonetize.com/w4h80fkwq0ipv6u699rm3mwr6wcfjpqx/512x384.jpg',
  960,
  600,
  0,
  0,
  4
),
(
  'corrida-do-rei-da-cozinha',
  'Corrida do Rei da Cozinha',
  'Corrida do Rei da Cozinha é um jogo de restaurante em ritmo acelerado onde clientes famintos chegam, e cabe a você servi-los refeições deliciosas no tempo certo! Cozinhe, emprate e entregue uma variedade de pratos de dar água na boca enquanto gerencia o caos da cozinha. Mantenha seus clientes felizes, ganhe grandes gorjetas e melhore seu restaurante para se tornar o Rei da Cozinha definitivo!',
  'Sirva comida o mais rápido possível',
  'https://html5.gamemonetize.com/irtmhn74jcqsejzgvkh802bkc55u0p7d/',
  'Culinária',
  'Melhor, Clicker',
  'https://img.gamemonetize.com/irtmhn74jcqsejzgvkh802bkc55u0p7d/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'taylor-cozinha-acao-gracas',
  'Taylor Cozinha Ação de Graças',
  'Este é um jogo de culinária online para o Dia de Ação de Graças. Você terá a oportunidade de entrar na casa da Taylor para ajudá-los a se preparar para o Dia de Ação de Graças. Primeiro você precisará ir ao supermercado e fazer compras de ingredientes e itens para preparar as decorações. Quando chegar em casa, você precisará fazer o peru primeiro, dos ingredientes ao cozimento.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/435zfhv6y544y6tyc75qobkf9w5nabqb/',
  'Culinária',
  'Comida, Compras, Super',
  'https://img.gamemonetize.com/435zfhv6y544y6tyc75qobkf9w5nabqb/512x384.jpg',
  720,
  1280,
  0,
  0,
  4
),
(
  'historia-restaurante-idle',
  'História do Restaurante Idle',
  'Este é um jogo de simulação de gerenciamento de restaurante, comece como um bar de comida de rua, contrate novos funcionários e melhore máquinas para ganhar mais dinheiro, depois abra um restaurante maior! Características: - Simples e fácil de começar - Melhore estrategicamente seus restaurantes para maximizar a receita - Vários restaurantes e comidas esperando para você desbloquear. Há 11 cidades e mais de 100 níveis diferentes.',
  'O controle do jogo é muito simples, apenas toque nas máquinas e comidas para completar os níveis do jogo',
  'https://html5.gamemonetize.com/r8zdmvt4yo1vjaet9i2cjattvq3vh40j/',
  'Culinária',
  'Casual, Culinária, Legal, Comida, Apontar e Clicar, Restaurante',
  'https://img.gamemonetize.com/r8zdmvt4yo1vjaet9i2cjattvq3vh40j/512x384.jpg',
  640,
  480,
  0,
  0,
  4
),
(
  'cookie-clicker-online',
  'Cookie Clicker Online',
  'Jogue Cookie Clicker Online gratuitamente, é um jogo incrivelmente divertido onde seu objetivo é assar o maior número de cookies possível. Você começa clicando para produzir cookies, e então pode desbloquear melhorias e conquistas emocionantes para aumentar sua velocidade de cozimento! Se você gosta de jogos que mantêm você engajado e querendo voltar para mais, Cookie Clicker é uma excelente escolha para você.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/z5n072q7gj0w969r5ul4ignnxe0fzsun/',
  'Culinária',
  'Clique, Clicker, Apontar e Clicar',
  'https://img.gamemonetize.com/z5n072q7gj0w969r5ul4ignnxe0fzsun/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'dentista-maluco-wojak',
  'O Dentista Maluco Wojak',
  'Junte-se ao Dr. Wojak, o dentista amigável e conhecedor, em uma aventura 2D emocionante criada especialmente para crianças! Em Aventura Dental com Dr. Wojak, jovens jogadores mergulharão em um mundo colorido onde aprender sobre higiene dental é divertido e envolvente. Características: Jogabilidade Envolvente: Ajude o Dr. Wojak em vários mini-jogos que envolvem limpar, escovar e cuidar dos dentes dos pacientes.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/y8iedym7u25m04ns5xdabpzxnp1pyr7h/',
  'Culinária',
  'Jogos .io, Jogos 2 Jogadores, Aventura, Arcade, Baby Hazel, Bejeweled, Craft, Escondido',
  'https://img.gamemonetize.com/y8iedym7u25m04ns5xdabpzxnp1pyr7h/512x384.jpg',
  1270,
  650,
  0,
  0,
  4
),
(
  'taylor-volta-escola',
  'Taylor Volta para a Escola',
  'Taylor Volta para a Escola é um jogo educativo. As longas férias estão chegando ao fim. Hoje Taylor vai arrumar suas coisas da escola. Vamos ajudar Taylor a arrumar suas coisas! Taylor ainda está dormindo, acorde-a rapidamente e ajude-a a escovar os dentes e lavar o rosto. A coisa mais importante para a escola é a mochila escolar. Ajude-a a organizar os livros e lápis que ela precisa levar para a escola.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/ma46cka3c27lucz8bzfp99samggqeo9p/',
  'Culinária',
  'Educativo',
  'https://img.gamemonetize.com/ma46cka3c27lucz8bzfp99samggqeo9p/512x384.jpg',
  1280,
  720,
  0,
  0,
  4
),
(
  'mundo-alice-nomes-vegetais',
  'Mundo de Alice - Nomes dos Vegetais',
  'Mundo de Alice - Nomes dos Vegetais é um jogo educativo desenvolvido para crianças onde elas aprenderão os nomes dos vegetais de forma divertida e interativa através do celular, tablet ou computador. Excelente recurso educativo. No Mundo de Alice, aprender é divertido.',
  'Arraste o vegetal solicitado pela Alice para a cesta',
  'https://html5.gamemonetize.com/590dmy86oek5nuvhljntj3hj9yytst25/',
  'Culinária',
  'Melhores Jogos, Educativo, Comida, jogos grátis para seu site, jogos grátis para seu website, jogos html5 grátis para seu website, jogos html para seu website, HTML5, jogos html5, jogos html5 para seu site, Crianças, Letras, Escola, Mundo de Alice',
  'https://img.gamemonetize.com/590dmy86oek5nuvhljntj3hj9yytst25/512x384.jpg',
  800,
  450,
  0,
  0,
  4
),
(
  'mania-grandes-donuts',
  'Mania dos Grandes Donuts',
  'Se você fez uma combinação, os donuts serão limpos e você ganhará os pontos! Quanto mais você conseguir, melhor será sua classificação na pontuação alta. Aviso: Mania dos Grandes Donuts é viciante como uma caixa de donuts!',
  'Alinhe-os',
  'https://html5.gamemonetize.com/vzk4zr4ad5elwwx1d5c9vm0b4osmotb4/',
  'Culinária',
  'Melhores Jogos, Match-3',
  'https://img.gamemonetize.com/vzk4zr4ad5elwwx1d5c9vm0b4osmotb4/512x384.jpg',
  1080,
  1920,
  0,
  0,
  4
),
(
  'magnata-restaurante-idle',
  'Magnata do Restaurante Idle',
  'Você quer ser um gerente de restaurante único? Você pode aprender como ser um gerente com o jogo Idle Restaurant. Você pode precisar de alguns especialistas para cozinhar e servir. Contrate um chef mestre, desenvolva sua equipe, gerencie suas finanças e torne-se o chefe perfeito. Além disso, não se esqueça de verificar seu mercado para presentes surpresa.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/znokgo6d1qsz3pwqoy5t43wf95aque88/',
  'Culinária',
  'Cozinhar, Culinária, comendo, Engraçado, Quente, Interativo, Crianças, Mobile, Estratégia',
  'https://img.gamemonetize.com/znokgo6d1qsz3pwqoy5t43wf95aque88/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'bartender-rapido',
  'Bartender Rápido',
  'Entre no mundo acelerado de um mixologista mestre em Bartender Rápido, um emocionante jogo de arcade onde matar a sede encontra ação que bombeia adrenalina! Clientes sedentos fazem fila no bar, seus olhos implorando por um gostinho da sua arte líquida. Você será o herói que entrega o despejo perfeito, ou a frustração borbulhará com bebidas derramadas e suspiros desapontados?',
  'Mobile Touch PC Mouse',
  'https://html5.gamemonetize.com/tevy36r7qnipasd04yrutfp3jaikpo1v/',
  'Culinária',
  '1 Jogador, Adulto, Culinária, Hypercasual',
  'https://img.gamemonetize.com/tevy36r7qnipasd04yrutfp3jaikpo1v/512x384.jpg',
  1080,
  1920,
  0,
  0,
  4
),
(
  'loja-chefs-padaria',
  'Loja dos Chefs da Padaria',
  'Loja dos Chefs da Padaria é um delicioso e divertido jogo de aventura culinária para meninas e crianças. Você é um cozinheiro talentoso que tem muitos clientes fiéis em sua padaria de desenho animado 2D. Você pode fazer pedidos e aprender como assar um bolo em 60 níveis. Você também pode decorar seus bolos com itens extras que pode desbloquear com moedas de ouro.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/9cn5c1omowu3y2t8qn65vuwhci3srppz/',
  'Culinária',
  '2D, Cozinhar, Culinária, Design, Comida',
  'https://img.gamemonetize.com/9cn5c1omowu3y2t8qn65vuwhci3srppz/512x384.jpg',
  1334,
  750,
  0,
  0,
  4
),
(
  'fabricante-algodao-doce',
  'Fabricante de Algodão Doce Doce',
  'Azul, rosa, amarelo, branco, uau! Marshmallows têm muitas cores e sabores incríveis. Você pode criar seus próprios marshmallows a qualquer hora. Em fabricantes de algodão doce, pegue seu doce e adicione seu sabor favorito para fazer sobremesas gostosas. A máquina está quente e esperando por você! Esta sobremesa é fácil de fazer, e você será um profissional em breve.',
  'Toque para jogar',
  'https://html5.gamemonetize.com/duay2vzk328wwhrufwowb0gy5nlqvql2/',
  'Culinária',
  '2D, Desenho Animado, Casual, Comida, Meninas, Crianças, Simulação',
  'https://img.gamemonetize.com/duay2vzk328wwhrufwowb0gy5nlqvql2/512x384.jpg',
  750,
  1334,
  0,
  0,
  4
),
(
  'bartender-mistura-certa',
  'Bartender: A Mistura Certa',
  'Ajude Miguel, o bartender, a misturar coquetéis para si mesmo nas proporções certas! Escolha de uma prateleira cheia de diferentes bebidas e misture-as para fazer o coquetel definitivo para uma boa noite. Adicione gelo ou limão para dar aquele chute extra, mas tenha cuidado, misturar nas quantidades erradas ou simplesmente misturar as bebidas erradas pode acabar da pior forma! Não é necessária escola de bartender!',
  '- Clique para escolher itens - Clique e segure para despejar e agitar',
  'https://html5.gamemonetize.com/a3kq2m27xqrt0vfitkakrwu36oi1ylbp/',
  'Culinária',
  '1 Jogador, Adulto, Culinária',
  'https://img.gamemonetize.com/a3kq2m27xqrt0vfitkakrwu36oi1ylbp/512x384.jpg',
  900,
  660,
  0,
  0,
  4
),
(
  'magnata-pizzaria-cafe',
  'Magnata da Pizzaria Café',
  'Você está pronto para construir um império de café bem-sucedido com você? Atualmente você possui uma pizzaria e os clientes adoram sua pizza deliciosa. Sua tarefa é entregar vários pedidos de pizza no prazo e rapidamente. Lembre-se, velocidade e qualidade são tudo no negócio de café. Você tem que trabalhar com dedicação para garantir a satisfação de seus clientes.',
  'Como jogar Desktop Mouse Mobile Touch control',
  'https://html5.gamemonetize.com/ozrihsbvi9tirbdb9cnyu7rks1ydj8hc/',
  'Culinária',
  'Cozinhar, Culinária, Jogo, Restaurante, Simulação, Luta de Rua, Timing',
  'https://img.gamemonetize.com/ozrihsbvi9tirbdb9cnyu7rks1ydj8hc/512x384.jpg',
  1080,
  1920,
  0,
  0,
  4
),
(
  'culinaria-tendencia',
  'Culinária Tendência',
  'Você quer que sua comida traga alegria para todos? Não há nada melhor do que cozinhar em seu próprio restaurante. Deixe Culinária Tendência realizar seus sonhos! Ao jogar Culinária Tendência, você se transformará em um chef famoso, criando pratos deliciosos para satisfazer os comensais todos os dias. Não apenas isso, você receberá recompensas atrativas após completar cada missão e usá-las para melhorar itens, construir seu próprio restaurante.',
  '1 Delicie clientes com refeições bem preparadas 2 Melhore seu restaurante e utensílios de cozinha com o ouro que você ganha após cada nível 3 Desbloqueie mais ingredientes deliciosos e condimentos 4 Jogos de culinária ensinam como fazer negócios e serviço de qualidade',
  'https://html5.gamemonetize.com/docrms4jca8iu8kndsglrihp3ihf3xh8/',
  'Culinária',
  'Culinária, Comida, Restaurante',
  'https://img.gamemonetize.com/docrms4jca8iu8kndsglrihp3ihf3xh8/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'tmnt-hora-pizza',
  'TMNT: Hora da Pizza',
  'No jogo Hora da Pizza, Michelangelo precisa da sua ajuda para fazer pizzas deliciosas na pizzaria do Antonio. Você tem um tempo limitado para preparar todos os pedidos, então coloque seu avental e prepare-se para fatiar e cozinhar quantas pizzas puder!',
  'É hora de aprender como as coisas funcionam na cozinha e você deve começar aprendendo os controles primeiro. Muitos ingredientes voarão pelo lugar e você deve segurar o Clique Esquerdo e mover o mouse para cortá-los todos. Não se preocupe se perder alguns',
  'https://html5.gamemonetize.com/hynoxd8wkdy2e05sld8xmrslb5vmppax/',
  'Culinária',
  'Arcade, Melhor, Cozinhar, Culinária, H5, Quente, HTML5, Novo, Ninja, Ninjago',
  'https://img.gamemonetize.com/hynoxd8wkdy2e05sld8xmrslb5vmppax/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'empilhador-sanduiche-625',
  'Empilhador de Sanduíche 625',
  'Empilhe os maiores sanduíches possíveis pegando ingredientes, mas não pegue nada nojento! Este jogo não contém links externos.',
  'Desktop Use as setas do teclado para mover um personagem Mobile Toque e segure na parte direita ou esquerda da tela',
  'https://html5.gamemonetize.com/fi9tq41y1fdxjic2q0aerphxg4af4k7e/',
  'Culinária',
  'Desenho Animado, Cozinhar, HTML5, Crianças, Mobile, Habilidades',
  'https://img.gamemonetize.com/fi9tq41y1fdxjic2q0aerphxg4af4k7e/512x384.jpg',
  1160,
  640,
  0,
  0,
  4
),
(
  'fabricante-sorvete',
  'Meu Fabricante de Sorvete',
  'A loja Fabricante de Sorvete está agora aberta para servir deliciosos cones de sorvete e combiná-los com um cupcake congelado. Em seguida, sirva esta deliciosa sobremesa gelada para seus clientes felizes neste jogo de sorvete. Fabricante de Sorvete - vai liberar sua criatividade! Se você sabe a resposta para a pergunta – Como você faz sorvete? – este "jogo viciante" é a melhor opção para você!',
  'A loja Fabricante de Sorvete está agora aberta para servir deliciosos cones de sorvete e combiná-los com um cupcake congelado. Em seguida, sirva esta deliciosa sobremesa gelada para seus clientes felizes neste jogo de sorvete.',
  'https://html5.gamemonetize.com/9p08cplp68sc1lcw9cxqvxltfrplvd1n/',
  'Culinária',
  'Arcade, Casual, Cozinhar, Culinária, Comida, Meninas, Gelo, Máquina',
  'https://img.gamemonetize.com/9p08cplp68sc1lcw9cxqvxltfrplvd1n/512x384.jpg',
  600,
  960,
  0,
  0,
  4
),
(
  'local-culinaria',
  'Local de Culinária',
  'Você no jogo Local de Culinária ajudará o chef a servir os clientes. Na sua frente na tela será visível a prateleira atrás da qual seu herói estará. Clientes virão até ela e farão pedidos. Eles serão exibidos ao lado dos clientes como fotos. Você terá que estudá-lo cuidadosamente e então começar a cozinhar. Certos alimentos estarão à sua disposição.',
  'Use o mouse ou toque na tela',
  'https://html5.gamemonetize.com/g905frowfw4cqcg481urvf0inkl4npj7/',
  'Culinária',
  'Melhor, Meninos, Hambúrguer, Comida, Diversão, Engraçado, Meninas, HTML5, Crianças, Mobile, Restaurante, Habilidade',
  'https://img.gamemonetize.com/g905frowfw4cqcg481urvf0inkl4npj7/512x384.jpg',
  1280,
  720,
  0,
  0,
  4
),
(
  'fabricante-bolo-cenoura',
  'Fabricante de Bolo: Bolo de Cenoura',
  'Com fome? Comece a assar! Torne-se o melhor padeiro de bolos da cidade e crie os bolos mais gostosos, neste delicioso jogo de culinária! A bela arte 3D deste jogo de culinária fará você se sentir como se estivesse assando um bolo de verdade! Gostoso! O que você está esperando? Tire sua batedeira e comece a quebrar esses ovos! Seja o melhor padeiro de bolos que o mundo já viu!',
  'Comece a assar',
  'https://html5.gamemonetize.com/ihopepb3fmu9r38lu31wkvssw6qkd1ol/',
  'Culinária',
  'Cozinhar, Culinária',
  'https://img.gamemonetize.com/ihopepb3fmu9r38lu31wkvssw6qkd1ol/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'restaurante-circo',
  'Restaurante do Circo',
  'Você é um amante de comida? Torne-se um Masterchef do seu restaurante, construa um império de restaurantes em diferentes países, ganhe dinheiro com suas comidas e acelere seu desenvolvimento investindo em seu negócio. Neste jogo de simulação idle tycoon, desbloqueie seus produtos, melhore suas receitas, decore seu restaurante e recrute novos chefs e garçons para administrar seu restaurante lucrativo.',
  'Toque para jogar',
  'https://html5.gamemonetize.com/531f01wlxovdz5ukpjhf17nv70qp3x8b/',
  'Culinária',
  'Cozinhar, Culinária, Restaurante',
  'https://img.gamemonetize.com/531f01wlxovdz5ukpjhf17nv70qp3x8b/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'assando-com-papai-noel',
  'Assando com Papai Noel',
  'Experimente as melhores receitas de biscoitos do mundo para você neste jogo de culinária de cozinha. Ei, pequenos chefs jovens, é hora de surpreender sua família com biscoitos de Natal perfeitos. Torne suas férias de Natal especiais jogando o novo jogo especial da temporada de férias do estúdio de jogos junior Receitas de Biscoitos de Natal - Culinária Doce de Férias.',
  'Toque para jogar',
  'https://html5.gamemonetize.com/mehazxjfszsf9rdan7z0gf2niqsv9gw5/',
  'Culinária',
  'Cozinhar, Culinária, Sandbox',
  'https://img.gamemonetize.com/mehazxjfszsf9rdan7z0gf2niqsv9gw5/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'lancheira',
  'Lancheira',
  'Pronto para se tornar o melhor organizador que já existiu. Encha a geladeira, prepare um café da manhã saboroso e até faça uma refeição feliz com este jogo de simulação satisfatório. Lancheira Pronta é um jogo de empacotamento ASMR que permite que você projete seu sanduíche, organize lanches e até corte comida. Se você gosta de organizar geladeira e encher a geladeira, isso está levando suas habilidades de empacotamento para o próximo nível.',
  'Toque para jogar',
  'https://html5.gamemonetize.com/e78eiyuve1l8mwcxs26o7wg7bekwtx28/',
  'Culinária',
  'Cozinhar, Culinária',
  'https://img.gamemonetize.com/e78eiyuve1l8mwcxs26o7wg7bekwtx28/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'sorvete-por-favor',
  'SORVETE, POR FAVOR!',
  'Em Sorvete, Por Favor!, você assume o papel de um pequeno proprietário de sorveteria neste divertido e envolvente jogo de simulação de restaurante. Sua tarefa é misturar e combinar sabores, coberturas, frutas e nozes para criar os pedidos de sorvete perfeitos para seus clientes. Use seu dedo, mouse ou teclado para selecionar os ingredientes e preparar o sorvete conforme a solicitação do seu cliente.',
  'Toque nos cones, tipos de sorvete ou coberturas para selecioná-los e usá-los',
  'https://html5.gamemonetize.com/16x1z2l7e58u93hhmk8dja23sbhbceh6/',
  'Culinária',
  'Meninos, Culinária, Comida, Meninas, Restaurante, Simulação',
  'https://img.gamemonetize.com/16x1z2l7e58u93hhmk8dja23sbhbceh6/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'desafio-culinaria',
  'Desafio de Culinária',
  'Um cliente faminto é um cliente impaciente. Que precisa ser servido o mais rápido possível. Isso é exatamente o que acontecerá no jogo Desafio de Culinária. Seu restaurante está aberto. Rapidamente coloque hambúrgueres na panela, jogue batatas fritas no óleo fervente e ligue o dispensador de bebidas. Tudo isso será necessário em breve e deixe os pratos ficarem prontos com antecedência para que clientes famintos não esperem e não fiquem nervosos.',
  'Use o mouse ou toque na tela',
  'https://html5.gamemonetize.com/ygyegpn6a3817y9yt3vl9ifec6qc50jk/',
  'Culinária',
  'Hambúrguer, Casual, Comida, Diversão, Engraçado, Meninas, HTML5, Hypercasual, Crianças, Mobile, Restaurante, Habilidade, Estratégia',
  'https://img.gamemonetize.com/ygyegpn6a3817y9yt3vl9ifec6qc50jk/512x384.jpg',
  1920,
  1080,
  0,
  0,
  4
),
(
  'culinaria-marina-2023',
  'Culinária Marina 2023',
  'Bem-vindo ao Culinária Marina - novos jogos de restaurante de culinária 2021. Como você sabe, Singapura é bem conhecida como uma das cidades mais bonitas e frescas do mundo e especialmente Singapura também é famosa por um paraíso culinário diversificado. Este jogo de culinária de restaurante rápido levará você a viajar por Singapura e alguns países da Ásia para experimentar pratos saborosos com receitas culinárias únicas.',
  'Toque para jogar',
  'https://html5.gamemonetize.com/ezm7nl5go8l2d6t0s3xql9evvt5qsu9c/',
  'Culinária',
  'Arcade, Melhor, Cérebro, Hambúrguer, Culinária, Meninas, Crianças',
  'https://img.gamemonetize.com/ezm7nl5go8l2d6t0s3xql9evvt5qsu9c/512x384.jpg',
  600,
  960,
  0,
  0,
  4
),
(
  'fabricante-pizza-engracado',
  'Fabricante de Pizza Engraçado',
  'Fabricante de Pizza: Meu Jogo de Pizzaria é o jogo de culinária de fast food ideal no qual você pode fazer pizza para seus clientes! Atenda todas as "chamadas de pedido de pizza", faça e venda pizza e obtenha uma avaliação dos clientes. Certifique-se de não decepcioná-los, siga a receita cuidadosamente e entregue a pizza no prazo!',
  'Toque na tela',
  'https://html5.gamemonetize.com/hd4lbep45o231k8y0bigxwuwct3nqhzy/',
  'Culinária',
  'Cozinhar, Culinária',
  'https://img.gamemonetize.com/hd4lbep45o231k8y0bigxwuwct3nqhzy/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'loja-hamburguer-engracado',
  'Loja de Hambúrguer Engraçado',
  'Prepare seus hambúrgueres de acordo com os desejos de seus clientes. Tente entregar no prazo ou seus clientes abandonarão o pedido.',
  'Toque na tela',
  'https://html5.gamemonetize.com/zc1z6q0q9o21pejfqukrirvvhg7rpvno/',
  'Culinária',
  'Hambúrguer, Cozinhar, Culinária, Unity3D',
  'https://img.gamemonetize.com/zc1z6q0q9o21pejfqukrirvvhg7rpvno/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'fabricante-smoothie-engracado',
  'Fabricante de Smoothie Engraçado',
  'Bem-vindo ao nosso império de smoothies, onde você pode fazer os melhores smoothies! Uma vez que seu smoothie esteja pronto, use nossos materiais de decoração que podem transformar smoothies em sobremesas saborosas e gostosas! Faça a mesma coisa com copos de smoothie – decore-os com diferentes canudos e adesivos. Faça smoothies parecerem adoráveis.',
  'Toque na tela',
  'https://html5.gamemonetize.com/i1f8y1bxilwuba1qh8nkx1fanmv0p3a2/',
  'Culinária',
  'Meninos, Culinária, Meninas, Crianças',
  'https://img.gamemonetize.com/i1f8y1bxilwuba1qh8nkx1fanmv0p3a2/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'fabricacao-batata-chips',
  'Fabricação de Batata Chips',
  'Entre no mundo dos jogos de fast food com níveis e faça as melhores batatas chips de todos os tempos',
  'Toque na tela',
  'https://html5.gamemonetize.com/p6oceg8cc0ypmw6vipg94mmps4j8ff15/',
  'Culinária',
  'Cozinhar, Culinária, Restaurante',
  'https://img.gamemonetize.com/p6oceg8cc0ypmw6vipg94mmps4j8ff15/512x384.jpg',
  800,
  600,
  0,
  0,
  4
),
(
  'culinaria-papai-noel',
  'Culinária do Papai Noel',
  'Culinária do Papai Noel é um dos mais novos e viciantes jogos de culinária de restaurante, apresentando habilidades de gerenciamento de tempo, estratégia e diversão de simulação. Mostre suas habilidades culinárias fazendo hambúrgueres deliciosos e torradas para se tornar um chef mestre!',
  'Culinária é louca Toque nos ingredientes para criar comida',
  'https://html5.gamemonetize.com/z6xc8b32h9hjfyk7gzagezfwxmn1n1p4/',
  'Culinária',
  'Natal, Culinária, Engraçado, Quebra-cabeça, Habilidades, Estratégia, Timing',
  'https://img.gamemonetize.com/z6xc8b32h9hjfyk7gzagezfwxmn1n1p4/512x384.jpg',
  1920,
  1080,
  0,
  0,
  4
),
(
  'simulador-restaurante-aberto',
  'Simulador de Restaurante Aberto',
  'Restaurante Aberto é um jogo onde você tem que administrar um restaurante e trazer suas habilidades de gerenciamento para cada cliente! Sobreviva ao alvo diário para obter pontuação alta.',
  'jogo simples velocidade para satisfação do cliente',
  'https://html5.gamemonetize.com/yhzo0lrt6x8jk9kru67h321qfo0o8202/',
  'Culinária',
  '3D, Jogos 3D, Restaurante, Simulação, Simulador',
  'https://img.gamemonetize.com/yhzo0lrt6x8jk9kru67h321qfo0o8202/512x384.jpg',
  800,
  600,
  0,
  0,
  4
);

-- Verificar se os jogos foram adicionados corretamente
SELECT COUNT(*) as total_jogos_pagina_4 FROM games WHERE page = 4;
SELECT id, title, category FROM games WHERE page = 4 ORDER BY id;