-- Migration 024: Adicionar jogos de tiro na página 5
-- Criado: 2024
-- Descrição: Adiciona 32 jogos de tiro traduzidos para português na página 5

INSERT INTO games (
  id, title, description, instructions, url, category, tags, thumb, width, height, views, likes, page
) VALUES 
(
  'salto-circulo',
  'Salto do Círculo',
  'Controle a seta para correr até o próximo círculo. Aproveite o momento, para que a seta corra e evite o vórtice. Venha experimentar e veja quantos pontos você pode ganhar.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/3irb0wmjx8kc93fohm9j22rxpeim8j2d/',
  'Tiro',
  '1 Jogador, Aventura, Arcade',
  'https://img.gamemonetize.com/3irb0wmjx8kc93fohm9j22rxpeim8j2d/512x384.jpg',
  350,
  600,
  0,
  0,
  5
),
(
  'matematica-maluca',
  'Matemática Maluca',
  'Descubra rapidamente a resposta certa. O jogo mostrará rapidamente um problema de cálculo simples, você precisa calcular a resposta correta. Cada resposta correta fará seu personagem disparar uma bala para matar o inseto à sua frente. Mate um inseto para ganhar um ponto. Venha experimentar e veja quantos pontos você pode conseguir.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/85hu8a9g2ve9wi36y5k9byzdrd30tcux/',
  'Tiro',
  'Arcade, Matemática, Tiro',
  'https://img.gamemonetize.com/85hu8a9g2ve9wi36y5k9byzdrd30tcux/512x384.jpg',
  350,
  600,
  0,
  0,
  5
),
(
  'cavaleiro-frango-tiro',
  'Cavaleiro do Frango Tiro Tung Tung Sahur',
  'Entre no mundo selvagem, maluco e pixelizado do Cavaleiro do Frango Tiro Tung Tung Sahur — um shooter de ação em ritmo acelerado onde o herói mais improvável enfrenta o submundo criminoso de uma Las Vegas estilo Minecraft. Você é o Cavaleiro do Frango, um bebê zumbi lendário montado em um frango destemido, armado com coragem, determinação e um blaster confiável.',
  'Apenas mouse',
  'https://html5.gamemonetize.com/5jekjsbk5wqleu5n4k5sqxibpycywcth/',
  'Tiro',
  '1 Jogador, 8 Ball Pool, Ação, Ar, Avião, Apocalipse, Arena, Mineblock, Minecraft',
  'https://img.gamemonetize.com/5jekjsbk5wqleu5n4k5sqxibpycywcth/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'vale-corrida',
  'Vale da Corrida',
  'Controle a aventura dos seus pets através de obstáculos. Evite tocar nos espinhos acima dos obstáculos. Há muitos animaizinhos fofos no jogo para desbloquear, você precisa conseguir um certo número de pontos. Venha experimentar.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/8hfx4lj743bimt4oz7u443l7l7ig851d/',
  'Tiro',
  '3D, Aventura, Tijolos',
  'https://img.gamemonetize.com/8hfx4lj743bimt4oz7u443l7l7ig851d/512x384.jpg',
  350,
  600,
  0,
  0,
  5
),
(
  'mestre-tanque',
  'Mestre dos Tanques',
  'A batalha começou. Enfrente seu oponente com os canhões e destrua o maior número de tanques possível antes que eles te matem. Lute contra inimigos astutos, colete power-ups e complete mais de 100 níveis de ação incrível. Colete moedas e melhore sua máquina de guerra com novos canhões, balas e armadura para ser o líder.',
  'Use o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/r50sosv94qp15bkjhze2givwy8z5bsuu/',
  'Tiro',
  'Jogos .io, 1 Jogador, 2D, Ação, Exército, Infinito, Shoot Em Up, Atirador, Tanque',
  'https://img.gamemonetize.com/r50sosv94qp15bkjhze2givwy8z5bsuu/512x384.jpg',
  800,
  480,
  0,
  0,
  5
),
(
  'explosao-bolhas-doces',
  'Explosão de Bolhas Doces - Bubble Shooter',
  'No jogo Bubble Shooter Halloween, seu objetivo é estourar todas as bolhas antes que elas cheguem ao chão. Mire e atire para combinar bolhas da mesma cor — quando você acertar um grupo correspondente, elas explodirão e você ganhará pontos.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/w9euon0rmteaatp9nh7do14cfkyws0mr/',
  'Tiro',
  '1 Jogador, Bubble Shooter, Diversão, Crianças',
  'https://img.gamemonetize.com/w9euon0rmteaatp9nh7do14cfkyws0mr/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'vira-arma',
  'Vira a Arma',
  'Role para cima com o recuo da arma. Tocar na tela faz a arma disparar, usando o recuo para rolar a arma para cima. Você ganha sprints e munição durante o rolamento. Moedas também são ganhas durante o rolamento, que podem desbloquear armas melhores. Venha experimentar.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/z22yvqrpc17cmoy7pisqv0ac1pdldhit/',
  'Tiro',
  'Aventura, Arcade, Tiro',
  'https://img.gamemonetize.com/z22yvqrpc17cmoy7pisqv0ac1pdldhit/512x384.jpg',
  350,
  600,
  0,
  0,
  5
),
(
  'ninja-sombra-kunai',
  'Ninja Sombra Kunai',
  'Entre no mundo das sombras em Ninja Sombra Kunai — um jogo ninja 2D de arremesso de facas em ritmo acelerado inspirado em lendas como Naruto e guerreiros shinobi clássicos! Domine a arte do arremesso de kunai enquanto assume o controle de um assassino ninja silencioso. Toque e mire com precisão para derrubar inimigos, quebrar obstáculos e sobreviver a ondas infinitas de desafios.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/rt9dgc33ezpdvzsqsijnzgylr32rtkxe/',
  'Tiro',
  'Casual, Ninja, Atirar, Tiro',
  'https://img.gamemonetize.com/rt9dgc33ezpdvzsqsijnzgylr32rtkxe/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'guerra-stickman',
  'Guerra Stickman',
  'Em um futuro distópico, o mundo está à beira da guerra. É hora da humanidade precisar do pacificador. Lute contra hordas de terroristas, melhore seus equipamentos de guerra e traga a paz de volta à Terra novamente!',
  'Use o mouse e teclado ou toque para jogar',
  'https://html5.gamemonetize.com/g29vickxti7tbf2f5srhvijd3w3azse4/',
  'Tiro',
  '1 Jogador, Ação, Exército, Batalha, Battlegrounds, Defesa, Atirador, Stickman, Tower Defense, Guerra',
  'https://img.gamemonetize.com/g29vickxti7tbf2f5srhvijd3w3azse4/512x384.jpg',
  800,
  480,
  0,
  0,
  5
),
(
  'ataque-moto',
  'Ataque de Moto',
  'Enfrente o maravilhoso Confronto de Ataque de Moto! Neste jogo de ação explosivo, você não está apenas correndo. Você também está atirando e lutando através de ondas de inimigos em seu carro poderoso! Perfeito para todo garoto amante de ação, Ataque de Moto é a combinação de alta octanagem de corrida, direção e tiro que você estava esperando.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/3qo6bwp6aea8pj4ntuulxtyqsszn30ns/',
  'Tiro',
  'Inimigos, Luta, Moto, Corrida',
  'https://img.gamemonetize.com/3qo6bwp6aea8pj4ntuulxtyqsszn30ns/512x384.jpg',
  1280,
  720,
  0,
  0,
  5
),
(
  'brrbrr-patapim',
  'BrrBrr Patapim',
  'BrrBrr Patapim é um épico shooter em primeira pessoa 3D onde você enfrenta o inimigo bizarro e poderoso—BrrBrr Patapim! Explore o mapa, colete armas poderosas e lance granadas enquanto luta para sobreviver à loucura. Com ação em ritmo acelerado, energia alimentada por memes e diversão sem parar, esta é uma experiência de tiro selvagem e exagerada que você não esquecerá!',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/1656arhg2u1z6evbbz5bcdqy39eyxk1d/',
  'Tiro',
  '3D, Animal, Anime, Desenho Animado, Atirador',
  'https://img.gamemonetize.com/1656arhg2u1z6evbbz5bcdqy39eyxk1d/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'anel-fogo',
  'Anel de Fogo',
  'Anel de Fogo é um desafio ardente e em ritmo acelerado que testará seu timing e reflexos! Guie seu orbe flamejante através de anéis rotativos, lacunas mutáveis e obstáculos ardentes em um jogo onde um movimento errado significa game over. Toque para saltar através de aberturas, evite as chamas e suba para alcançar a pontuação mais alta.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/lqw68u7gzk1pn7dpst8a08ta9rhai7k1/',
  'Tiro',
  'Arcade, Bola, Melhor, Melhores Jogos, Clique, Escape, Fogo, Bombeiros, Apontar e Clicar, Quebra-cabeça, Tiro, Espaço',
  'https://img.gamemonetize.com/lqw68u7gzk1pn7dpst8a08ta9rhai7k1/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'residentes-mal-guerra-tarifaria',
  'Residentes do Mal: Guerra Tarifária',
  'Na sombra de uma guerra tarifária global, o mundo vacila à beira do colapso. O Presidente foi sequestrado por uma nação hostil e levado para um bio-laboratório ultra-secreto para experimentos indescritíveis. Você é um ex-agente de operações especiais enviado para território inimigo em uma missão de resgate de alto risco.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/fflrrt8bl8iqdlrz9drpklg3o8phfasd/',
  'Tiro',
  'Horror, Labirinto, Quebra-cabeça, Tiro, Guerra, Armas, Zumbi',
  'https://img.gamemonetize.com/fflrrt8bl8iqdlrz9drpklg3o8phfasd/512x384.jpg',
  1280,
  720,
  0,
  0,
  5
),
(
  'destruicao-invasores',
  'Destruição dos Invasores',
  'Destruição dos Invasores – Shooter Espacial Arcade Clássico – Defenda a Terra em Estilo Retrô! Capitão, a Terra precisa de você! Invasores alienígenas cercaram nosso planeta, ameaçando destruir tudo que consideramos querido. Os céus estão cheios de naves inimigas, suas armas apontadas para nossas cidades, nossos lares e nossos entes queridos.',
  'Teclado Z X C e S se mega foguete estiver desbloqueado ou toque para jogar',
  'https://html5.gamemonetize.com/hj96k2buy81zylbjzuyoas898s5xibe4/',
  'Tiro',
  '1 Jogador, 2D, Ação, Aeronave, Avião, Arcade, Ataque, Retrô, Atirar, Shoot Em Up, Atirador, Tiro, Espaço, Nave Espacial',
  'https://img.gamemonetize.com/hj96k2buy81zylbjzuyoas898s5xibe4/512x384.jpg',
  720,
  1280,
  0,
  0,
  5
),
(
  'fruta-espeto',
  'Fruta no Espeto',
  'Mire e atire nas frutas suculentas que caem de muitos tipos. Atire em múltiplas frutas com um espeto para combos. Obtenha as melhores pontuações nos modos Clássico e Contra o Tempo.',
  'Clique ou toque e arraste para mirar, então solte para atirar',
  'https://html5.gamemonetize.com/0fgyb9jvnyq1g35j2sz3aehyjabxvy2e/',
  'Tiro',
  '1 Jogador, 2D, Bubble Shooter, Fruta, Frutas, Pontuação Alta, Atirador, Tiro',
  'https://img.gamemonetize.com/0fgyb9jvnyq1g35j2sz3aehyjabxvy2e/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'metal-auto-torcido',
  'Metal Auto Torcido',
  'Metal Auto Torcido é um jogo explosivo de combate veicular ambientado em um deserto pós-apocalíptico onde o caos reina e apenas os motoristas mais mortais sobrevivem. Inspirado em títulos clássicos como Twisted Metal, este shooter de alta octanagem coloca os jogadores atrás do volante de carros brutalizados e armados, incluindo o icônico Nissan Skyline.',
  'WASD mover',
  'https://html5.gamemonetize.com/xxdj5e8m9r6b38u5nx08mtwpaqcaiql8/',
  'Tiro',
  '1 Jogador, 3D, Batalha, Direção',
  'https://img.gamemonetize.com/xxdj5e8m9r6b38u5nx08mtwpaqcaiql8/512x384.jpg',
  960,
  600,
  0,
  0,
  5
),
(
  'lendas-john-malvado',
  'Lendas John Malvado',
  'John foi chamado urgentemente para o dever, mas um erro que cometeu durante a missão o colocou em uma situação perigosa. John Malvado está furioso — ele se armou com todas as suas armas e está pronto para a batalha. Atire em todos os bandidos que ficarem no seu caminho e chegue ao seu carro. Entre e escape da cena.',
  'Use as teclas WASD para mover. Atire e derrote todos os inimigos que chegam. Chegue ao seu carro com segurança. Jogável tanto em celular quanto em PC',
  'https://html5.gamemonetize.com/u3ueg1yymng353tm76ubf6or4ea8319k/',
  'Tiro',
  'Ação, Aventura, Shooter em Primeira Pessoa, Arma, Atirador',
  'https://img.gamemonetize.com/u3ueg1yymng353tm76ubf6or4ea8319k/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'linha-frente-arco-iris',
  'Linha de Frente Arco-íris',
  'Linha de Frente Arco-íris é um shooter 2D pixel em ritmo acelerado ambientado em uma galáxia arco-íris vibrante sob cerco! Assuma o controle de uma nave espacial retrô, desvie de meteoros que caem e exploda inimigos alienígenas coloridos em batalhas baseadas em ondas. Domine o tema de cada nível — do vermelho ao violeta — enquanto luta através do espectro!',
  'Controle para Teclado: Teclas de seta ou WASD → Controle de Direção. Tecla Espaço → Controle de Fogo. Para Mobile: Controle de Joystick Virtual',
  'https://html5.gamemonetize.com/rqgswayf7z65y1shros2d14rwhnls3yj/',
  'Tiro',
  '1 Jogador, 2D, Avião, Arcade, Pixel, Nave Espacial',
  'https://img.gamemonetize.com/rqgswayf7z65y1shros2d14rwhnls3yj/512x384.jpg',
  540,
  960,
  0,
  0,
  5
),
(
  'agente-caca-tiro',
  'Agente Caça Tiro',
  'Você joga o papel de um agente de elite e está preso em uma batalha nervosa. Entre no Agente Caça Tiro, pegue uma arma poderosa em sua mão e destrua seus inimigos com tiro de precisão! Esconda-se atrás das caixas para se cobrir e cace os inimigos. Vencendo, selecione armas de maior dano, bombas, capacetes, etc.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/i5pai5kh2haeh7c3qmb30mjqsws4l9ks/',
  'Tiro',
  'Batalha, Caça, Armas',
  'https://img.gamemonetize.com/i5pai5kh2haeh7c3qmb30mjqsws4l9ks/512x384.jpg',
  1280,
  720,
  0,
  0,
  5
),
(
  'orbes-oceano',
  'Orbes do Oceano',
  'Mergulhe no azul profundo em Orbes do Oceano, uma aventura subaquática hipnotizante! Combine os orbes adoráveis conforme eles flutuam para baixo e guie-os para a zona de cor correta. Com visuais oceânicos deslumbrantes e música tranquila, Orbes do Oceano oferece uma experiência de jogabilidade relaxante, mas desafiadora.',
  'Orbes de cores diferentes flutuarão da parte superior da tela. Toque no botão de orbe correto na parte inferior para combinar a cor do orbe que está caindo. Perder uma combinação custará uma vida. Você tem 5 vidas por jogo',
  'https://html5.gamemonetize.com/8x38e1tbpcybabri2iapa98s5smw2bzr/',
  'Tiro',
  '1 Jogador, 2048, 2D, Android, Melhor, Melhores Jogos, Shoot Em Up, Atirador, Tiro',
  'https://img.gamemonetize.com/8x38e1tbpcybabri2iapa98s5smw2bzr/512x384.jpg',
  720,
  1280,
  0,
  0,
  5
),
(
  'tung-tung-sahur-zumbi',
  'Tung Tung Sahur Zumbi',
  'Tung Tung Sahur Zumbi— um jogo super legal no qual você deve matar todos os zumbis, acertos diretos de balas, bem como o ricochete! Compartilhe do que você é capaz e destrua todos os zumbis o mais rápido possível! Aproveite o jogo!',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/9e0dmqixqwds3g3y1vpuxjwaseq7yetu/',
  'Tiro',
  'Arcade, Sahur, Atirador, Sniper, Tung Tung, Tung Tung Tung Sahur, Zumbi',
  'https://img.gamemonetize.com/9e0dmqixqwds3g3y1vpuxjwaseq7yetu/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'atirador-armas',
  'Atirador de Armas',
  'Bem-vindo ao Atirador de Armas 3D Jogo de Tiro! Você joga como um cavaleiro e sua missão é girar e escolher sua arma para atacar os monstros. Divirta-se!',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/zuyr8qluffzmjsqa9k33eiwv5vd2rxew/',
  'Tiro',
  'Monstro, Armas, Zumbi',
  'https://img.gamemonetize.com/zuyr8qluffzmjsqa9k33eiwv5vd2rxew/512x384.jpg',
  720,
  1280,
  0,
  0,
  5
),
(
  'confronto-cristal',
  'Confronto de Cristal',
  'Entre no mundo deslumbrante do Confronto de Cristal, onde os jogadores navegam por um reino cristalino de tirar o fôlego. Combine e alinhe cristais cintilantes conforme eles descem, mirando marcar o maior número de pontos possível antes do jogo acabar.',
  'Iniciar o Jogo: Toque no botão Iniciar para começar. Combinar Cristais: Toque nos botões coloridos na parte inferior para combinar os cristais que descem. Marcar Pontos: Ganhe pontos combinando cristais corretamente o mais rápido possível',
  'https://html5.gamemonetize.com/1y8i7ouaaz2jh1jq5oczbi10fw8luj3x/',
  'Tiro',
  '1 Jogador, 2048, 2D, Android, Melhor, Melhores Jogos, Atirar, Shoot Em Up, Tiro',
  'https://img.gamemonetize.com/1y8i7ouaaz2jh1jq5oczbi10fw8luj3x/512x384.jpg',
  720,
  1280,
  0,
  0,
  5
),
(
  'tanque-8bit',
  'Tanque 8Bit',
  'Jogo de tanque 8Bit para amantes da nostalgia! Destrua tanques inimigos, colete pontos e tente conseguir a pontuação mais alta! Comece a jogar este jogo cheio de ação agora!',
  'Seta Esquerda A Ir Esquerda. Seta Direita D Ir Direita. Espaço Atirar. Aqueles que fazem login pelo celular podem usar controles de toque',
  'https://html5.gamemonetize.com/63gftpz0ypcgefikbbnfj18dc54tyd16/',
  'Tiro',
  '1 Jogador, 2D, Ação, Tanque',
  'https://img.gamemonetize.com/63gftpz0ypcgefikbbnfj18dc54tyd16/512x384.jpg',
  480,
  720,
  0,
  0,
  5
),
(
  'counter-craft-classico-2',
  'Counter Craft Clássico 2',
  'Counter Craft Clássico 2 é um shooter emocionante em primeira pessoa que combina os melhores elementos das armas do Counter-Strike com ambientes estilo Minecraft. Entre em campos de batalha blocados cheios de mobs perigosos, tiroteios intensos e ação em ritmo acelerado. Armado com armas icônicas como AWP, AK-47, Desert Eagle e mais, sua missão é simples, mas desafiadora.',
  'WASD - Mover LMB - Atirar RMB - Mirar Lanterna R - Recarregar G - Granada H - Corpo a Corpo C - Agachar M - Mudo Espaço - Pular Shift - Correr 1-9 - Selecionar Arma',
  'https://html5.gamemonetize.com/gxwulrf1sr4thmrx7bo3w4f3ks3cofwk/',
  'Tiro',
  '3D, Jogos 3D, CSGO, Shooter em Primeira Pessoa, Minecraft, Atirar, Shoot Em Up, Atirador, Tiro, Unity3D',
  'https://img.gamemonetize.com/gxwulrf1sr4thmrx7bo3w4f3ks3cofwk/512x384.jpg',
  960,
  600,
  0,
  0,
  5
),
(
  'polygun-idle-td',
  'PolyGun: Idle TD',
  'Bem-vindo ao PolyGun – o definitivo shooter idle tower defense! Assuma o comando de uma poderosa torre de tiro automático e mergulhe em um mundo dominado por ondas infinitas de inimigos geométricos. Cada inimigo tem seu próprio padrão de movimento, e eles não estão aqui para brincar. Melhore, desbloqueie, domine. Potencialize com cartas. Complete missões e desafios. Ganhe recompensas diárias.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/oiogyrk33rkn63dyivstyxp4jsi7fn5l/',
  'Tiro',
  'Ação, Arena, Idle, Polígono, Tiro, Sobrevivência, Tower Defense',
  'https://img.gamemonetize.com/oiogyrk33rkn63dyivstyxp4jsi7fn5l/512x384.jpg',
  1280,
  720,
  0,
  0,
  5
),
(
  'onibus-perdido',
  'Ônibus Perdido',
  'Após a última guerra nuclear na terra, as pessoas sofreram mutação e se tornaram zumbis, alguns deles se tornaram de tamanhos irreais, aterrorizando a imaginação. Todos estão contra você, exceto sua garota devotada Sasha e seu ônibus escolar modernizado em caso de X. Às vezes os militares podem ajudá-lo, às vezes as modificações do ônibus, e às vezes a sorte. Sobreviva a este INFERNO!!!',
  'Todas as instruções de controle na seção controle no menu inicial. Controle adaptado para dispositivos Desktop e Mobile',
  'https://html5.gamemonetize.com/7mk4877sa9dsncmfvos70ovm1kfggcxa/',
  'Tiro',
  'Defesa, Monstro, Atirador, Sobrevivência, Zumbi',
  'https://img.gamemonetize.com/7mk4877sa9dsncmfvos70ovm1kfggcxa/512x384.jpg',
  900,
  600,
  0,
  0,
  5
),
(
  'bar-mentirosos',
  'Bar dos Mentirosos',
  'Bem-vindo a um mundo de estratégia, inteligência e jogos mentais no Bar dos Mentirosos. Aqui, você precisará de mais do que apenas sorte. Tudo depende de sua inteligência para superar seus oponentes. Se você gosta de blefar, jogos de adivinhação e um pouco de mentira, então este é o jogo para você. Escolha o Duelo de Revólver ou Duelo de Cão.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/sxph8qyc222kubj5z8r2gpzxbhq9dhcb/',
  'Tiro',
  'Adivinhação, Arma, Estratégia',
  'https://img.gamemonetize.com/sxph8qyc222kubj5z8r2gpzxbhq9dhcb/512x384.jpg',
  1560,
  720,
  0,
  0,
  5
),
(
  'grande-cidade-crime',
  'Grande Cidade do Crime',
  'Entre nas ruas sombrias da Grande Cidade do Crime, onde o perigo espreita em cada esquina e apenas os mais resistentes sobrevivem. Neste jogo de tiro cheio de ação, você assumirá o papel de um vigilante destemido completando missões intensas para trazer ordem — ou caos — à cidade. Com 20 missões emocionantes, cada uma mais desafiadora que a anterior.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/ccons3f0b0o17o9zzx7idewbiro075i1/',
  'Tiro',
  'Cidade, Luta, Shooter em Primeira Pessoa, GTA, Matança, Atirar, Shoot Em Up, Tiro',
  'https://img.gamemonetize.com/ccons3f0b0o17o9zzx7idewbiro075i1/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'resident-evil-operacao-purga',
  'Resident Evil: Operação Purga',
  'No início de cada nível, os jogadores devem localizar rapidamente armas poderosas como a espingarda e rifle sniper, cruciais para repelir hordas de zumbis. Uma vez que o alarme sinistro soa, mortos-vivos grotescos e ferozes inundam a área. Um único erro pode levar a ser cercado, então marksmanship preciso, movimento ágil e julgamento calmo são essenciais para a sobrevivência.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/8dmfr9r473kkux0h9kbqn7iolfllp6ak/',
  'Tiro',
  '3D, Horror, Atirar, Armas, Zumbi',
  'https://img.gamemonetize.com/8dmfr9r473kkux0h9kbqn7iolfllp6ak/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'mestre-alvo-2d',
  'Mestre do Alvo 2D',
  'Te joga em uma corrida arcade em ritmo acelerado onde cada tiro conta. Mire sua bola brilhante, calcule arcos perfeitos e exploda através de obstáculos complicados em um mundo cheio de luzes vibrantes e momentum suave. Não é apenas sobre pular — é sobre timing, precisão e estilo. Pule, atire e deslize através de níveis 3D insanos que ficam mais difíceis quanto mais longe você vai.',
  'Clique com o mouse ou toque para jogar',
  'https://html5.gamemonetize.com/nmcnse5rq33jki9ky4zie8rhp63m4xav/',
  'Tiro',
  '3D, Jogos 3D, Bola, Casual, Hypercasual, Atirador, Tiro, Jogos Unity para seu site, Jogos Unity para seu website',
  'https://img.gamemonetize.com/nmcnse5rq33jki9ky4zie8rhp63m4xav/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'atirador-carnaval',
  'Atirador do Carnaval',
  'Atirador do Carnaval traz a diversão da feira para suas pontas dos dedos! Aproxime-se e teste sua mira nesta galeria de tiro vibrante e em ritmo acelerado. Exploda balões, derrube latas, acerte alvos em movimento e marque alto para ganhar prêmios emocionantes. Com visuais temáticos de carnaval coloridos, efeitos sonoros satisfatórios e uma variedade de desafios peculiares.',
  'Use o Mouse para jogar',
  'https://html5.gamemonetize.com/zjffrydbxq3l8tky673mpq5ejbeeit30/',
  'Tiro',
  'Desenho Animado, Diversão, Quebra-cabeça, Atirar, Tiro',
  'https://img.gamemonetize.com/zjffrydbxq3l8tky673mpq5ejbeeit30/512x384.jpg',
  800,
  600,
  0,
  0,
  5
),
(
  'zona-radiacao',
  'Zona de Radiação',
  'É um shooter FPS com zumbis e militares. Sua missão é limpar a área de todos os terroristas na zona de radiação restrita. Você pode encontrar e usar muitos tipos de armas e munição na área. Disponível para você inventário, onde você pode coletar um saque para sobreviver. Para fazer uma tenda, você precisa coletar quatro roupas e quatro galhos.',
  'WASD - Movimento Ctrl - Agachar LShift - Sprint Q E - Inclinar esquerda direita F - Pegar ou Inspecionar Caixa de Arma 1 2 3 - Trocar Armas G - Granada LMB - Fogo RMB - Mirar Tab - Inventário Duplo clique no item - usar Duplo clique direito - descartar',
  'https://html5.gamemonetize.com/6soajborlx4vhi236yzk4i2be8og80jy/',
  'Tiro',
  'Militar, Atirador, Sobrevivência, Zumbi',
  'https://img.gamemonetize.com/6soajborlx4vhi236yzk4i2be8og80jy/512x384.jpg',
  800,
  500,
  0,
  0,
  5
);

-- Verificar se os jogos foram adicionados corretamente
SELECT COUNT(*) as total_jogos_pagina_5 FROM games WHERE page = 5;
SELECT id, title, category FROM games WHERE page = 5 ORDER BY id; 