-- Migration 025: Adicionar jogos de corrida na página 6
-- Criado: 2024
-- Descrição: Adiciona 35 jogos de corrida traduzidos para português na página 6

INSERT INTO games (
  id, title, description, instructions, url, category, tags, thumb, width, height, views, likes, page
) VALUES 
(
  'direcao-russa-taz-2',
  'Direção Russa Taz 2',
  'Russian Taz Driving 2 apresenta gráficos incríveis e muitos carros russos diferentes para dirigir e fazer drift pelas ruas da grande cidade cheias de gopniks russos dançando.',
  'WASD - Dirigir, Espaço - Freio, C - Mudar câmera',
  'https://html5.gamemonetize.com/ulqp6jflm90q0hrtvsjtna5zdjocfic9/',
  'Corrida',
  '1 Jogador, 3D, Jogos 3D, Carro, Carros, drift, Direção, gta, Corrida, Unity3D, WebGL',
  'https://img.gamemonetize.com/ulqp6jflm90q0hrtvsjtna5zdjocfic9/512x384.jpg',
  960,
  600,
  0,
  0,
  6
),
(
  'heroi-da-superbike',
  'Herói da Superbike',
  'Compita pela Europa e Oriente Médio enquanto corre na Série Superbike. Acelere entre oponentes, segure-se em curvas apertadas, colete moedas e melhore sua superbike para a próxima corrida. Você é o Herói da Superbike?',
  'Mobile use touch para dirigir, Desktop use setas ou WASD',
  'https://html5.gamemonetize.com/xadmbez57xew9kcphfpu4gaye4bt38t1/',
  'Corrida',
  '3D, Arcade, Moto, Clássico, Hypercasual, Mobile, Corrida, Racing',
  'https://img.gamemonetize.com/xadmbez57xew9kcphfpu4gaye4bt38t1/512x384.jpg',
  720,
  405,
  0,
  0,
  6
),
(
  'carro-voador-supremo',
  'Carro Voador Supremo',
  'Você quer fazer corridas rápidas e voos nas longas ruas da cidade? O jogo Ultimate Flying Car te convida para uma experiência realista de simulador de carro voador. Explore o céu com carros voadores estilosos, ou desbloqueie novos carros participando de corridas. Você pode jogar todos esses modos de jogo para 1 jogador ou 2 jogadores.',
  'Jogador 1: Mover WASD, NOS SHIFT, Olhar para trás T, Consertar posição do carro R, Freio de mão ESPAÇO. Jogador 2: Mover SETAS, NOS M, Olhar para trás L, Consertar posição U, Freio de mão K',
  'https://html5.gamemonetize.com/yqbipdebtjz8q97zamh7utwjdrs1bh1e/',
  'Corrida',
  '2 Jogadores, Jogos 2 Jogadores, Direção, Voo, voar, Corrida, Acrobacias, Supercarros',
  'https://img.gamemonetize.com/yqbipdebtjz8q97zamh7utwjdrs1bh1e/512x384.jpg',
  800,
  450,
  0,
  0,
  6
),
(
  'carro-come-carro-aventura-masmorra',
  'Carro Come Carro: Aventura na Masmorra',
  'Pronto para uma luta contra rivais em uma corrida dinâmica na estrada? Ultrapasse inimigos e crie seu próprio carro na incubadora em Car Eats Car: Dungeon Adventure! Seus amigos foram presos - faça tudo que puder para libertar os carros malvados! Boas habilidades de direção e velocidade turbo são úteis neste simulador de direção maluco e jogo de perseguição policial.',
  'Espaço - Bombas, X - Turbo, W - Acelerar, S - Freio, A D - Equilibrar, Setas - Acelerar Freio Equilibrar',
  'https://html5.gamemonetize.com/2ysdz38kvh0t5zfu64oew4wzbbginajp/',
  'Corrida',
  '2D, Ação, Carro, Carros, Família, Corrida, Racing, WebGL',
  'https://img.gamemonetize.com/2ysdz38kvh0t5zfu64oew4wzbbginajp/512x384.jpg',
  800,
  500,
  0,
  0,
  6
),
(
  'simulador-direcao-cyber-truck',
  'Simulador de Direção Cyber Truck',
  'O carro mais falado recentemente, Cyber Truck Drive Simulator te dá uma experiência única. Física realista, efeitos sonoros e interface avançada permite que você se divirta. No Cyber Truck Drive Simulator, seu objetivo é coletar as bandeiras no mapa de forma que o dano ao carro seja mínimo. E antes que o tempo acabe :)',
  'WASD ou setas. Você pode freiar com Espaço. Pode mudar para diferentes ângulos de câmera com a tecla C',
  'https://html5.gamemonetize.com/7xk1ek5ya108fojn7b3df0ajdx2k5jhc/',
  'Corrida',
  '1 Jogador, 3D, Ação, Carro, Carros, Casual, Natal, Fantasia, Engraçado, Jogo, Hypercasual, Corrida, Racing, Supercarros',
  'https://img.gamemonetize.com/7xk1ek5ya108fojn7b3df0ajdx2k5jhc/512x384.jpg',
  900,
  600,
  0,
  0,
  6
),
(
  'subway-surfers-berlim',
  'Subway Surfers em Berlim',
  'Subway Surfers World Tour: Berlin 2021 é a centésima vigésima terceira edição da série Subway Surfers World Tour e a centésima décima parcela da série World Tour.',
  'Controle no jogo Subway Surfers Berlin no computador é feito usando as setas, espaço - para ativar o skate. O objetivo do jogo é o herói correr o mais longe possível superando obstáculos e desviando',
  'https://html5.gamemonetize.com/ese52z6zggy691j61gpdwtv2me3rjduy/',
  'Corrida',
  '3D, Jogos 3D, Aventura, H5, Hot, HTML, HTML5, pular, Pulando, Corrida, Racing, correr, correndo, subway, Subway Surfers, Unity3D',
  'https://img.gamemonetize.com/ese52z6zggy691j61gpdwtv2me3rjduy/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'dia-louco-especial',
  'Dia Louco Especial',
  'Lute contra a Invasão Alienígena da Terra nesta corrida épica para resgatar seu amado polvo de estimação Fluffy e escapar. Mad Day é uma combinação de um jogo incrível de corrida e tiro alienígena. Melhore seu Carro, Armas, Armadura, Roupas e mais para vencer os bandidos.',
  'Espaço - Pular, X Seta para Cima - Foguetes',
  'https://html5.gamemonetize.com/x1pcf3eqnaqhacegno3gkgidfsbz7us4/',
  'Corrida',
  '2D, Ação, Alienígena, Batalha, Carro, Carros, WebGL',
  'https://img.gamemonetize.com/x1pcf3eqnaqhacegno3gkgidfsbz7us4/512x384.jpg',
  800,
  500,
  0,
  0,
  6
),
(
  'motorista-mercenario-gta-maluco',
  'Motorista Mercenário GTA Maluco',
  'Jogo estilo GTA está aqui, dirigindo carros, roubando carros, coletando dinheiro, matando pedestres é o melhor modo de jogo para este incrível jogo de direção RCK GTA Mercenary Driver, você tem 100 níveis únicos para se divertir, roubar e estacionar carro.',
  'E - Entrar/sair do carro, Tab - menu, Espaço - Freio, WASD - Dirigir, G - Resetar carro',
  'https://html5.gamemonetize.com/ms6hpyknf5j9xmghxznncws9b8eee2n0/',
  'Corrida',
  '3D, Jogos 3D, Carro, Carros, drift, drifting, Direção, gta, Estacionar, Corrida, Racing, Supercarros, Unity3D, WebGL',
  'https://img.gamemonetize.com/ms6hpyknf5j9xmghxznncws9b8eee2n0/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'carro-come-carro-aventura-inverno',
  'Carro Come Carro: Aventura de Inverno',
  'Pronto para uma luta contra rivais em uma corrida dinâmica na estrada? Ultrapasse inimigos e crie seu próprio carro na incubadora em Car Eats Car: Winter Adventure! Seus amigos foram presos - faça tudo que puder para libertar os carros malvados!',
  'Espaço - Bombas, X - Turbo, W - Acelerar, S - Freio, A D - Equilibrar, Setas - Acelerar Freio Equilibrar',
  'https://html5.gamemonetize.com/e8hanet9p6a9z25i94az2aysrh7v5h0k/',
  'Corrida',
  '2D, Ação, Carro, Carros, Desenho Animado, Família, Corrida, Racing, WebGL',
  'https://img.gamemonetize.com/e8hanet9p6a9z25i94az2aysrh7v5h0k/512x384.jpg',
  800,
  500,
  0,
  0,
  6
),
(
  'supercarros-drift-racing',
  'Supercarros Drift Racing Cars',
  'Lendas assumem o volante de carros reais de fabricantes épicos premium proeminentes, como Ferrari, Porsche, Lamborghini e W Motors, entre muitas outras marcas mundiais. Dirija, melhore e execute acrobacias em locais dinâmicos da vida real em jogo solo ou multiplayer.',
  'WASD - dirigir, ESPAÇO - freio',
  'https://html5.gamemonetize.com/k4ffna0j4dx8xjr7njii048zsn2ydw5h/',
  'Corrida',
  '1 Jogador, 3D, Jogos 3D, Melhor, Carro, Carros, drift, drifting, Direção, Jogo, Jogos, Minecraft, Corrida, Super, Supercarros, Unity3D, WebGL',
  'https://img.gamemonetize.com/k4ffna0j4dx8xjr7njii048zsn2ydw5h/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'heroi-do-stock-car',
  'Herói do Stock Car',
  'Compita pela América do Norte enquanto corre na Série Stock Car. Desvie do tráfego, acelere em curvas inclinadas, colete moedas e melhore seu carro para a próxima corrida. Você é o Herói do Stock Car?',
  'Mobile use touch para dirigir, Desktop use setas ou WASD',
  'https://html5.gamemonetize.com/txgllriwza6em334ggoovyr508bo2wow/',
  'Corrida',
  '3D, Arcade, Carro, Clássico, Hypercasual, Mobile, Corrida, Racing',
  'https://img.gamemonetize.com/txgllriwza6em334ggoovyr508bo2wow/512x384.jpg',
  720,
  405,
  0,
  0,
  6
),
(
  'supercarros-dirigindo-zumbis-2',
  'Supercarros Dirigindo Zumbis 2',
  'Supercars Zombie Driving 2 apresenta os supercarros mais rápidos e cidade cheia de zumbis onde você deve encontrar e esmagar todos os zumbis em alta velocidade para vencer.',
  'WASD - Dirigir, Espaço - Freio, C - Mudar câmera',
  'https://html5.gamemonetize.com/y8beyghin9gz988xxzjbu6fx757k477n/',
  'Corrida',
  '1 Jogador, 3D, Jogos 3D, Carro, Carros, Direção, Corrida, Racing, Simulação, Simulador, Supercarros, Unity3D, WebGL, Zumbi',
  'https://img.gamemonetize.com/y8beyghin9gz988xxzjbu6fx757k477n/512x384.jpg',
  960,
  600,
  0,
  0,
  6
),
(
  'simulador-direcao-gangster-vegas',
  'Simulador de Direção Gangster Vegas',
  'Jogo de Tiro Criminal de Direção de Automóvel da Cidade Máfia-Gangster Feroz! Experimente as atividades criminais violentas da área da gangue, torne-se um mafioso incrível, dirija uma variedade de carros de luxo, use uma variedade de ferramentas poderosas!',
  'F para entrar no carro ou sair, Tab para mostrar menu, WASD para dirigir carro ou personagem, Espaço para freio no carro. E muito mais diversão te esperando neste jogo incrível!',
  'https://html5.gamemonetize.com/gksa0vhulij3zd4resscdbm1543davet/',
  'Corrida',
  '3D, Jogos 3D, Melhor, Carro, Carros, Maluco, Direção, Super, Supercarros, Unity3D, WebGL',
  'https://img.gamemonetize.com/gksa0vhulij3zd4resscdbm1543davet/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'estacionamento-caminhao-2-motorista',
  'Estacionamento de Caminhão 2 - Motorista de Caminhão',
  'Police Car Parking Mania 2020: Jogo Simulador de Direção de Rodovia da Cidade Avançada. Police Car Parking 2020 permite que você escolha controles para dirigir estacionamento policial moderno. Master Car Parking game te dá tempo difícil para dirigir seu carro de polícia de luxo.',
  'Controles do Teclado',
  'https://html5.gamemonetize.com/ifzj413r6a9r9kojvy67dez77fm5dgy1/',
  'Corrida',
  '1 Jogador, Jogos 2 Jogadores, 3D, Jogos 3D, Adulto, Aventura, Arcade, Carro, Carros, Jogo, Jogos, Ladybug, Estacionar, Corrida, Racing, Estrada, Simulação, Simulador, Acrobacias, Supercarros, Caminhão, Unity3D',
  'https://img.gamemonetize.com/ifzj413r6a9r9kojvy67dez77fm5dgy1/512x384.jpg',
  900,
  600,
  0,
  0,
  6
),
(
  'heroi-do-grand-prix',
  'Herói do Grand Prix',
  'Compita em múltiplos continentes enquanto corre na Série Grand Prix. Desvie do tráfego, acelere em altas velocidades, colete moedas e melhore seu carro para a próxima corrida. Você é o Herói do Grand Prix?',
  'Mobile use touch para dirigir, Desktop use setas ou WASD',
  'https://html5.gamemonetize.com/xuwx294k0sxrwr1g8ct6vfj0dr9mxymu/',
  'Corrida',
  '3D, Arcade, Carro, Clássico, Hypercasual, Mobile, Corrida, Racing',
  'https://img.gamemonetize.com/xuwx294k0sxrwr1g8ct6vfj0dr9mxymu/512x384.jpg',
  720,
  405,
  0,
  0,
  6
),
(
  'acrobacia-moto-cidade-2',
  'Acrobacia de Moto na Cidade 2',
  'City Bike Stunt está aqui com seu novo episódio! O mapa massivo de Free Riding foi redesenhado. No City Bike Stunt 2, você pode melhorar motocicletas na "Garagem" e mudar seus designs. Para todas essas melhorias você precisará coletar diamantes no mapa "Free Riding".',
  'Jogador 1: Mover SETAS, Nitro N, Câmera C. Jogador 2: Mover WASD, Nitro T, Câmera Q',
  'https://html5.gamemonetize.com/ja1pna4vrn2csmtjofiq195zi1yoj292/',
  'Corrida',
  '3D, Coletando, Direção, Motocicleta, Acrobacias',
  'https://img.gamemonetize.com/ja1pna4vrn2csmtjofiq195zi1yoj292/512x384.jpg',
  800,
  450,
  0,
  0,
  6
),
(
  'teste-do-trator',
  'Teste do Trator',
  'Dirija um trator e se prepare para uma corrida off-road maluca. Tente passar por todos os obstáculos e armadilhas mantendo o trator equilibrado.',
  'Desktop: setas ou WASD para dirigir o trator. Mobile: Use botões na tela para dirigir',
  'https://html5.gamemonetize.com/i7w17r4iadej099cqmsm6utorjxjrv59/',
  'Corrida',
  'Carro, HTML5, Mobile, Obstáculo, Caminhão',
  'https://img.gamemonetize.com/i7w17r4iadej099cqmsm6utorjxjrv59/512x384.jpg',
  800,
  450,
  0,
  0,
  6
),
(
  'acrobacias-grande-cidade',
  'Acrobacias da Grande Cidade',
  'Em uma Grande Cidade, uma aventura muito longa de acrobacias e corridas está começando com o jogo Grand City Stunts! Este jogo não consiste apenas de acrobacias, mas também consiste de corridas nas quais você pode jogar sozinho ou com dois jogadores.',
  'Jogador 1: Mover WASD, Nitro F, Olhar para trás T, Respawn R, Freio de mão ESPAÇO. Jogador 2: Mover SETAS, Nitro K, Respawn O, Olhar para trás L, Freio de mão RIGHT-SHIFT',
  'https://html5.gamemonetize.com/ehni1mj8vzyzv4usr03qm5obdlv974sl/',
  'Corrida',
  '2 Jogadores, Jogos 2 Jogadores, Meninos, Maluco, Corrida, Racing, Acrobacias',
  'https://img.gamemonetize.com/ehni1mj8vzyzv4usr03qm5obdlv974sl/512x384.jpg',
  800,
  450,
  0,
  0,
  6
),
(
  'acrobacia-drift-derby-urbano',
  'Acrobacia e Drift Derby Urbano',
  'Você está pronto para desfrutar da direção de carro suprema? Jogo de carro de acrobacia cheio de diversão e entretenimento com diversão casual e também níveis desafiadores. Execute acrobacias e colete moedas para ganhar dinheiro para desbloquear novos veículos!',
  'Setas para Dirigir, Espaço para Freio, F para NITRO, C para mudar a câmera, Esc ou Tab para pausar',
  'https://html5.gamemonetize.com/g1pdb30jmob4f5pf3xadcsycl8b7ubsa/',
  'Corrida',
  '1 Jogador, Jogos 3D, drift, kiz10, Corrida, Racing, Acrobacias',
  'https://img.gamemonetize.com/g1pdb30jmob4f5pf3xadcsycl8b7ubsa/512x384.jpg',
  750,
  548,
  0,
  0,
  6
),
(
  'msk-squid-game-acrobacias-moto',
  'MSK Squid Game Acrobacias de Motocicleta',
  'Estou convocando o melhor motociclista para organizar as motos de corrida enquanto nestes jogos grátis para correr online e offline. Enfrente jogadores determinados de moto, como seguidores de jogos de moto e jogadores de corrida de moto.',
  'Dirija rápido e colete todas as moedas, termine de coletar moedas antes que o tempo acabe. Tab - Menu, teclas SETAS ou WASD para dirigir a moto, tecla ESPAÇO para freio de mão, C',
  'https://html5.gamemonetize.com/5kg2dgxtdg3lw9ztnn4sk8i87s03ofxe/',
  'Corrida',
  '.io, Jogos .io, 1 Jogador, Jogos 3D, Ação, Melhor, Moto, Maluco, Direção, Jogo, Jogos, Moto, Motocicleta, Sim, Simulação, Acrobacias',
  'https://img.gamemonetize.com/5kg2dgxtdg3lw9ztnn4sk8i87s03ofxe/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'lenda-do-asfalto',
  'Lenda do Asfalto',
  'Aqui está um jogo de simulação de direção de carro com elementos de corrida 3D para fãs de Driving-Game. Você tem a chance de dirigir vários tipos de carros esportivos famosos no jogo. Tente completar mais missões para ganhar seus veículos favoritos na garagem!',
  'WASD para mover o carro',
  'https://html5.gamemonetize.com/0ihjp7bxr2qaz2ug625lkp5v333nkwxj/',
  'Corrida',
  '3D, Carro, Direção, Corrida, Simulação',
  'https://img.gamemonetize.com/0ihjp7bxr2qaz2ug625lkp5v333nkwxj/512x384.jpg',
  1334,
  750,
  0,
  0,
  6
),
(
  'aventura-motocicleta-sonic',
  'Aventura de Motocicleta do Sonic',
  'Sonic é um pequeno ouriço azul que praticamente não tem medo de nada e está corajosamente pronto para enfrentar quaisquer perigos que encontramos com ele na continuação de muitas aventuras, às vezes tão perigosas que parecia não haver saída.',
  'Use o teclado ou toque na tela para controlar o sonic',
  'https://html5.gamemonetize.com/2a02uzmwvubpz918we9nhno35oosi3bl/',
  'Corrida',
  'Animal, Anime, Arcade, Desenho Animado, Cartoon Network, Moto, Motocicleta, Corrida, Racing',
  'https://img.gamemonetize.com/2a02uzmwvubpz918we9nhno35oosi3bl/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'corrida-punk-dupla-2',
  'Corrida Punk Dupla 2',
  'A série Two Punk Racing continua com o segundo episódio do jogo. Compita contra rivais, colete recompensas e compre carros novos ou melhore seu carro! Há 3 modos no jogo. Corra contra rivais, corrida de 2 jogadores e colete recompensas no mapa livre enorme!',
  'Jogador 1: Mover SETAS, Nitro N, Olhar para Trás B. Jogador 2: Mover WASD, Nitro T, Olhar para Trás C, Reiniciar Nível R',
  'https://html5.gamemonetize.com/fyq1rojlql5ws1v5xt83qn8ark19ng92/',
  'Corrida',
  '2 Jogadores, Jogos 2 Jogadores, Jogos 3D, Arcade, Menino, Carro, Coletando, Acrobacias',
  'https://img.gamemonetize.com/fyq1rojlql5ws1v5xt83qn8ark19ng92/512x384.jpg',
  800,
  450,
  0,
  0,
  6
),
(
  'homem-aranha-amigos-incriveis-balanco',
  'Homem-Aranha e Amigos Incríveis: Balanço em Ação!',
  'Três Pessoas-Aranha diferentes estão agora se unindo para uma missão onde vão balançar por Nova York e cuidar de problemas e bandidos, uma experiência que temos o prazer de apresentar a todos vocês agora e aqui!',
  'Use a barra de espaço',
  'https://html5.gamemonetize.com/h74o20btk721joo9xpqg4lhjlmw0spso/',
  'Corrida',
  'Ação, Aventura, H5, Corrida, Homem-Aranha',
  'https://img.gamemonetize.com/h74o20btk721joo9xpqg4lhjlmw0spso/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'direcao-carro-acrobacia-darkside-3d',
  'Direção de Carro de Acrobacia Darkside 3D',
  'Bem-vindo ao mundo dos jogos de acrobacias de carro! A noite chegou e seus supercarros estão esperando. Desfrute da corrida através de diferentes pistas extremas no alto do céu, mas cuidado e não caia fora da pista.',
  'Dirigir SETAS, Nitro F, Freio de mão ESPAÇO, Mudar Câmera C',
  'https://html5.gamemonetize.com/5xbagybtvfgb02pswmdqbfsd74jxjv6f/',
  'Corrida',
  '1 Jogador, 3D, Jogos 3D, Android, Carro, Carros, Maluco, Direção, HTML5, Mobile, Corrida, Habilidade, Acrobacias, Supercarros, Unity3D, WebGL',
  'https://img.gamemonetize.com/5xbagybtvfgb02pswmdqbfsd74jxjv6f/512x384.jpg',
  900,
  600,
  0,
  0,
  6
),
(
  'dirigir-carro-acorrentado-3d',
  'Dirigir Carro Acorrentado 3D',
  'Chained Cars 3D é um simulador de corrida de veículos em tempo real que tem uma nova direção de feixe rápido, bem como uma rampa única. É seu trabalho manter sua velocidade sob controle neste jogo insano de corrida offroad de ônibus versus Prado Jeep.',
  'Use WASD para dirigir',
  'https://html5.gamemonetize.com/7paqux1px21azi1jgkni50xld4dpfkjh/',
  'Corrida',
  'Carro, Carros, Direção, Corrida, Supercarros, Unity3D, WebGL',
  'https://img.gamemonetize.com/7paqux1px21azi1jgkni50xld4dpfkjh/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'acrobacia-carro-voador-5',
  'Acrobacia de Carro Voador 5',
  'O jogo Fly Car Stunt 5 veio com grandes atualizações. Nova Cidade Espacial futurística e 6 novos carros voadores originais estão neste jogo. Toda nova física fornece muito melhor controle do veículo no ar!',
  'Jogador 1: Mover SETAS, Nitro N, Olhar para Trás B. Jogador 2: Mover WASD, Nitro T, Olhar para Trás C, Reiniciar Nível R',
  'https://html5.gamemonetize.com/mc1a5fs2osaqbi4z569d2yryilex14xn/',
  'Corrida',
  '1 Jogador, 2 Jogadores, Jogos 2 Jogadores, Jogos 3D, Aeronave, Carro, Voo, Espaço, Nave Espacial',
  'https://img.gamemonetize.com/mc1a5fs2osaqbi4z569d2yryilex14xn/512x384.jpg',
  800,
  500,
  0,
  0,
  6
),
(
  'acrobacia-moto-porto',
  'Acrobacia de Moto no Porto',
  'A série Bike Stunt continua com o Mapa do Porto. É hora de mostrar suas habilidades de acrobacia em um Porto enorme! Você tem que andar em uma estrada feita de contêineres de transporte. Mas, não é tão fácil quanto parece; há várias armadilhas na estrada.',
  'Jogador 1: Mover SETAS, Nitro N, Câmera C. Jogador 2: Mover WASD, Nitro T, Câmera Q, Reiniciar Nível R',
  'https://html5.gamemonetize.com/lbwkhqasq8c6kemsshnwnyf8wsdfp8fa/',
  'Corrida',
  'Jogos 2 Jogadores, 3D, Jogos 3D, Ação, Moto, Motocicleta, Habilidade, Acrobacias',
  'https://img.gamemonetize.com/lbwkhqasq8c6kemsshnwnyf8wsdfp8fa/512x384.jpg',
  800,
  450,
  0,
  0,
  6
),
(
  'corrida-carro-real-pro',
  'Corrida de Carro Real Pro',
  'Real Car Pro Racing é um jogo de direção de carro 3D com ótimos gráficos e apresenta 15 carros esportivos e 36 pistas de corrida. Real Car Pro Racing tem um sistema de compra e desenvolvimento de carros.',
  'Mover SETAS - WASD, Nitro N, Câmera C, Freio de Mão ESPAÇO',
  'https://html5.gamemonetize.com/rfk8dd79oidw9ikyn2zk9ml3t8nxnufv/',
  'Corrida',
  '3D, Melhor, Carro, drifting, Direção, voar, Hot, Corrida, Acrobacias, Supercarros',
  'https://img.gamemonetize.com/rfk8dd79oidw9ikyn2zk9ml3t8nxnufv/512x384.jpg',
  800,
  450,
  0,
  0,
  6
),
(
  'subway-surfers-zurique',
  'Subway Surfers Zurich',
  'Subway Surfers World Tour: Zurich 2020 é a centésima vigésima primeira atualização do Subway Surfers e a centésima décima quinta parcela da série World Tour. Esta edição inclui o retorno de Hugo como prêmio da Season Hunt.',
  'Controle no jogo Subway Surfers Zurich no computador é feito usando as setas, espaço - para ativar o skate. O objetivo do jogo é o herói correr o mais longe possível superando obstáculos',
  'https://html5.gamemonetize.com/lhpdj67fzrlgqcaelzd4yqdzyvsgvi7h/',
  'Corrida',
  'Ação, Aventura, H5, Hot, HTML, HTML5, Hypercasual, pular, Pulando, Corrida, correr, correndo, subway, Subway Surfers',
  'https://img.gamemonetize.com/lhpdj67fzrlgqcaelzd4yqdzyvsgvi7h/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'simulador-direcao-caminhao-bombeiros',
  'Simulador de Direção de Caminhão de Bombeiros Real',
  'Quando você está jogando jogos de caminhão de bombeiros, seu veículo será o veículo mais vital que você terá que empregar para terminar sua missão com sucesso. Seu caminhão deve, portanto, estar bem preparado para emergências.',
  'WASD dirigir, ESPAÇO FREIO',
  'https://html5.gamemonetize.com/hevkmhtk4azgro9vkz6slj6d4ulzz63q/',
  'Corrida',
  'Direção, Caminhão, Unity3D, WebGL',
  'https://img.gamemonetize.com/hevkmhtk4azgro9vkz6slj6d4ulzz63q/512x384.jpg',
  800,
  600,
  0,
  0,
  6
),
(
  'super-direcao',
  'Super Direção',
  'Super Drive apresenta gráficos incríveis e muitos supercarros para dirigir pela grande cidade cheia de pedestres, dirija o mais rápido que puder e tente executar diferentes acrobacias no seu caminho.',
  'WASD - Dirigir, Espaço - Freio, C - Mudar câmera',
  'https://html5.gamemonetize.com/uka0g9xcqkba4ymmbn4kto9z0bgvpdyb/',
  'Corrida',
  '1 Jogador, 3D, Jogos 3D, Carro, Carros, Direção, Corrida, Racing, Simulação, Simulador, Supercarros, Unity3D, WebGL',
  'https://img.gamemonetize.com/uka0g9xcqkba4ymmbn4kto9z0bgvpdyb/512x384.jpg',
  960,
  600,
  0,
  0,
  6
),
(
  'acrobacias-duas-motos',
  'Acrobacias de Duas Motos',
  'Em Two Bike Stunts, motocicletas incríveis estão no palco! Você pode andar em 8 motocicletas diferentes em 2 mapas gigantes. A garagem vem cheia com 3 motos bloqueadas. Colete as moedas no mapa e desbloqueie motocicletas bloqueadas!',
  'Jogador 1: Mover SETAS, Nitro N, Câmera C. Jogador 2: Mover WASD, Nitro T, Câmera Q, Reiniciar Nível R',
  'https://html5.gamemonetize.com/vzvmcb4xxgrdjxvcwh3ne1bncclr05rv/',
  'Corrida',
  'Jogos 2 Jogadores, 3D, Jogos 3D, Ação, Maluco, Motocicleta, Corrida, Habilidade, Acrobacias',
  'https://img.gamemonetize.com/vzvmcb4xxgrdjxvcwh3ne1bncclr05rv/512x384.jpg',
  800,
  450,
  0,
  0,
  6
); 