-- Migration 026: Adicionar jogos de puzzle na página 7
-- Criado: 2024
-- Descrição: Adiciona 35 jogos de puzzle traduzidos para português na página 7

INSERT INTO games (
  id, title, description, instructions, url, category, tags, thumb, width, height, views, likes, page
) VALUES 
(
  'heroi-resgate-quebra-cabeca',
  'Herói Resgate Quebra-cabeça',
  'Você gosta de jogos de resgate? Claro, eles são ótimos. Ajude o herói resgate a salvar a princesa e conseguir o tesouro no novo jogo de guerras heroicas - Herói Resgate. Atire nos bastões para salvar a princesa, matar os goblins, conseguir um tesouro... Você se tornará um herói rico neste jogo de resgate da cidade.',
  'Controle com mouse',
  'https://html5.gamemonetize.com/3596x93682lmj4cn7mrtldmfhviig7jj/',
  'Puzzle',
  'Ação, Meninos, Diversão, Meninas, HTML5, Lógica, Puzzle',
  'https://img.gamemonetize.com/3596x93682lmj4cn7mrtldmfhviig7jj/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'bolas-do-amor-2d',
  'Bolas do Amor 2D',
  'É hora de usar seu cérebro e encontrar uma maneira de bater as bolas! A regra é fácil, apenas desenhe linhas ou formas para bater as bolas, você precisará de sua sabedoria e imaginação.',
  'Use o mouse para jogar',
  'https://html5.gamemonetize.com/1l6pgl750zi41o2cktmkmr71dntshaej/',
  'Puzzle',
  'Aventura, Arcade, Bola, Amor, Puzzle',
  'https://img.gamemonetize.com/1l6pgl750zi41o2cktmkmr71dntshaej/512x384.jpg',
  900,
  600,
  0,
  0,
  7
),
(
  'copo-feliz-encher-copo-desenhar-linhas',
  'Copo Feliz: Encher o Copo Desenhando Linhas',
  'Simplesmente enchendo o Copo Feliz com Desenhar Linhas, Faça um Corvo Feliz. Tente encontrar a melhor maneira de completar cada nível. Você pode criar sua própria solução, então seja criativo e não tenha medo de pensar fora da caixa!',
  'Desenhe linhas com clique esquerdo do mouse',
  'https://html5.gamemonetize.com/dayksem3hjbea9vsbklh6wqi213w9121/',
  'Puzzle',
  'Meninos, Clique, Desenhar, Jogos, Meninas, HTML, HTML5',
  'https://img.gamemonetize.com/dayksem3hjbea9vsbklh6wqi213w9121/512x384.jpg',
  600,
  900,
  0,
  0,
  7
),
(
  'pou-online',
  'Pou Online',
  'Você tem o que é preciso para cuidar do seu próprio animal de estimação alienígena? Alimente e cuide do Pou.',
  'Controle com mouse',
  'https://html5.gamemonetize.com/jyeazqa0x7ym5xcq22g9mgv74s5tift1/',
  'Puzzle',
  'Meninos, Meninas, HTML5',
  'https://img.gamemonetize.com/jyeazqa0x7ym5xcq22g9mgv74s5tift1/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'salvar-garota-epico',
  'Salvar a Garota Épico',
  'Você precisa resgatar a garota no jogo e ajudá-la a evitar todos os tipos de perigos. Encontre uma saída. Cada nível tem diferentes desafios e perigos. A segurança das garotas precisa da sua proteção. Você pode precisar desafiar muitas vezes. Não desanime e tente com força. Há lojas de decoração de quarto e lojas de roupas no jogo para tornar sua jornada de salvação estilosa.',
  'Toque para jogar',
  'https://html5.gamemonetize.com/9ytk0fr25q0r20zbb524x4bxcvpnm5gw/',
  'Puzzle',
  'Android, Menino, Menina, H5, HTML, HTML5, Hypercasual, Interativo, Crianças, Lógica, Lógico, Mobile, Online, Puzzle',
  'https://img.gamemonetize.com/9ytk0fr25q0r20zbb524x4bxcvpnm5gw/512x384.jpg',
  750,
  1334,
  0,
  0,
  7
),
(
  'puxar-ele-para-fora-online',
  'Puxar Ele Para Fora Online',
  'O caçador começa sua jornada pelo tesouro, mas os quebra-cabeças na frente do caçador o prenderam. O que você precisa fazer é desenhar o bastão na ordem certa, para que o caçador possa levar o tesouro escondido com segurança.',
  'Use o mouse para jogar',
  'https://html5.gamemonetize.com/mhqkw9a80at8pnqcc6jj2uiii5chfai1/',
  'Puzzle',
  'Aventura, Meninos, Meninas, Lógica, Lógico, Puzzle',
  'https://img.gamemonetize.com/mhqkw9a80at8pnqcc6jj2uiii5chfai1/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'jogo-lula-escondido',
  'Jogo da Lula Escondido',
  'Jogo da Lula Escondido é um jogo online gratuito de habilidade e objetos escondidos. Encontre os objetos escondidos nas imagens especificadas. Cada nível tem 10 objetos escondidos. Há 6 níveis no total. O tempo é limitado, então seja rápido e encontre todos os objetos escondidos antes que o tempo acabe. Clicar no lugar errado várias vezes reduz o tempo em 5 segundos adicionais. Então, se você estiver pronto, comece o jogo e divirta-se!',
  'Use seu mouse para jogar ou toque na tela',
  'https://html5.gamemonetize.com/h8x9sv6r7uqxuvjfs7hffm72jjl62t8l/',
  'Puzzle',
  'Diversão, Escondido, HTML5, Crianças, Mobile, Puzzle',
  'https://img.gamemonetize.com/h8x9sv6r7uqxuvjfs7hffm72jjl62t8l/512x384.jpg',
  1280,
  720,
  0,
  0,
  7
),
(
  'candy-crush-saga-rei',
  'Candy Crush Saga Rei',
  'Planeje seus movimentos combinando 3 ou mais doces em uma fileira, usando boosters sabiamente para superar esses quebra-cabeças extra pegajosos! Exploda o chocolate e colete doces doces em milhares de níveis, garantido para deixar você com vontade de mais!',
  'Comece a jogar Candy Crush Saga hoje movendo doces doces',
  'https://html5.gamemonetize.com/ushitaltif0ig5by3w54p4cy9sd3yptt/',
  'Puzzle',
  'Bomba, Doce, Fruta, Frutas, Hypercasual, Match 3, Match-3, Match3, Combinação, Puzzle, Atirar, Atirador, Tiro',
  'https://img.gamemonetize.com/ushitaltif0ig5by3w54p4cy9sd3yptt/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'jogo-lula-doce-dalgona-3d',
  'Jogo da Lula Doce Dalgona 3D',
  'Com o jogo Jogo da Lula Doce Dalgona, você deve remover as formas nos moldes de doce com a ajuda de uma agulha. Você tem que ser muito cuidadoso, pois o molde de doce é duro e quebradiço. Se você quebrar o doce, será eliminado do jogo! Você tem que verificar o "Medidor de Rachadura" para remover cuidadosamente o doce. Não clique no botão periodicamente. Se o "Medidor de Rachadura" atingir o nível vermelho, o doce será quebrado. Você também deve prestar atenção ao tempo. Se você não conseguir remover a forma no tempo dado, será eliminado do jogo.',
  'Clique do mouse ou Espaço',
  'https://html5.gamemonetize.com/vbf8hbv945lzatzyrth3te7i2lt8ddfi/',
  'Puzzle',
  '3D, Arcade, Melhor, Doce, Casual, Clique, Clicker, Engraçado, Hypercasual, Crianças, Puzzle, Escola, Habilidades, WebGL',
  'https://img.gamemonetize.com/vbf8hbv945lzatzyrth3te7i2lt8ddfi/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'bentley-supersports-conversivel-quebra-cabeca',
  'Bentley Supersports Conversível Quebra-cabeça',
  'Jogue com 9 imagens neste jogo perfeito de quebra-cabeça: Bentley Supersports Conversível Quebra-cabeça. Todas as imagens são com o carro - Bentley Supersports Conversível. Resolva todos os quebra-cabeças e mantenha seu cérebro afiado. Você tem quatro modos para cada imagem: 16 peças, 36 peças, 64 peças e 100 peças. Divirta-se!',
  'Use o mouse para jogar este jogo HTML5 de carros',
  'https://html5.gamemonetize.com/nlqahluv3e60h9ry3kac0svcx92qubox/',
  'Puzzle',
  'Carro, Carros, HTML5, Quebra-cabeça, Mobile, Supercarros',
  'https://img.gamemonetize.com/nlqahluv3e60h9ry3kac0svcx92qubox/512x384.jpg',
  1920,
  1080,
  0,
  0,
  7
),
(
  'matematica-correta',
  'Matemática Correta',
  'Matemática Correta é um jogo matemático onde você pode testar seu conhecimento em adição e subtração de números. Você receberá três respostas para a pergunta matemática e precisará clicar no resultado correto. O tempo para pensar sobre o resultado é curto. Seja rápido e preciso. Ganhe o máximo de pontos que puder neste jogo cerebral de matemática.',
  'Toque na tela para jogar este jogo',
  'https://html5.gamemonetize.com/nk8ecy4vj5jc8u7271mx9v9aptpbdn41/',
  'Puzzle',
  'Cérebro, Clicker, Crianças, Matemática, Número, Puzzle',
  'https://img.gamemonetize.com/nk8ecy4vj5jc8u7271mx9v9aptpbdn41/512x384.jpg',
  480,
  800,
  0,
  0,
  7
),
(
  'joaninha-quebra-cabeca-colecao',
  'Joaninha Quebra-cabeça Coleção',
  'O jogo online "Quebra-cabeças da Joaninha" é uma grande oportunidade para meninas que são fãs de desenhos animados se divertirem coletando fotos com sua heroína favorita. A Joaninha mantinha um álbum de fotos em casa com uma seleção de fotografias sobre suas façanhas com Super-Gato. E então um dia Gavião-Homem, para prejudicar seu inimigo, subiu na casa da Joaninha e cortou todas as fotos em pedaços. A joaninha está muito chateada e espera que as meninas consigam restaurá-las. No total, na coleção do jogo, as crianças encontrarão 12 quebra-cabeças, que retratam o famoso casal - Joaninha e Super Gato.',
  'mouse',
  'https://html5.gamemonetize.com/07cyslhfnl55xgtrteakwxg366q2rg5s/',
  'Puzzle',
  'Desenho Animado, Quebra-cabeça, Joaninha',
  'https://img.gamemonetize.com/07cyslhfnl55xgtrteakwxg366q2rg5s/512x384.jpg',
  900,
  600,
  0,
  0,
  7
),
(
  'zumba-mania',
  'Zumba Mania',
  'Melhore no tiro de mármore e tente completar todos os níveis com três estrelas em cada nível. Este jogo de mármore é fácil de jogar e viciante ao mesmo tempo.',
  'Toque para atirar. Combine 3 ou mais mármores da mesma cor para eliminá-los. Destrua todos os mármores na corrente antes que atinja o fim. Toque no sapo para trocar entre o mármore atual e o próximo. Use power-ups para limpar o tabuleiro mais rápido',
  'https://html5.gamemonetize.com/03yns70hfztn5480rjr3pfrg55z22e23/',
  'Puzzle',
  'Bola, HTML5, Tiro, Zuma',
  'https://img.gamemonetize.com/03yns70hfztn5480rjr3pfrg55z22e23/512x384.jpg',
  600,
  800,
  0,
  0,
  7
),
(
  'jogo-lula-match3',
  'Jogo da Lula Match3',
  'Bem-vindo à nova parte do famoso torneio de sobrevivência "Jogo da Lula", no qual você encontrará alguns dos testes mais brutais demonstrados na série de TV sul-coreana de mesmo nome!',
  'Use o mouse ou toque na tela',
  'https://html5.gamemonetize.com/t02lif7gkyvo6425j8d0jg0sgqqa9ezw/',
  'Puzzle',
  'HTML5, Match 3, Mobile',
  'https://img.gamemonetize.com/t02lif7gkyvo6425j8d0jg0sgqqa9ezw/512x384.jpg',
  1280,
  720,
  0,
  0,
  7
),
(
  'cruzamentos',
  'Cruzamentos',
  'Preencha todos os espaços vazios com linhas para completar o nível. Use seu dedo ou mouse para mover as linhas para que o valor da linha seja zero. Mire inteligentemente! Passe pelos níveis, ficará mais difícil e mais interessante.',
  'Toque no mouse',
  'https://html5.gamemonetize.com/56cw62qu259b0ar8c3xjkf2eitpeospe/',
  'Puzzle',
  '1 Jogador, Cérebro, Ponte',
  'https://img.gamemonetize.com/56cw62qu259b0ar8c3xjkf2eitpeospe/512x384.jpg',
  1080,
  1920,
  0,
  0,
  7
),
(
  'zuma-tribal',
  'Zuma Tribal',
  'No jogo, chegamos a um mundo de totem misterioso e antigo, mas parece estar amaldiçoado aqui. Precisamos lançar mármores para conectar três ou mais mármores idênticos para eliminá-lo. A maldição desaparecerá apenas depois que todos os mármores forem eliminados. Vamos tentar juntos!',
  'Clique para jogar',
  'https://html5.gamemonetize.com/63lh22skhzyp4znidpgtt47qhn4rpatb/',
  'Puzzle',
  'Clicker, Hypercasual, Puzzle, Zuma',
  'https://img.gamemonetize.com/63lh22skhzyp4znidpgtt47qhn4rpatb/512x384.jpg',
  642,
  1281,
  0,
  0,
  7
),
(
  'irmao-panda',
  'Irmão Panda',
  'Irmãos panda mostram kung fu real, venha desafiar sua mão direita e mão esquerda.',
  'Clique para jogar',
  'https://html5.gamemonetize.com/nuxb2k2as5s7a96dg137kvjykkk54mvr/',
  'Puzzle',
  'Hypercasual, Puzzle',
  'https://img.gamemonetize.com/nuxb2k2as5s7a96dg137kvjykkk54mvr/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'mesa-giratoria-colorida',
  'Mesa Giratória Colorida',
  'Este é um jogo de entretenimento com cores ricas e frescas. A operação do jogo é simples e cheia de diversão. É hora de testar sua visão e velocidade das mãos. Apresse-se e compita com seus amigos.',
  'Clique para jogar',
  'https://html5.gamemonetize.com/9f2npv6tegdd3jl8w1fwu76hks9o1cwb/',
  'Puzzle',
  'Hypercasual, Puzzle',
  'https://img.gamemonetize.com/9f2npv6tegdd3jl8w1fwu76hks9o1cwb/512x384.jpg',
  640,
  1136,
  0,
  0,
  7
),
(
  'jogo-lula-desafio-dalgona',
  'Jogo da Lula Desafio Dalgona',
  'Você está pronto para um jogo de quebra-cabeça divertido e popular? Com o jogo Jogo da Lula Desafio do Açúcar Dalgona, você tem que usar uma agulha para remover a forma que escolheu dos moldes de doce. Como o molde de doce é duro e frágil, você deve remover cuidadosamente a forma. Se você quebrar o doce, é fim de jogo! Você tem que clicar no botão periodicamente para remover o doce sem quebrá-lo. Se você clicar muito e definir o "Medidor de Rachadura" para o nível vermelho, o doce quebrará. Além disso, se você não remover o doce dentro do tempo dado, o jogo acaba.',
  'Clique do mouse ou Toque',
  'https://html5.gamemonetize.com/prgiyhh6f1ueu7mvyvabtkal9rz557gj/',
  'Puzzle',
  '3D, Arcade, Melhor, Doce, Casual, Clique, Clicker, Engraçado, Hypercasual, Crianças, Puzzle, Escola, Habilidades, WebGL',
  'https://img.gamemonetize.com/prgiyhh6f1ueu7mvyvabtkal9rz557gj/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'paciencia-fairway-jogo-cartas-classico',
  'Paciência Fairway - Jogo de Cartas Clássico',
  'Um jogo de cartas de paciência simples, mas divertido. Tente ganhar o máximo de rodadas de paciência de golfe que puder removendo todas as cartas da grade. Baseado na jogabilidade de paciência, ajudará você a manter seu cérebro inteligente e afiado. Jogue agora!',
  'Mouse',
  'https://html5.gamemonetize.com/k2ry2h1iqplf0qqnl2qw33fbb09fyugi/',
  'Puzzle',
  'Carta, Casual, Clássico, Golfe, Poker, Puzzle, Paciência',
  'https://img.gamemonetize.com/k2ry2h1iqplf0qqnl2qw33fbb09fyugi/512x384.jpg',
  1152,
  648,
  0,
  0,
  7
),
(
  'jogo-lula-quebra-cabeca',
  'Jogo da Lula Quebra-cabeça',
  'Você se encontrará em um tempo misterioso e mágico neste emocionante jogo de quebra-cabeça do Jogo da Lula. Divirta-se montando quebra-cabeças com gráficos bonitos e ricos. Cada quebra-cabeça é uma nova emoção, experimente também. Não se esqueça de experimentar a categoria "Nossos Jogos". Todos eles foram desenvolvidos para você. Continue fazendo jogos divertidos e siga a categoria de jogos. Divirta-se!',
  'Clique Esquerdo',
  'https://html5.gamemonetize.com/inctjl5li17iii4rv9edu2sv4wgeuxow/',
  'Puzzle',
  'HTML5, Crianças, Habilidade',
  'https://img.gamemonetize.com/inctjl5li17iii4rv9edu2sv4wgeuxow/512x384.jpg',
  800,
  450,
  0,
  0,
  7
),
(
  'lula-doce-dalgona',
  'Lula Doce Dalgona',
  'Você está pronto para jogar um jogo de quebra-cabeça popular e divertido? Você deve usar uma agulha para remover a forma desejada dos moldes de doce no jogo Lula Doce Dalgona. Você deve remover suavemente o molde de doce, pois é duro e quebradiço. É fim de jogo se você quebrar o doce! Para extrair o doce sem quebrá-lo, você deve clicar no botão regularmente. Os doces se quebrarão se você clicar muito e colocar o "Medidor de Rachadura" no nível vermelho. O jogo também termina se você não remover o doce dentro do limite de tempo.',
  'Clique do mouse ou Toque',
  'https://html5.gamemonetize.com/lmcgtvpxt3ur3o9b544lvj7djkayz62a/',
  'Puzzle',
  '3D, Arcade, Melhor, Doce, Casual, Clique, Engraçado, Hypercasual, Crianças, Puzzle, Escola, Habilidades, WebGL',
  'https://img.gamemonetize.com/lmcgtvpxt3ur3o9b544lvj7djkayz62a/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'guerreiros-prisao-stickman',
  'Guerreiros da Prisão Stickman',
  'Um jogo emocionante sobre um stickman escapando da prisão. Um stickman é incriminado e preso, mas ele nunca desiste e planeja a auto-salvação. Persevere, dia após dia, ano após ano. A esperança pode libertá-lo. Finalmente, ele pode respirar a liberdade.',
  'Corte o bloco, derrube-o no chão e você pode pisar no bloco para sair da floresta',
  'https://html5.gamemonetize.com/ef5utfw1l3drq2dfojdsef2cc0clga6t/',
  'Puzzle',
  '1 Jogador, 2D, Aventura, Arcade, Prisão, Puzzle, Stickman',
  'https://img.gamemonetize.com/ef5utfw1l3drq2dfojdsef2cc0clga6t/512x384.jpg',
  640,
  960,
  0,
  0,
  7
),
(
  'jogo-lula-quebra-cabeca-jigsaw',
  'Jogo da Lula Quebra-cabeça Jigsaw',
  'Jogo da Lula Quebra-cabeça Jigsaw é um jogo de quebra-cabeça online divertido. Arraste as peças para a posição certa usando o mouse. Resolver quebra-cabeças é relaxante, gratificante e mantém seu cérebro afiado. Você precisa gastar $1000 para poder comprar uma das seguintes imagens. Você tem três modos para cada imagem, dos quais o modo mais difícil traz mais dinheiro. Você tem um total de 10 imagens.',
  'Use o mouse ou toque na tela',
  'https://html5.gamemonetize.com/mhma77nm8f0r6a1d0if7a5qiyxzl13gp/',
  'Puzzle',
  '1 Jogador, Ação, Diversão, Jogo, Quebra-cabeça, Lógica, Mobile, Habilidade, Habilidades',
  'https://img.gamemonetize.com/mhma77nm8f0r6a1d0if7a5qiyxzl13gp/512x384.jpg',
  1280,
  720,
  0,
  0,
  7
),
(
  'futebol-gravidade',
  'Futebol Gravidade',
  'Futebol gravidade é um jogo muito legal e de fãs.',
  'Aponte e clique na caixa',
  'https://html5.gamemonetize.com/c9mvw808c7show579eyvwnl4vk3712g6/',
  'Puzzle',
  'Arcade, Casual, Clique, Hypercasual, Física, Apontar e Clicar, Puzzle',
  'https://img.gamemonetize.com/c9mvw808c7show579eyvwnl4vk3712g6/512x384.jpg',
  854,
  560,
  0,
  0,
  7
),
(
  'monopoly-online',
  'Monopoly Online',
  'Jogo online MONOPOLY. É o jogo clássico de Monopoly que você conhece e ama com um toque online. Reviva uma das séries de jogos de tabuleiro mais icônicas de todos os tempos, o jogo clássico de negócios Monopoly agora online.',
  'Clique esquerdo para jogar o jogo',
  'https://html5.gamemonetize.com/rb9b7ctnmy1rjphxzuwlmy8c4b7mw9po/',
  'Puzzle',
  '2 Jogadores, 3D, Jogos 3D, Tabuleiro, Meninos, Menina, Meninas, HTML5, Lógica, Lógico, Multiplayer, Puzzle',
  'https://img.gamemonetize.com/rb9b7ctnmy1rjphxzuwlmy8c4b7mw9po/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'laboratorio-alquimista-esmagar-joias',
  'Laboratório do Alquimista - Esmagar Joias',
  'Bem-vindo ao mundo do Laboratório Match3 de Alquimia. Faça uma combinação simples de 3 elementos de Joia para limpá-los e Combine 4 ou 5 fichas para gerar bônus. Combine bônus com gema para ativá-lo, então Combine bônus uns com os outros para gerar pedra filosofal. Explore mais de 100 níveis desafiadores. Divirta-se!',
  'Deslize para combinar gemas coloridas',
  'https://html5.gamemonetize.com/152k8bm16yx6mjq1tq6w1l7vmrh8vz17/',
  'Puzzle',
  'Melhor, Doce, Cor, Quente, Match 3, Match-3, Match3, Puzzle',
  'https://img.gamemonetize.com/152k8bm16yx6mjq1tq6w1l7vmrh8vz17/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'fuga-espaco-entre-nos',
  'Fuga do Espaço Entre Nós',
  'Quão longe o Herói pode correr? Neste jogo de ação você tem que ajudar o Herói a fugir do Vermelho malvado. Pule de asteroide em asteroide, mas cuidado com os quentes. Evite os cometas em chamas. Seja rápido ou o Vermelho malvado vai te pegar.',
  'Esquerda - Pulo Pequeno, Direita - Pulo Grande',
  'https://html5.gamemonetize.com/zkcgcuzfq424y4472zfgf050vgfa15u0/',
  'Puzzle',
  'Fuga, Pokemon, Resgate',
  'https://img.gamemonetize.com/zkcgcuzfq424y4472zfgf050vgfa15u0/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'batalha-mundo-robos',
  'Batalha do Mundo dos Robôs',
  'Monte Robôs e lute no Torneio Épico. Destrua todos os seus inimigos. Só pode haver Um.',
  'Clique para Jogar',
  'https://html5.gamemonetize.com/2yssw05uvpvrjx2w2byhbcwkjr3cqz6s/',
  'Puzzle',
  'Luta, kiz10, Robô',
  'https://img.gamemonetize.com/2yssw05uvpvrjx2w2byhbcwkjr3cqz6s/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'kissy-missy-huggy-wuggy',
  'Kissy Missy e Huggy Wuggy',
  'A aventura de dois corações amorosos no jogo Kissy Missy e Huggy Wuggy. Este é um jogo emocionante para todas as idades. Um análogo do jogo Fogo e Água. Colete todas as gemas, ajudem-se mutuamente pressionando botões, lançando elevadores e caminhem juntos até o final deste caminho difícil. Lembre-se, Kissy Missy pode passar por águas flamejantes, mas reservatórios azuis são mortais para ela. Mas Huggy Wuggy tem o oposto. Tenha um bom jogo e boa sorte!',
  'O jogo consiste em vários níveis de dificuldade variada com os seguintes controles: Smartphone/Tablet - Controle por toque, PC - Mover - setas do teclado, troca de personagem - barra de espaço',
  'https://html5.gamemonetize.com/5v4qslmgoj68kmqyrfr1g0yvn4xn1kz1/',
  'Puzzle',
  '2 Jogadores, Jogos 2 Jogadores, 2D, Melhor, Menino, Meninos, Castelo, Fogo, Engraçado, Jogo, Jogos, Menina, Meninas, Quente, HTML, HTML5, Lógica, Lógico, Amor, Stickman, Super',
  'https://img.gamemonetize.com/5v4qslmgoj68kmqyrfr1g0yvn4xn1kz1/512x384.jpg',
  1920,
  1080,
  0,
  0,
  7
),
(
  'assassino-impostor',
  'Assassino Impostor',
  'Esguire-se pelo nível matando todos os impostores para completar cada estágio. Evite detecção ou é fim de jogo e você terá que tentar novamente neste divertido jogo online temático do Among Us.',
  'Setas para mover, Barra de espaço para atacar ou use controles de toque',
  'https://html5.gamemonetize.com/ua633ralct1mi7pjqsik8svx3z0ke0a8/',
  'Puzzle',
  'Sangue, Matança, Online, Furtividade',
  'https://img.gamemonetize.com/ua633ralct1mi7pjqsik8svx3z0ke0a8/512x384.jpg',
  800,
  600,
  0,
  0,
  7
),
(
  'puxar-pino-resgate',
  'Puxar o Pino Resgate',
  'Puxar o Pino Resgate é um jogo de resgate onde você precisa puxar o pino na ordem certa e resgatar um cara preso. Uma vez falhado, o jovem estará em perigo. Foque mais na sua estratégia e salve-o.',
  'Toque e deslize para mover',
  'https://html5.gamemonetize.com/2d188mmlbr7n8uj9y0w36nm75uusur4w/',
  'Puzzle',
  '3D, Jogos 3D, Aventura, Animal, Menino, Cérebro, Menina, H5, HTML5, Crianças, Lógica, Lógico, Mobile, Online, Plataforma, Puzzle',
  'https://img.gamemonetize.com/2d188mmlbr7n8uj9y0w36nm75uusur4w/512x384.jpg',
  750,
  1334,
  0,
  0,
  7
),
(
  'ford-f100-eluminator-deslizar',
  'Ford F-100 Eluminator Deslizar',
  'Jogue este jogo de quebra-cabeça deslizante do carro - Ford F-100 Eluminator. Inclui 3 imagens e 3 modos (peças 3x3, peças 4x4, peças 5x5) para jogar.',
  'Use o mouse para jogar este jogo HTML5',
  'https://html5.gamemonetize.com/danedschqracnvfocuzlnyahmhrigth0/',
  'Puzzle',
  'Carro, Carros, HTML5, Mobile',
  'https://img.gamemonetize.com/danedschqracnvfocuzlnyahmhrigth0/512x384.jpg',
  1920,
  1080,
  0,
  0,
  7
); 