-- Migration 035: Adicionar jogos de esportes na página 8
-- Inserir jogos de esportes traduzidos para português

INSERT INTO games (id, title, description, instructions, url, category, tags, thumb, width, height, gameid, page) VALUES
('batalha-de-golfe', 'Batalha de Golfe', 'A melhor batalha de mini golfe! Torne-se o Rei da partida de golfe! O jogo de golfe perfeito para jogadores casuais, jogue online no celular ou PC!', 'Use o mouse para jogar', 'https://html5.gamemonetize.com/w0ij1igcyt8yd96ppelksxcwulp0inye/', 'Sports', '3D, Ação, Meninos, Meninas, Golfe, Esporte, Esportes', 'https://img.gamemonetize.com/w0ij1igcyt8yd96ppelksxcwulp0inye/512x384.jpg', 800, 600, 'w0ij1igcyt8yd96ppelksxcwulp0inye', 8),

('ronaldo-kick-run', 'Ronaldo Kick Run', 'Ronaldo Kick Run. É hora de levar suas habilidades do campo para as pistas neste jogo Ronaldo Kick n Run.', 'Mouse ou toque para jogar em dispositivos desktop ou móveis', 'https://html5.gamemonetize.com/nfi0vtpni37e0u6q9ypi10ramfa58lgv/', 'Sports', 'Futebol, corrida, Subway Surfers', 'https://img.gamemonetize.com/nfi0vtpni37e0u6q9ypi10ramfa58lgv/512x384.jpg', 800, 600, 'nfi0vtpni37e0u6q9ypi10ramfa58lgv', 8),

('euro-2020', 'Euro 2020 (2021)', 'Jogue a edição de chutes livres da Euro 2020, escolha entre 10 das melhores equipes e leve-as à glória do campeonato', 'Mouse ou toque para chutar e defender', 'https://html5.gamemonetize.com/afsdceo148sxpldq92poqda4jnauoe0z/', 'Sports', 'Futebol, HTML5, Futebol, Esportes', 'https://img.gamemonetize.com/afsdceo148sxpldq92poqda4jnauoe0z/512x384.jpg', 960, 600, 'afsdceo148sxpldq92poqda4jnauoe0z', 8),

('estrelas-do-basquete', 'Estrelas do Basquete', 'Enterre muito! Você nunca jogou um esporte assim antes! Sinta a diversão do verdadeiro drible de basquete "reverso". Desafie o mundo e colete todos os troféus!', 'Enterre muito! Você nunca jogou um esporte assim antes! Sinta a diversão do verdadeiro drible de basquete reverso. Desafie o mundo e colete todos os troféus!', 'https://html5.gamemonetize.com/8wl1o0fch6z6d1tz3ottmauzgoyufw1p/', 'Sports', '.io, Jogos .io, Esporte, Esportes', 'https://img.gamemonetize.com/8wl1o0fch6z6d1tz3ottmauzgoyufw1p/512x384.jpg', 1080, 1920, '8wl1o0fch6z6d1tz3ottmauzgoyufw1p', 8),

('desenhar-piloto', 'Desenhar Piloto', 'Desenhe e depois corra! você deve desenhar as rodas primeiro. Certifique-se de desenhar um novo par toda vez, diferentes desafios precisam de formas diversas das rodas. Corra rápido e passe por todos os níveis com sucesso!', 'Desenhe suas rodas para vencer a corrida', 'https://html5.gamemonetize.com/awplu2aw0cubmr6mqa2o6q8euwwa3pdd/', 'Sports', 'Meninos, Desenhar, Corrida, Corrida', 'https://img.gamemonetize.com/awplu2aw0cubmr6mqa2o6q8euwwa3pdd/512x384.jpg', 800, 600, 'awplu2aw0cubmr6mqa2o6q8euwwa3pdd', 8),

('arqueiros-sangrentos', 'Arqueiros Sangrentos', 'Os bonecos palito estão nisso novamente! Desta vez eles estão lutando com arco e flecha e tentando aperfeiçoar suas habilidades de tiro com arco. Você deve provar sua destreza com um arco e tentar ser o lutador mais rápido da cidade.', 'Arraste o botão esquerdo do mouse para trás para mirar, solte para atirar', 'https://html5.gamemonetize.com/plyrpmx3tkun2u8r0ywdhgr0v63ntfni/', 'Sports', '2D, Arcade, Sangue, Casual, Hypercasual, Retrô, Esporte', 'https://img.gamemonetize.com/plyrpmx3tkun2u8r0ywdhgr0v63ntfni/512x384.jpg', 1280, 720, 'plyrpmx3tkun2u8r0ywdhgr0v63ntfni', 8),

('mestre-home-run', 'Mestre Home Run', 'Torne-se o mestre do home run acertando home runs incríveis para fora do parque', 'Clique para balançar ou mire e levante o dedo nos celulares', 'https://html5.gamemonetize.com/vdfwh0z15fnbs4i1v651fri11epzyw1x/', 'Sports', 'Beisebol, Esporte', 'https://img.gamemonetize.com/vdfwh0z15fnbs4i1v651fri11epzyw1x/512x384.jpg', 800, 600, 'vdfwh0z15fnbs4i1v651fri11epzyw1x', 8),

('futebol-io', 'Futebol.io', 'Futebol.io é um jogo io viciante e divertido. Você tem que competir com 3 outros jogadores e eliminá-los para vencer o jogo.', 'Use o mouse ou as setas do teclado para jogar', 'https://html5.gamemonetize.com/cx80i42fx1750j3bfk11laoibldijepw/', 'Sports', '.io, Jogos .io, Futebol, Esporte, Esportes', 'https://img.gamemonetize.com/cx80i42fx1750j3bfk11laoibldijepw/512x384.jpg', 900, 600, 'cx80i42fx1750j3bfk11laoibldijepw', 8),

('moto-maniaco-3', 'Moto Maníaco 3', 'Este é um jogo de bicicleta inclinada que desafiará suas habilidades de trial ao máximo. A competição de trial está configurada na floresta, então esteja pronto para escalar árvores e rochas.', 'Cima ou W, Baixo ou S - Dirigir para frente/trás, Esquerda ou A, Direita ou D - Inclinar esquerda/direita, P - pausar', 'https://html5.gamemonetize.com/ohf41w276nahrogfzpm258zmcxswlvvu/', 'Sports', '2D, Bicicleta, Legal, Moto, Motocicleta, Obstáculo, Física, Corrida, Corrida, Habilidade, Esporte, Esportes, Acrobacias', 'https://img.gamemonetize.com/ohf41w276nahrogfzpm258zmcxswlvvu/512x384.jpg', 800, 600, 'ohf41w276nahrogfzpm258zmcxswlvvu', 8),

('liga-de-bolso-3d', 'Liga de Bolso 3D', 'Liga de Bolso 3D é um jogo divertido de futebol de carros que pode ser jogado por 1 e 2 jogadores. Se quiser, você também pode incluir bots de IA no jogo.', 'Se jogando sozinho: Mover SETAS, Pular ESPAÇO, Girar Duplo ESPAÇO. Se jogando dois jogadores: JOGADOR 1: Mover SETAS, Pular L, Girar Duplo L. JOGADOR 2: Mover W A S D, Pular G, Girar Duplo G', 'https://html5.gamemonetize.com/ckane5lyx4583jknsdh3qs0d6p39gpls/', 'Sports', '2 Jogadores, Jogos 2 Jogadores, 3D, Carro, Dirigir, Futebol, Futebol', 'https://img.gamemonetize.com/ckane5lyx4583jknsdh3qs0d6p39gpls/512x384.jpg', 800, 450, 'ckane5lyx4583jknsdh3qs0d6p39gpls', 8); 