-- Migration 036: Adicionar mais jogos de esportes na página 8 (continuação)
-- Inserir mais jogos de esportes traduzidos para português

INSERT INTO games (id, title, description, instructions, url, category, tags, thumb, width, height, gameid, page) VALUES
('moto-x3m-inverno', 'Moto X3M Inverno', 'Bem-vindo ao especial de inverno deste incrível jogo de acrobacias de moto, Moto X3M 4: Inverno. Dirija sua moto através de pistas desafiadoras cheias de armadilhas mortais.', 'Use as setas do teclado para controlar', 'https://html5.gamemonetize.com/1gjwgvl2j0ipdd9ybezeavu04y1nqjen/', 'Sports', 'Moto, Motocicleta, Corrida', 'https://img.gamemonetize.com/1gjwgvl2j0ipdd9ybezeavu04y1nqjen/512x384.jpg', 420, 480, '1gjwgvl2j0ipdd9ybezeavu04y1nqjen', 8),

('mini-batalhas-esportivas', 'Mini Batalhas Esportivas', 'Mini Batalhas Esportivas é uma coleção brilhante de jogos baseados em esportes. Você pode jogar contra um oponente de IA ou seu amigo usando controles divididos.', 'Para mover jogador 1 use AD e jogador 2 use setas esquerda e direita. Para pular jogador 1 use W e jogador 2 use seta para cima. Para atacar jogador 1 use barra de espaço e jogador 2 use 0 ou enter', 'https://html5.gamemonetize.com/w9az2zsezzwxou02zu6uayyarwe1a627/', 'Sports', 'Jogos 2 Jogadores, 2D, Arcade, Casual, Hypercasual, Esporte, Esportes', 'https://img.gamemonetize.com/w9az2zsezzwxou02zu6uayyarwe1a627/512x384.jpg', 1280, 720, 'w9az2zsezzwxou02zu6uayyarwe1a627', 8),

('moto-x3m-halloween', 'Moto X3M Halloween', 'Moto X3M é um jogo de corrida de motos com acrobacias malucas e uma reviravolta em obstáculos mortais e acidentes explosivos. Bem-vindo à versão especial "Terra Assombrada".', 'Use as setas do teclado para controlar', 'https://html5.gamemonetize.com/hlmgvewlf6122xcmkubad7s5f0ajf1fo/', 'Sports', 'Bicicleta, Halloween, Moto, Motocicleta', 'https://img.gamemonetize.com/hlmgvewlf6122xcmkubad7s5f0ajf1fo/512x384.jpg', 720, 480, 'hlmgvewlf6122xcmkubad7s5f0ajf1fo', 8),

('cidade-do-skate', 'Cidade do Skate', 'Cidade do Skate é um jogo de skate acrobático para crianças. Ande de skate até coletar todas as estrelas para completar o nível.', 'Para começar a andar de skate você precisa apertar a seta direita. Para controlar o skatista use as setas do teclado. Para fazer truques use Z e X, para pular use a barra de ESPAÇO', 'https://html5.gamemonetize.com/rstlghydkazgl4pbdoj2cgjgzypg2lwl/', 'Sports', 'Skate, Patinação', 'https://img.gamemonetize.com/rstlghydkazgl4pbdoj2cgjgzypg2lwl/512x384.jpg', 800, 600, 'rstlghydkazgl4pbdoj2cgjgzypg2lwl', 8),

('basquete-aleatorio', 'Basquete Aleatório', 'O basquete está aqui de sua forma mais engraçada e aleatória. No jogo Basquete Aleatório, tente fazer uma cesta usando apenas uma tecla com variações diferentes!', 'Jogador 1: W, Jogador 2: SETA PARA CIMA. Você pode jogar o jogo por controles de toque em dispositivos móveis ou tablets', 'https://html5.gamemonetize.com/anaaahgt57d5t2tddrbc1m4qq97vz1jd/', 'Sports', '2 Jogadores, Jogos 2 Jogadores, Basquete, Diversão, Engraçado, HTML5, Física, Pixel, Esporte, Esportes', 'https://img.gamemonetize.com/anaaahgt57d5t2tddrbc1m4qq97vz1jd/512x384.jpg', 900, 600, 'anaaahgt57d5t2tddrbc1m4qq97vz1jd', 8),

('estrelas-do-basquete-all', 'Estrelas do Basquete All', 'Estrelas do Basquete é um jogo legal de basquete para 2 jogadores. Escolha sua equipe e entre em um torneio desafiador.', 'Setas movem/pulam, Seta para baixo bloqueia/bombeia, X rouba/atira, Z super arremesso', 'https://html5.gamemonetize.com/ycc9yyyfyazoiibce061j1b7jx91tt8a/', 'Sports', 'Basquete', 'https://img.gamemonetize.com/ycc9yyyfyazoiibce061j1b7jx91tt8a/512x384.jpg', 920, 480, 'ycc9yyyfyazoiibce061j1b7jx91tt8a', 8),

('estacionamento-lamborghini-3', 'Estacionamento Lamborghini 3', 'Estacione seu carro de luxo na posição designada, que requer controle excelente. Você se atreve a desafiar?', 'P1 pode pressionar W S A e D para operar o movimento do veículo e espaço para frear. P2 pode pressionar as setas esquerda, direita, cima e baixo para operar o movimento do veículo e o teclado numérico 1 para frear', 'https://html5.gamemonetize.com/bltnauh5b7uptbr1ezj2yncpeiac03jn/', 'Sports', '2 Jogadores, Jogos 2 Jogadores, Carro, Dirigir, Estacionamento', 'https://img.gamemonetize.com/bltnauh5b7uptbr1ezj2yncpeiac03jn/512x384.jpg', 960, 600, 'bltnauh5b7uptbr1ezj2yncpeiac03jn', 8),

('basquete-epico', 'Basquete Épico', 'No Basquete Épico você encontrará física realista, personagens malucas, diversão ilimitada e um ranking mundial para subir o mais alto que puder.', 'Pressione o botão esquerdo do mouse, arraste para mirar, solte para lançar', 'https://html5.gamemonetize.com/15rv13nk1d6t9i7f8ezzjismvo0hbcoc/', 'Sports', 'Arcade, Basquete, Casual, Esporte, Esportes', 'https://img.gamemonetize.com/15rv13nk1d6t9i7f8ezzjismvo0hbcoc/512x384.jpg', 1280, 720, '15rv13nk1d6t9i7f8ezzjismvo0hbcoc', 8),

('corrida-formula-3d', 'Corrida Fórmula 3D', 'Corrida Fórmula 3D é um novo jogo de corrida 3D. Escolha seu carro de Fórmula Um e tente estabelecer novos recordes!', 'W A S D Setas movem, ESPAÇO freia', 'https://html5.gamemonetize.com/tia5pbecnefai0pnlkapzyzzfh0yobn4/', 'Sports', 'Carro, Dirigir, Corrida', 'https://img.gamemonetize.com/tia5pbecnefai0pnlkapzyzzfh0yobn4/512x384.jpg', 800, 600, 'tia5pbecnefai0pnlkapzyzzfh0yobn4', 8),

('ataque-basquete', 'Ataque Basquete', 'É hora de entrar na quadra para algumas enterradas malucas! Pegue a bola, dirija pela linha e balance a cesta!', 'Apenas Mouse', 'https://html5.gamemonetize.com/x5ch7xndlhqxdp0p71gmeizs8kg4nd2l/', 'Sports', '3D, Jogos 3D, Basquete, Menino, Meninos, Esporte', 'https://img.gamemonetize.com/x5ch7xndlhqxdp0p71gmeizs8kg4nd2l/512x384.jpg', 960, 640, 'x5ch7xndlhqxdp0p71gmeizs8kg4nd2l', 8); 