-- Migration 037: Adicionar jogos finais de esportes na página 8 (parte final)
-- Inserir jogos restantes de esportes traduzidos para português

INSERT INTO games (id, title, description, instructions, url, category, tags, thumb, width, height, gameid, page) VALUES
('herois-velocistas', 'Heróis Velocistas', 'O jogo Heróis Velocistas convida você para um torneio mundial de corrida. Os heróis da corrida podem ser você e seu amigo.', 'Toque as SETAS ESQUERDA DIREITA e A D alternadamente para correr', 'https://html5.gamemonetize.com/310ts4meky0hvxnxazhqqlc8o6du4rv8/', 'Sports', 'Jogos 2 Jogadores, 3D, Jogos 3D, Casual, Corrida, corrida, Simulação, WebGL', 'https://img.gamemonetize.com/310ts4meky0hvxnxazhqqlc8o6du4rv8/512x384.jpg', 800, 520, '310ts4meky0hvxnxazhqqlc8o6du4rv8', 8),

('luta-enterradas', 'Luta das Enterradas', 'Prepare-se para diversão de basquete com o jogo Luta das Enterradas 2P. Prepare-se quando a contagem regressiva começar e pegue a bola antes do seu oponente.', 'Jogador 1: Mover teclas A-D, Arremessar teclas W-S. Jogador 2: Mover setas Esquerda-Direita, Arremessar setas Cima-Baixo', 'https://html5.gamemonetize.com/ikcx0een75yb4w8gupe62jvyppzg6vs6/', 'Sports', '2 Jogadores, Jogos 2 Jogadores, 2D, Basquete, Engraçado, Esportes', 'https://img.gamemonetize.com/ikcx0een75yb4w8gupe62jvyppzg6vs6/512x384.jpg', 800, 450, 'ikcx0een75yb4w8gupe62jvyppzg6vs6', 8),

('heroi-do-tenis', 'Herói do Tênis', 'Escolha seu herói e compita contra 3 oponentes no evento de Tênis. Toque para cronometrar seus golpes à perfeição.', 'Toque, mouse ou teclas do cursor para balançar na bola. Jogo de um botão - timing é tudo', 'https://html5.gamemonetize.com/rxephxpfkvlhz0hbuh4rbx39tgsx6mrx/', 'Sports', 'Arcade, Esportes, Tênis', 'https://img.gamemonetize.com/rxephxpfkvlhz0hbuh4rbx39tgsx6mrx/512x384.jpg', 720, 405, 'rxephxpfkvlhz0hbuh4rbx39tgsx6mrx', 8),

('estradas-sinuosas', 'Estradas Sinuosas', 'Siga a estrada e passe pelos pontos de verificação para ganhar pontos, e colete moedas para comprar veículos. A jornada só fica mais e mais difícil.', 'Siga as instruções do jogo', 'https://html5.gamemonetize.com/xdfv9rv4i61grjme4mmhe0wna81g5cbp/', 'Sports', 'Carro, Carros, Dirigir, Kart, Obstáculo, Corrida, Corrida', 'https://img.gamemonetize.com/xdfv9rv4i61grjme4mmhe0wna81g5cbp/512x384.jpg', 1280, 720, 'xdfv9rv4i61grjme4mmhe0wna81g5cbp', 8),

('chuteira-de-ouro-2022', 'Chuteira de Ouro 2022', 'Ganhe a chuteira de ouro como artilheiro e ganhe outros troféus no processo. Você consegue fazer um hat trick?', 'Mova com mouse ou dedo, clique ou levante o dedo para chutar, não precisa deslizar', 'https://html5.gamemonetize.com/6lujax20kicvs9hc7p69eshjx4qscgrs/', 'Sports', 'Futebol, Esportes', 'https://img.gamemonetize.com/6lujax20kicvs9hc7p69eshjx4qscgrs/512x384.jpg', 800, 600, '6lujax20kicvs9hc7p69eshjx4qscgrs', 8),

('sinuca-3d', 'Sinuca 3D', 'Esta é uma experiência autêntica de sinuca 3D como você nunca viu no PC. Ao contrário de outros jogos de sinuca, Sinuca 3D oferece jogar sinuca em visualização 3D.', 'Controle do mouse', 'https://html5.gamemonetize.com/ozjq3f4vbq3z9l5gfhq7q7bd4bvo7vbv/', 'Sports', '3D, Jogos 3D, Ação, HTML5, Atirador, Tiro', 'https://img.gamemonetize.com/ozjq3f4vbq3z9l5gfhq7q7bd4bvo7vbv/512x384.jpg', 800, 600, 'ozjq3f4vbq3z9l5gfhq7q7bd4bvo7vbv', 8),

('futebol-aleatorio', 'Futebol Aleatório', 'O futebol está aqui de sua forma mais engraçada e aleatória. No jogo Futebol Aleatório, tente marcar um gol usando apenas uma tecla com variações diferentes!', 'Jogador 1: W, Jogador 2: SETA PARA CIMA. Você pode jogar o jogo por controles de toque em dispositivos móveis ou tablets', 'https://html5.gamemonetize.com/3n1k20ccttp0hvvr6ox2b41a8ibha9x3/', 'Sports', '2 Jogadores, Jogos 2 Jogadores, Bola, Futebol, Diversão, Engraçado, Física, Futebol, Esporte, Esportes', 'https://img.gamemonetize.com/3n1k20ccttp0hvvr6ox2b41a8ibha9x3/512x384.jpg', 800, 450, '3n1k20ccttp0hvvr6ox2b41a8ibha9x3', 8),

('mestre-do-tenis', 'Mestre do Tênis', 'Torne-se um mestre do tênis e mostre todos os seus talentos competitivos para vencer seus oponentes no jogo Mestres do Tênis.', 'Controles do Jogador 1: Setas para mover, X para rebater e Z para atacar', 'https://html5.gamemonetize.com/73735h3z94pu326yf9gs7b0a9acixuso/', 'Sports', 'Esportes, Tênis', 'https://img.gamemonetize.com/73735h3z94pu326yf9gs7b0a9acixuso/512x384.jpg', 920, 480, '73735h3z94pu326yf9gs7b0a9acixuso', 8),

('moto-x3m-festa-piscina', 'Moto X3M Festa na Piscina', 'Moto X3M é um jogo definitivo de corrida de motos online, muito adequado para jogadores que amam esportes extremos. Bem-vindo à versão especial "Festa na Piscina".', 'Use as setas do teclado para controlar', 'https://html5.gamemonetize.com/mim4uot21hygwai6uek2u1t2ovb3lkzd/', 'Sports', 'Bicicleta, Moto, Corrida', 'https://img.gamemonetize.com/mim4uot21hygwai6uek2u1t2ovb3lkzd/512x384.jpg', 720, 480, 'mim4uot21hygwai6uek2u1t2ovb3lkzd', 8),

('penalti-no-alvo', 'Pênalti no Alvo', 'É hora do pênalti! Você está confiante em suas habilidades? Acerte o alvo e não erre para se tornar o melhor!', 'Use mouse ou toque para mirar e chutar', 'https://html5.gamemonetize.com/os00yv4rjbamn3014mxc5mhyqw5jy2rv/', 'Sports', '1 Jogador, 2D, Futebol, Esporte', 'https://img.gamemonetize.com/os00yv4rjbamn3014mxc5mhyqw5jy2rv/512x384.jpg', 960, 540, 'os00yv4rjbamn3014mxc5mhyqw5jy2rv', 8),

('moto-x3m-original', 'Moto X3M Original', 'Moto X3M é um incrível jogo de corrida de motos com 25 níveis desafiadores. Então pegue sua motocicleta, coloque seu capacete e pegue um tempo no ar.', 'Setas dirigem/equilibram, Barra de espaço reaparecer no último checkpoint', 'https://html5.gamemonetize.com/cwvgstrd6an0nqgcf0rdd7phev53fnm1/', 'Sports', 'Bicicleta, Motocicleta, Corrida, Corrida', 'https://img.gamemonetize.com/cwvgstrd6an0nqgcf0rdd7phev53fnm1/512x384.jpg', 720, 480, 'cwvgstrd6an0nqgcf0rdd7phev53fnm1', 8),

('liverpool-vs-real-2022', 'Liverpool vs Real 2022', 'Esta é sua chance de ganhar o campeonato. Escolha Liverpool F.C. ou Real Madrid e chute e defenda seu caminho para o troféu', 'Mouse ou Toque para definir direção, elevação e curva do seu chute. Ao defender, toque ou clique nas luvas do goleiro quando aparecerem', 'https://html5.gamemonetize.com/4s4igxk8mcalex0xptrhjoj3yoojogf3/', 'Sports', 'Arcade, Futebol, Esporte, Esportes', 'https://img.gamemonetize.com/4s4igxk8mcalex0xptrhjoj3yoojogf3/512x384.jpg', 960, 540, '4s4igxk8mcalex0xptrhjoj3yoojogf3', 8); 