-- Migration 038: Adicionar jogos restantes de esportes na página 8 (última parte)
-- Inserir últimos jogos de esportes traduzidos para português

INSERT INTO games (id, title, description, instructions, url, category, tags, thumb, width, height, gameid, page) VALUES
('cabecas-do-futebol', 'Cabeças do Futebol', 'Viva sua história no futebol! Entre no campo, destrua seu oponente com vários chutes poderosos e power-ups divertidos e peculiares.', 'Mova-se lateralmente e pule com os botões de seta. Execute vários chutes com os botões da bola. Marque mais gols no tempo determinado e vença a partida', 'https://html5.gamemonetize.com/uzkm3h1igndrx9is3e3mzrhmwfpzv3zp/', 'Sports', 'Bola, Futebol, Combinação, Futebol', 'https://img.gamemonetize.com/uzkm3h1igndrx9is3e3mzrhmwfpzv3zp/512x384.jpg', 800, 600, 'uzkm3h1igndrx9is3e3mzrhmwfpzv3zp', 8),

('mestre-bicicleta', 'Mestre da Bicicleta', 'O chute mais incrível de todos os esportes (definitivamente futebol). A bicicleta, então um jogo onde você tenta vencer o goleiro e um defensor atirando apenas chutes de bicicleta.', 'Mouse para mover, clique para chutar. Nos celulares mova com o dedo, levante o dedo para chutar (não precisa deslizar)', 'https://html5.gamemonetize.com/oonsdaa12i0e2xf7096c318el03ayh0m/', 'Sports', 'Arcade, Futebol, Esportes', 'https://img.gamemonetize.com/oonsdaa12i0e2xf7096c318el03ayh0m/512x384.jpg', 600, 650, 'oonsdaa12i0e2xf7096c318el03ayh0m', 8),

('campeao-do-tapa', 'Campeão do Tapa', 'Campeonato de Tapas. Torne-se um Campeão do Tapa. Jogue contra o computador. No modo 2 Jogadores jogue com seus amigos locais e desafie-os.', 'Clique do mouse ou toque na tela para jogar', 'https://html5.gamemonetize.com/j5hv8x67fzdupua6pj668ec92lww2tml/', 'Sports', '.io, 1 Jogador, 3D, Ação, Aventura, Android, Arcade, Boxe, Meninos, Casual', 'https://img.gamemonetize.com/j5hv8x67fzdupua6pj668ec92lww2tml/512x384.jpg', 800, 600, 'j5hv8x67fzdupua6pj668ec92lww2tml', 8),

('mudanca-cubo', 'Mudança do Cubo', 'Mude a forma do cubo para passar pelos obstáculos.', 'Mude a forma do cubo para passar pelos obstáculos', 'https://html5.gamemonetize.com/0k9n0t7mlx8k3zg0a3etfqkezl4gb1pb/', 'Sports', 'HTML5, Hypercasual, Esporte', 'https://img.gamemonetize.com/0k9n0t7mlx8k3zg0a3etfqkezl4gb1pb/512x384.jpg', 800, 600, '0k9n0t7mlx8k3zg0a3etfqkezl4gb1pb', 8),

('el-clasico', 'El Clásico', 'El Clásico, a maior rivalidade de todo o esporte. Aqui está sua chance de se envolver, Escolha Real ou Barça e vença o El Clásico', 'Toque ou Clique para definir direção, altura e curva do seu chute', 'https://html5.gamemonetize.com/yha7c2v8calegde0qdunmgn8zlj9xdf7/', 'Sports', 'Futebol, Futebol, Esporte', 'https://img.gamemonetize.com/yha7c2v8calegde0qdunmgn8zlj9xdf7/512x384.jpg', 960, 540, 'yha7c2v8calegde0qdunmgn8zlj9xdf7', 8),

('trial-parkour-extremo', 'Trial Parkour Extremo', 'Tente alcançar os menores tempos em mais de 40 níveis neste jogo de acrobacias malucas, você tem que ser o mais rápido possível na corrida de bicicleta.', 'WASD ou Setas do Teclado', 'https://html5.gamemonetize.com/g2m4tesy8vwb0x3n1ydsybnst522lkq3/', 'Sports', 'Aventura, Bicicleta, Menino, Meninos, Carro, Carros, Engraçado, Moto, Motocicleta, Esportes', 'https://img.gamemonetize.com/g2m4tesy8vwb0x3n1ydsybnst522lkq3/512x384.jpg', 800, 600, 'g2m4tesy8vwb0x3n1ydsybnst522lkq3', 8),

('2-jogadores-futebol-among', '2 Jogadores Futebol Among', 'Prepare-se para as partidas de futebol mais desafiadoras com Among Soccer. Jogue contra dezenas de jogadores reais ou desafie seus amigos no modo "2 Jogadores".', 'Modo 2 Jogadores: Jogador 1: Pular Seta Cima, Esquerda Seta Esquerda, Direita Seta Direita, Chutar P ou Seta Baixo, Super Bônus K. Jogador 2: Pular W, Esquerda A, Direita D, Chutar S, Super Bônus Q', 'https://html5.gamemonetize.com/uoi3pc91mixkykwgdpjn88slj8u7d3z7/', 'Sports', '2 Jogadores, Jogos 2 Jogadores, 2D, Futebol, Futebol, Esporte', 'https://img.gamemonetize.com/uoi3pc91mixkykwgdpjn88slj8u7d3z7/512x384.jpg', 800, 600, 'uoi3pc91mixkykwgdpjn88slj8u7d3z7', 8),

('corrida-stickman-3d', 'Corrida Stickman 3D', 'Participe da corrida, vença contra os oponentes, seja o número 1 em todas as 3 rodadas para vencer os níveis e eliminar os oponentes.', 'Use mouse ou toque para jogar', 'https://html5.gamemonetize.com/93m159g7q6g18tqyyeud322kxv1lh0yq/', 'Sports', '1 Jogador, 3D, Jogos 3D, Corrida, Stickman', 'https://img.gamemonetize.com/93m159g7q6g18tqyyeud322kxv1lh0yq/512x384.jpg', 960, 600, '93m159g7q6g18tqyyeud322kxv1lh0yq', 8),

('jogo-corrida-panqueca', 'Jogo Corrida de Panqueca', 'Você precisa fazer panquecas deliciosas e dá-las aos clientes! Você pode adicionar frutas deliciosas, como morangos, bananas e mirtilos!', 'Deslize para mover', 'https://html5.gamemonetize.com/k8e084nhbes5msslwo6inumujh4l2v3o/', 'Sports', '3D, Meninos, Comida, Crianças, Obstáculo, corrida', 'https://img.gamemonetize.com/k8e084nhbes5msslwo6inumujh4l2v3o/512x384.jpg', 750, 1334, 'k8e084nhbes5msslwo6inumujh4l2v3o', 8); 