-- Migration: Add first 10 multiplayer games for page 9
-- Created: 2024

INSERT INTO games (id, title, description, instructions, url, category, tags, thumb, width, height, gameid, page) VALUES
(
  'mine-strike-diversao',
  'Mine Strike Diversão',
  'Mine Strike Diversão é um jogo divertido no estilo Minecraft. Coma bolos, biscoitos, peixe cozido e tudo que encontrar para crescer de tamanho enquanto você é pequeno. Mais importante, não coma batatas venenosas, pois elas reduzem sua experiência e te fazem menor! Ataque inimigos menores para ter melhor chance de sobreviver. Você pode se proteger fugindo de inimigos grandes para que não te matem com um golpe de sua arma poderosa! O jogo tem apenas 15 níveis, desde Steve com espada de madeira até Herobrine com nanosable. Consegue chegar ao nível 15 e se tornar o maior e mais forte do jogo?',
  'Mover - mouse, Atacar - botão esquerdo do mouse, Acelerar - botão direito do mouse',
  'https://html5.gamemonetize.com/bgkaq5jchbya9rff5jw6gnkwceukg16s/',
  'Multiplayer',
  '.io, Jogos .io, 2D, Ação, Animal, Arcade, Batalha, Bloco, Minecraft, Espada, Zumbi',
  'https://img.gamemonetize.com/bgkaq5jchbya9rff5jw6gnkwceukg16s/512x384.jpg',
  800,
  600,
  'bgkaq5jchbya9rff5jw6gnkwceukg16s',
  9
),
(
  'tiro-blocky-combat-swat-sobrevivencia',
  'Tiro Blocky Combat SWAT Sobrevivência',
  'Jogo de tiro Blocky Combat SWAT Sobrevivência Multiplayer na incrível arena de mapas divertidos, pronto para jogar 5 modos de jogo? Jogue com amigos ao redor do mundo, você pode jogar offline até 40 níveis. Você pode jogar com 18 armas adicionando camuflagem e acessórios. Divirta-se!',
  'WASD - mover, Mouse - mirar e atirar, ESPAÇO - pular, TAB - menu, SHIFT - correr, Q - trocar camuflagem, E - trocar acessório',
  'https://html5.gamemonetize.com/z4ajge69b989gm67dq59mkgv20ed6zg6/',
  'Multiplayer',
  'Ação, Sangue, Multiplayer, Pixel, Tiro, Atirador, Tiroteio',
  'https://img.gamemonetize.com/z4ajge69b989gm67dq59mkgv20ed6zg6/512x384.jpg',
  800,
  600,
  'z4ajge69b989gm67dq59mkgv20ed6zg6',
  9
),
(
  'mine-craft-io-multiplayer',
  'Mine Craft IO Multiplayer',
  'Mine Craft IO é um jogo baseado no minecraft. No Mine Craft, você pode fazer a mesma coisa que em um minecraft normal e ainda mais! Obtenha recursos, construa casas e vários mecanismos, faça amigos, proteja-se de mobs malignos à noite e jogadores agressivos.',
  'Controles: WASD - mover, E - abrir/fechar inventário do jogador, Left Shift - correr, Enter - chat, Botão Esquerdo do Mouse - atacar, Botão Direito do Mouse - ação, 1-8 - trocar item ativo',
  'https://html5.gamemonetize.com/i004avdmt9jezvey9tjvuzv9h1l2e9kx/',
  'Multiplayer',
  '.io, Jogos .io, Animal, Melhor, Bloco, Bomba, Arco, Tijolos, Bolo, Crafting, Criação, Fofo, Minecraft, Multiplayer, Zumbi',
  'https://img.gamemonetize.com/i004avdmt9jezvey9tjvuzv9h1l2e9kx/512x384.jpg',
  1000,
  800,
  'i004avdmt9jezvey9tjvuzv9h1l2e9kx',
  9
),
(
  'round-6-online-multiplayer',
  'Round 6 Online Multiplayer',
  'Você quer jogar Round 6 luz vermelha luz verde online com outros jogadores? Corra quando a boneca disser luz verde, pare quando disser luz vermelha. Se você não conseguir parar, a boneca vai detectar você e eliminá-lo do jogo. Aproveite o Round 6 com jogadores em grupos de 30 de todo o mundo. Preste atenção ao som do brinquedo para obter a melhor classificação.',
  'Use mouse ou touchpad para jogar este jogo. Você também pode usar as teclas W A S D ou setas',
  'https://html5.gamemonetize.com/f9kc49j4awgatd4pl3yfnns0bu0lcz4c/',
  'Multiplayer',
  '.io, Jogos .io, 3D, Ação, Arena, Batalha, Melhor, Casual, Escape, Hipercasual, IO, Multiplayer, Online, correr, corrida, WebGL',
  'https://img.gamemonetize.com/f9kc49j4awgatd4pl3yfnns0bu0lcz4c/512x384.jpg',
  800,
  600,
  'f9kc49j4awgatd4pl3yfnns0bu0lcz4c',
  9
),
(
  'sonic-corrida-rapida',
  'Sonic Corrida Rápida',
  'Sonic the Hedgehog e seus amigos estão de volta em um jogo de corrida cheio de ação! Um novo grande jogo cheio de diversão! Dispositivos móveis e desktop',
  'Mouse ou Toque para Jogar',
  'https://html5.gamemonetize.com/apq6vn2vd1iueahd9upn2uhe2gmihnjs/',
  'Multiplayer',
  'corrida, correr',
  'https://img.gamemonetize.com/apq6vn2vd1iueahd9upn2uhe2gmihnjs/512x384.jpg',
  800,
  480,
  'apq6vn2vd1iueahd9upn2uhe2gmihnjs',
  9
),
(
  'quem-e-o-impostor',
  'Quem é o Impostor',
  'Descubra quem é o impostor neste jogo de mistério e dedução multiplayer!',
  'Teclas de Seta',
  'https://html5.gamemonetize.com/mzk6ktnnhs4izve2ghkycz4vw7mo9edv/',
  'Multiplayer',
  '.io, Jogos .io, 2D, Android, Desenho',
  'https://img.gamemonetize.com/mzk6ktnnhs4izve2ghkycz4vw7mo9edv/512x384.jpg',
  854,
  480,
  'mzk6ktnnhs4izve2ghkycz4vw7mo9edv',
  9
),
(
  'round-6-io-batalha',
  'Round 6 IO Batalha',
  'Jogo multiplayer do Round 6! Colete gemas para crescer e caçar jogadores menores! Personalize seu personagem com chapéus e cores.',
  'Mouse para mover, Clique para acelerar',
  'https://html5.gamemonetize.com/j4drf322s2noxvmrvou4ed4j7a0h2ugv/',
  'Multiplayer',
  '.io, Jogos .io, Ação, Multiplayer',
  'https://img.gamemonetize.com/j4drf322s2noxvmrvou4ed4j7a0h2ugv/512x384.jpg',
  800,
  600,
  'j4drf322s2noxvmrvou4ed4j7a0h2ugv',
  9
),
(
  'cobra-craft-minecraft',
  'Cobra Craft Minecraft',
  'Cobra Craft Minecraft - é MINECRAFT + COBRA em um jogo dinâmico! Faça uma cobra crescer comendo diferentes blocos do Minecraft. Comendo um bloco de diamante você obtém o máximo de pontos. Acelere com o botão esquerdo do mouse, mas cuidado, você reduz o comprimento da cobra. Jogue TNT nos inimigos com o botão direito do mouse e chegue ao topo! Você pode proteger sua cobra se cercando com sua cauda. Neste caso, você está seguro!',
  'Movimento do mouse - Mover, Botão esquerdo do mouse - Acelerar, Botão direito do mouse - Jogar TNT, Enter - Chat',
  'https://html5.gamemonetize.com/evckpufpla0xoqwf0ihlwvxy3pc04dzi/',
  'Multiplayer',
  'Jogos .io, 2D, 3D, Animal, Arcade, Arena, Batalha, Bloco, Bomba, Minecraft, Slither, Cobra',
  'https://img.gamemonetize.com/evckpufpla0xoqwf0ihlwvxy3pc04dzi/512x384.jpg',
  1000,
  800,
  'evckpufpla0xoqwf0ihlwvxy3pc04dzi',
  9
),
(
  'jogo-cartas-uno-amigos',
  'Jogo de Cartas UNO Amigos',
  'UNO Amigos é o jogo de cartas clássico que é fácil de aprender e impossível de largar. É um jogo muito simples de aprender, mas ainda tem alguma complexidade estratégica.',
  'Mouse esquerdo',
  'https://html5.gamemonetize.com/nzyxeod3knb7uw2b6yry1l8su588dex0/',
  'Multiplayer',
  '.io, Jogos .io, Arcade, Carta, Cassino, Casual, Clássico, Estratégia, Unity3D',
  'https://img.gamemonetize.com/nzyxeod3knb7uw2b6yry1l8su588dex0/512x384.jpg',
  900,
  600,
  'nzyxeod3knb7uw2b6yry1l8su588dex0',
  9
),
(
  'round-6-luta-multiplayer',
  'Round 6 Luta Multiplayer',
  'Pronto para jogar uma luta na rua? Bem... Você pode se juntar com seu amigo e nocautear todos os inimigos vermelhos do Round 6! Você também lutará com a chefe Garota, som do Round 6, você se sentirá como em ação, você também tem possibilidade de jogar modo campanha e terminar todos os níveis, muito movimento de luta precisa usar para vencer, combinação, correr e pular. Divirta-se!',
  'SETA - MOVER, Z - SOCO PRESSIONE 2 SEGUNDOS SOCO PODEROSO, X - CHUTE ESCAPE AGARRAR, C - GUARDA, V - AGARRAR, SETA ESQUERDA E DIREITA - EMPURRE PARA 2 PARA CORRER ENTÃO PODE SOCAR OU CHUTAR, ESPAÇO - PULAR',
  'https://html5.gamemonetize.com/b6jfcy0rn288sn5p61pn86i2l6yyo8ni/',
  'Multiplayer',
  '1 Jogador, 2 Jogadores, Jogos 2 Jogadores, 3D, Jogos 3D, Luta, Lutando, Multiplayer, Luta de Rua, Unity3D, WebGL',
  'https://img.gamemonetize.com/b6jfcy0rn288sn5p61pn86i2l6yyo8ni/512x384.jpg',
  800,
  600,
  'b6jfcy0rn288sn5p61pn86i2l6yyo8ni',
  9
); 