-- Migration: Add second 10 multiplayer games for page 9
-- Created: 2024

INSERT INTO games (id, title, description, instructions, url, category, tags, thumb, width, height, gameid, page) VALUES
(
  'basquete-io-multiplayer',
  'Basquete IO Multiplayer',
  'Drible, arremesse, marque, VENÇA! Pegue a bola e enfrente o mundo com Basquete IO',
  'Teclas de seta, WASD, Arrastar Mouse',
  'https://html5.gamemonetize.com/2wk4ilq5edz9qb89worqc3qtwgcw3096/',
  'Multiplayer',
  '.io, Jogos .io, 3D, Jogos 3D, Ação, Basquete, Multiplayer, Esporte, Esportes',
  'https://img.gamemonetize.com/2wk4ilq5edz9qb89worqc3qtwgcw3096/512x384.jpg',
  800,
  600,
  '2wk4ilq5edz9qb89worqc3qtwgcw3096',
  9
),
(
  'atirador-urbano-multiplayer',
  'Atirador Urbano Multiplayer',
  'Atirador Urbano Multiplayer apresenta guerra urbana intensa com outros jogadores, use diferentes tipos de rifles de precisão para atirar em seus oponentes e tente obter a maior pontuação para vencer.',
  'WASD - Mover, Espaço - Pular, C - Agachar, Botão Esquerdo - Atirar, Botão Direito - Mirar, R - Recarregar, P - Menu de pausa, 1 2 3 - Selecionar arma',
  'https://html5.gamemonetize.com/v6mez3gdl9836lk86u790ucw0hgyz77u/',
  'Multiplayer',
  '3D, Jogos 3D, Ação, CSGO, Arma, Matando, Multiplayer, Tiro, Atirador, Tiroteio, Sniper, Unity3D, Guerra, WebGL',
  'https://img.gamemonetize.com/v6mez3gdl9836lk86u790ucw0hgyz77u/512x384.jpg',
  960,
  600,
  'v6mez3gdl9836lk86u790ucw0hgyz77u',
  9
),
(
  'apocalipse-zumbi-sobrevivencia-agora',
  'Apocalipse Zumbi Sobrevivência Agora',
  'Popular Sobrevivência Zumbi 3D - Último Jogo de Tiro Humano, todos vocês são exterminadores. Mantenha sua guarda alta e atire em zumbis neste jogo de tiro viciante com armas 3D épicas - batalhe pela sobrevivência em um apocalipse zumbi. Escolha a melhor arma para lutar contra os mortos que caminham em sua direção. Você precisará de estratégia e precisão para parar o ataque neste jogo de tiro zumbi.',
  'WASD - MOVER PERSONAGEM, MOUSE - ATIRAR MIRAR TROCAR ARMA, TAB - MENU, ESPAÇO - PULAR, Q - CAMUFLAGENS, E - ACESSÓRIOS',
  'https://html5.gamemonetize.com/4bul1aq72zf5a48zvpscm6dow8rc6oaa/',
  'Multiplayer',
  'Jogos 3D, Ação, Melhor, Louco, Arma, Multiplayer, Atirador, Tiroteio, Habilidade, Unity3D, WebGL, Zumbi',
  'https://img.gamemonetize.com/4bul1aq72zf5a48zvpscm6dow8rc6oaa/512x384.jpg',
  800,
  600,
  '4bul1aq72zf5a48zvpscm6dow8rc6oaa',
  9
),
(
  'atirador-minecraft-pixel-louco',
  'Atirador Minecraft Pixel Louco',
  'Arma de Bloco: Jogos de tiro FPS PvP Guerra-Online estão chegando com uma nova versão e muitas adições novas para manter a ação respondendo a um ritmo acelerado! Com novos mapas, armas incríveis e um novo sistema de competição de elite, Arma de Bloco: FPS PvP Guerra-Online vai te impressionar! Aniquile a competição em PVP em tempo real, enfrente seus desafiantes no modo explosão ou confira nosso modo assustador para um jogador!',
  'WASD - controlar personagem, Mouse - olhar ao redor atirar trocar arma na rolagem, Tab - menu, Q E - acessórios e camuflagem da arma, Enter - chat',
  'https://html5.gamemonetize.com/mrnu7obls97e32t5mo3qyfkju544318q/',
  'Multiplayer',
  'Ação, Diversão, Arma, Minecraft, Multiplayer, Pixel, Atirador, Tiroteio',
  'https://img.gamemonetize.com/mrnu7obls97e32t5mo3qyfkju544318q/512x384.jpg',
  800,
  600,
  'mrnu7obls97e32t5mo3qyfkju544318q',
  9
),
(
  'tiro-zumbi-fps-extremo-bons-vs-maus',
  'Tiro Zumbi FPS Extremo Bons vs Maus',
  'Tiro Zumbi FPS Extremo Bons vs Maus Garotos grátis para jogar contra muito inimigo AI como soldado e zumbi realista, 5 modos de jogo como gun game, sobrevivência, TDM, DM e muito mais, multiplayer jogar com amigos e offline com 40 níveis. Divirta-se aqui.',
  'WASD - mover, Mouse - atirar mirar olhar ao redor trocar arma, ESPAÇO - pular, TAB - menu, SHIFT - correr',
  'https://html5.gamemonetize.com/afazlcawhhxr8v6zalxj6zwtm1r58yyi/',
  'Multiplayer',
  'Sangue, Multiplayer, Tiro, Atirador, Tiroteio, Unity3D, WebGL',
  'https://img.gamemonetize.com/afazlcawhhxr8v6zalxj6zwtm1r58yyi/512x384.jpg',
  800,
  600,
  'afazlcawhhxr8v6zalxj6zwtm1r58yyi',
  9
),
(
  'contra-craft-multiplayer',
  'Contra Craft Multiplayer',
  'Contra Craft apresenta batalha multiplayer em diferentes mapas temáticos do minecraft e muitos tipos variados de armas para comprar e atirar em todos os jogadores rivais para vencer.',
  'WASD - Mover, Espaço - Pular, C - Agachar, Botão Esquerdo - Atirar, Botão Direito - Mirar, R - Recarregar, TAB - Menu de pausa, 1 2 3 - Selecionar arma',
  'https://html5.gamemonetize.com/j6doy20k2ti3aa0vea8g77f14q1vibg1/',
  'Multiplayer',
  '3D, Jogos 3D, Ação, Craft, CSGO, Arma, Matando, Multiplayer, Tiro, Atirador, Tiroteio, Unity3D, Guerra, WebGL',
  'https://img.gamemonetize.com/j6doy20k2ti3aa0vea8g77f14q1vibg1/512x384.jpg',
  960,
  600,
  'j6doy20k2ti3aa0vea8g77f14q1vibg1',
  9
),
(
  'apocalipse-zumbi-bunker-sobrevivencia',
  'Apocalipse Zumbi Bunker Sobrevivência',
  'Apocalipse Zumbi Bunker Sobrevivência online grátis para jogar contra muito inimigo AI como soldado e zumbi realista, 5 modos de jogo como gun game, sobrevivência, TDM, DM e muito mais, multiplayer jogar com amigos e camuflagem + acessórios em cada arma. Divirta-se aqui.',
  'WASD - mover, Mouse - atirar mirar olhar ao redor trocar arma, ESPAÇO - pular, TAB - menu, SHIFT - correr',
  'https://html5.gamemonetize.com/wlwgi4czrpygroha3lu336j790j7027x/',
  'Multiplayer',
  'Tiro, Tiroteio, Unity3D, WebGL',
  'https://img.gamemonetize.com/wlwgi4czrpygroha3lu336j790j7027x/512x384.jpg',
  800,
  600,
  'wlwgi4czrpygroha3lu336j790j7027x',
  9
),
(
  'steve-louco-io-batalha',
  'Steve Louco IO Batalha',
  'O jogo Steve Louco IO foi criado para diversão e luta rápida. A tarefa principal no Steve Louco é marcar o máximo de pontos possível e ser o mais legal. Para fazer isso, você precisa coletar diamantes e maçãs que aparecem no mapa. Por diamantes, você carrega mais experiência do que maçãs, mas graças às maçãs você pode recuperar sua saúde. Muitos diamantes caem do rival morto.',
  'Movimento do mouse - Mover, Botão esquerdo do mouse - Atacar, Botão direito do mouse - Acelerar, Enter - Chat',
  'https://html5.gamemonetize.com/uqzbzhkjckdjj96mn9sm0mcyoz68tagn/',
  'Multiplayer',
  'Ação, Animal, Bloco, Arco, Diversão, Engraçado, Minecraft, Atirador, Espada',
  'https://img.gamemonetize.com/uqzbzhkjckdjj96mn9sm0mcyoz68tagn/512x384.jpg',
  1000,
  800,
  'uqzbzhkjckdjj96mn9sm0mcyoz68tagn',
  9
),
(
  'guerreiros-evolucao-diversao',
  'Guerreiros Evolução Diversão',
  'Guerreiros Evolução Diversão é um jogo gratuito de estilo fantasia. Coma bifes, ovos, leite e tudo que encontrar para crescer de tamanho enquanto você é pequeno, mais importante não coma amanita, porque reduz sua experiência e você fica menor! Ataque inimigos menores, assim você tem melhor chance de ficar vivo. Você pode se proteger apenas fugindo de inimigos grandes para que não te matem com um golpe de sua arma poderosa.',
  'Atacar - botão esquerdo do mouse, Acelerar - botão direito do mouse',
  'https://html5.gamemonetize.com/gf8ve9ub8patlfqyyeplw3e40kjriymz/',
  'Multiplayer',
  'Batalha, Fantasia, Cavaleiro, Guerra',
  'https://img.gamemonetize.com/gf8ve9ub8patlfqyyeplw3e40kjriymz/512x384.jpg',
  800,
  600,
  'gf8ve9ub8patlfqyyeplw3e40kjriymz',
  9
),
(
  'minhoca-doce-batalha',
  'Minhoca Doce Batalha',
  'Minhoca Doce Batalha é o jogo original da cobra com novas aparências. escolha sua nova aparência de minhoca, clique em Iniciar e vá direto para a batalha de minhocas. Jogue contra outros, Coma doces para ficar maior. Se sua cabeça tocar outro jogador, você explodirá e então é game over. Mas se outros correrem para você, então eles morrerão, e você pode comer os restos de doces deles!',
  'Mouse ou Joystick para guiar sua minhoca',
  'https://html5.gamemonetize.com/dtb0czsws9pku94s4odrc1m4tujn9jam/',
  'Multiplayer',
  '.io, Jogos .io, Ação, Arcade, Hipercasual, Multiplayer, Simulação, Slither, Cobra, Estratégia, Minhoca, Minhocas',
  'https://img.gamemonetize.com/dtb0czsws9pku94s4odrc1m4tujn9jam/512x384.jpg',
  800,
  600,
  'dtb0czsws9pku94s4odrc1m4tujn9jam',
  9
); 