-- Migration: Add third 10 multiplayer games for page 9
-- Created: 2024

INSERT INTO games (id, title, description, instructions, url, category, tags, thumb, width, height, gameid, page) VALUES
(
  'ataque-critico-operacoes-globais',
  'Ataque Crítico Operações Globais',
  'Ataque Crítico Operações Globais apresenta gráficos de próxima geração e grande arsenal de armas modernas para atirar em jogadores rivais em diferentes mapas altamente detalhados.',
  'WASD - Mover, Mouse - Atirar, R - Recarregar, B - Comprar armas',
  'https://html5.gamemonetize.com/ju1jg4fg4beharxn9k6uck2286omnfm7/',
  'Multiplayer',
  '3D, Ação, CSGO, Arma, Multiplayer, Tiro, Atirador, Tiroteio, Unity3D, Guerra, WebGL',
  'https://img.gamemonetize.com/ju1jg4fg4beharxn9k6uck2286omnfm7/512x384.jpg',
  960,
  600,
  'ju1jg4fg4beharxn9k6uck2286omnfm7',
  9
),
(
  'assassino-io-halloween',
  'Assassino IO Halloween',
  'Mate e esconda corpos neste divertido jogo de assassinato online. Tente matar o máximo de pessoas possível na festa de Halloween. Tente não ser pego!',
  'Teclas de seta ou controles de toque para mover',
  'https://html5.gamemonetize.com/niseadlbd8923kfntkyjjy1ftloz4wss/',
  'Multiplayer',
  'Escape, Halloween, Matar, Matando',
  'https://img.gamemonetize.com/niseadlbd8923kfntkyjjy1ftloz4wss/512x384.jpg',
  800,
  600,
  'niseadlbd8923kfntkyjjy1ftloz4wss',
  9
),
(
  'arma-blocky-paintball-3',
  'Arma Blocky Paintball 3',
  'Bem-vindo ao outro incrível paintball! Multiplayer e single player esperando você tentar testar toda sua habilidade, inimigo como AI e zumbi para destruir em diferentes modos de jogo como equipe vs equipe, todos contra todos, gun game.',
  'WASD - mover, mouse - olhar ao redor atirar mirar, tab - menu, espaço - pular',
  'https://html5.gamemonetize.com/hocokhgzih155zic2x3vows5d2kc199j/',
  'Multiplayer',
  'Multiplayer, Pixel, Tiroteio',
  'https://img.gamemonetize.com/hocokhgzih155zic2x3vows5d2kc199j/512x384.jpg',
  800,
  600,
  'hocokhgzih155zic2x3vows5d2kc199j',
  9
),
(
  'craft-mine-nocaute-final',
  'Craft Mine Nocaute Final',
  'Jogo de corrida e vitória multiplayer online móvel temático do Minecraft. Passe muitas pessoas e seja o vencedor do primeiro estágio. então confie em sua memória e vença o estágio 2. Sobreviva ao 3º estágio o máximo e vença o jogo.',
  'Teclas de Seta e Botão de Espaço, Controle de Toque Móvel',
  'https://html5.gamemonetize.com/v7ffvzz951bhyleap3wum4937ma0szwn/',
  'Multiplayer',
  '1 Jogador, 3D, Jogos 3D, Ação, Aventura, Minecraft, Multiplayer',
  'https://img.gamemonetize.com/v7ffvzz951bhyleap3wum4937ma0szwn/512x384.jpg',
  800,
  600,
  'v7ffvzz951bhyleap3wum4937ma0szwn',
  9
),
(
  'combate-ataque-sobrevivencia-zumbi-multiplayer',
  'Combate Ataque Sobrevivência Zumbi Multiplayer',
  'Combate Ataque Sobrevivência Zumbi Multiplayer totalmente grátis para apostar muito inimigo AI como soldado e zumbi pixel realista, 5 configurações de jogo como jogo de arma, sobrevivência, TDM, DM, trancar toda arma por classificação, comprar personagens com XP multiplayer se divirtam com amigos próximos e também offline com 40 níveis.',
  'WASD - mover, Mouse - atirar mirar olhar ao redor trocar arma, ESPAÇO - pular, TAB - menu, SHIFT - correr',
  'https://html5.gamemonetize.com/6qp6iehvnxzwlppp3lbcw06htubmcznj/',
  'Multiplayer',
  'Atirador, Tiroteio, Unity3D, WebGL, Zumbi',
  'https://img.gamemonetize.com/6qp6iehvnxzwlppp3lbcw06htubmcznj/512x384.jpg',
  800,
  600,
  '6qp6iehvnxzwlppp3lbcw06htubmcznj',
  9
),
(
  'onda-sobrevivencia-zumbi-multiplayer',
  'Onda Sobrevivência Zumbi Multiplayer',
  'Onda Sobrevivência Zumbi Multiplayer grátis para jogar contra muito inimigo AI como soldado e zumbi realista, 5 modos de jogo como gun game, sobrevivência, TDM, DM e muito mais, multiplayer jogar com amigos e camuflagem + acessórios em cada arma. Divirta-se aqui.',
  'WASD - mover, Mouse - atirar mirar olhar ao redor trocar arma, ESPAÇO - pular, TAB - menu, SHIFT - correr',
  'https://html5.gamemonetize.com/6h1vk7k6inrzqr0uw8395srnhra7d1yk/',
  'Multiplayer',
  'Tiroteio',
  'https://img.gamemonetize.com/6h1vk7k6inrzqr0uw8395srnhra7d1yk/512x384.jpg',
  800,
  600,
  '6h1vk7k6inrzqr0uw8395srnhra7d1yk',
  9
),
(
  'hexagono-dois-corrida',
  'Hexágono Dois Corrida',
  'Hexágono Dois é um divertido jogo 3D de corrida e pulo para 1 Jogador e 2 Jogadores! Jogue este jogo online sozinho contra muitos outros personagens ou desafie um de seus melhores amigos para jogar no mesmo computador no modo tela dividida! Seu objetivo é continuar correndo em um chão formado por hexágonos, que simplesmente cairão assim que alguém os tocar.',
  'Setas WASD correr, Espaço Q pular',
  'https://html5.gamemonetize.com/asyi0bqah6bhoeiuej3p9esjwq1f732i/',
  'Multiplayer',
  'Jogos 2 Jogadores, Engraçado, Hipercasual, Pulando, Online, correndo',
  'https://img.gamemonetize.com/asyi0bqah6bhoeiuej3p9esjwq1f732i/512x384.jpg',
  800,
  600,
  'asyi0bqah6bhoeiuej3p9esjwq1f732i',
  9
),
(
  'desenho-confronto-multiplayer',
  'Desenho Confronto Multiplayer',
  'Desenho Confronto apresenta gráficos legais e batalhas multiplayer em vários mapas de desenhos animados, você deve usar diferentes tipos de armas para atirar em todos os jogadores rivais em seu caminho e tentar obter a maior pontuação para vencer cada rodada.',
  'WASD - Mover, Espaço - Pular, C - Agachar, Botão Esquerdo - Atirar, Botão Direito - Mirar, R - Recarregar, P - Menu de pausa, 1 2 3 - Selecionar arma',
  'https://html5.gamemonetize.com/p1lmq9u1fmpjn8d9h9p6gqb8diljbri1/',
  'Multiplayer',
  '3D, Jogos 3D, Ação, Desenho, Clash, CSGO, Arma, Matando, Multiplayer, Tiro, Atirador, Tiroteio, Unity3D, Guerra, WebGL',
  'https://img.gamemonetize.com/p1lmq9u1fmpjn8d9h9p6gqb8diljbri1/512x384.jpg',
  960,
  600,
  'p1lmq9u1fmpjn8d9h9p6gqb8diljbri1',
  9
),
(
  'jogo-arma-paintball-guerras',
  'Jogo Arma Paintball Guerras',
  'Bem-vindo às incríveis guerras de paintball jogo de arma! Multiplayer e campanha esperando você tentar testar toda sua habilidade, inimigo como ai e zumbi para destruir em diferentes modos de jogo como equipe vs equipe, todos contra todos, jogo de arma, você como zumbi e destruir todos os soldados e não esqueça nossa onda de sobrevivência zumbi onde você pode se divertir com seus amigos e completar todos os níveis.',
  'WASD - mover, mouse - olhar ao redor atirar mirar, tab - menu, espaço - pular',
  'https://html5.gamemonetize.com/nwlt1pmvhjaqm77jsrb7yrmhx21mgt23/',
  'Multiplayer',
  'Fogo, Multiplayer, Pixel, Atirador, Tiroteio, Unity3D, WebGL',
  'https://img.gamemonetize.com/nwlt1pmvhjaqm77jsrb7yrmhx21mgt23/512x384.jpg',
  800,
  600,
  'nwlt1pmvhjaqm77jsrb7yrmhx21mgt23',
  9
),
(
  'minhoca-io-atirador',
  'Minhoca IO Atirador',
  'Jogo de minhoca com minhocas atiradoras! Coma gemas para crescer mais. Atire em outras minhocas para dar um empurrão nelas!',
  'Mouse para mover, Clique no mouse para atirar, Segure o mouse para acelerar',
  'https://html5.gamemonetize.com/on57ewcv2740i24fbnohytevjs523pcr/',
  'Multiplayer',
  '.io, Jogos .io, 2D, Multiplayer, Slither',
  'https://img.gamemonetize.com/on57ewcv2740i24fbnohytevjs523pcr/512x384.jpg',
  800,
  600,
  'on57ewcv2740i24fbnohytevjs523pcr',
  9
); 